<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\RaceCards\RaceCard\RaceCardIRE;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\RaceCards\RaceCardIRE
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/racecards/778172';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Models\Bo\RaceCards\RaceInstance:832 ->getRaceCard()
            '2da5acbc24fe208eccce14fa3e696e03' => [
                0 => [
                    'race_instance_title' => 'Minorstown Handicap Hurdle',
                    'race_instance_uid' => 778172,
                    'rp_ages_allowed_desc' => '4yo+',
                    'official_rating_band_desc' => '80-95',
                    'race_datetime' => '2021-02-18 15:30:00',
                    'local_meeting_race_datetime' => '2021-02-18 15:30:00',
                    'hours_difference' => null,
                    'three_yo_min_weight_lbs' => null,
                    'minimum_weight_lbs' => 138,
                    'ages_allowed_uid' => 21,
                    'declared_runners' => 14,
                    'no_of_runners' => 14,
                    'distance_yard' => 3520,
                    'rp_tv_text' => 'RTV',
                    'race_condition_desc' => 'Winner will receive EUR 6,000 (Penalty Value: EUR 5,900) Second will receive EUR 2,000 Third will receive EUR 1,000 Fourth will receive EUR 500 Fifth will receive EUR 300 Sixth will receive EUR 200  An extended handicap hurdle for four years old and upwards rated 80-95   Top weight in the original handicap and after the time of declaration shall not be less than 12st and the minimum weight shall not be less than 9st 12lbs   About 2 miles  EUR 80 to enter, EUR 20 extra if declared to run  Penalties - Winner of a hurdle race after calculation of the handicap shall carry 5lb extra for each hurdle race won.                                                             ',
                    'going_type_desc' => 'Heavy',
                    'rp_penalties' => '(after calculation of the handicap), each hurdle won 5lb     ',
                    'course_uid' => 177,
                    'mixed_course_uid' => null,
                    'course_name' => 'CLONMEL',
                    'course_style_name' => 'Clonmel',
                    'rp_horse_types' => '4yo+ rated 80-95 ',
                    'rp_weights' => 'highest weight in the original handicap and after the time of declaration shall not be less than 12st          ',
                    'allowances' => null,
                    'entry_fee' => null,
                    'extra_fee' => null,
                    'country_code' => 'IRE',
                    'rp_stakes' => 10000,
                    'rp_ag_indicator' => 'G',
                    'weights_raised_lbs' => null,
                    'rp_auction_min' => null,
                    'rp_claim_min' => null,
                    'rp_confirmed' => null,
                    'race_status_code' => 'O',
                    'race_type_code' => 'H',
                    'race_group_uid' => 6,
                    'pool_prize_sterling' => 10000,
                    'race_type_desc' => 'Hurdle Turf',
                    'race_group_desc' => 'Handicap',
                    'going_type_code' => 'HY',
                    'no_of_fences' => 9,
                    'no_of_entries' => null,
                    'rp_stalls_position' => null,
                    'stage' => null,
                    'forfeit_number' => null,
                    'forfeit_value' => null,
                    'race_group_code' => 'H',
                    'safety_factor_number' => null,
                    'early_closing_race_yn' => null,
                    'reopened_yn' => 'N',
                    'division_preference' => null,
                    'prev_year_datetime' => '2020-02-13 15:15:00',
                    'prev_runners' => 0,
                    'prev_horse_name' => null,
                    'prev_draw' => null,
                    'prev_trainer' => null,
                    'prev_horse_age' => null,
                    'prev_weight_carried' => null,
                    'prev_odds' => null,
                    'prev_jockey' => null,
                    'weight_allowance_lbs' => null,
                    'int_1' => null,
                    'lookup_uid' => null,
                    'prev_rating' => 'OR',
                    'highest_official_rating' => null,
                    'perform_race_uid_atr' => null,
                    'perform_race_uid_ruk' => null,
                    'stalls_position_desc' => null,
                    'straight_round_jubilee_code' => null,
                    'live_tab' => 'N',
                    'race_number' => 4,
                    'weather_details' => '(Showers)',
                ],
            ],

             //Models\Bo\RaceCards\RaceInstance:1738 ->getLongHandicap()
            'b7716b78b22a33844a93a2ca83a62882' => [
                0 => [
                    'horse_uid' => 2550258,
                    'style_name' => 'Irregularheartbeat',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 168,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 2,
                    'horse_age' => 8,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                1 => [
                    'horse_uid' => 1504646,
                    'style_name' => 'Fallen Forest',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 167,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 5,
                    'horse_age' => 6,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                2 => [
                    'horse_uid' => 3075237,
                    'style_name' => 'Clonbury Bridge',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 165,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 12,
                    'horse_age' => 5,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                3 => [
                    'horse_uid' => 2214059,
                    'style_name' => 'Vitudurum',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 165,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 15,
                    'horse_age' => 6,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                4 => [
                    'horse_uid' => 3039431,
                    'style_name' => 'Added Bonus',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 164,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 16,
                    'horse_age' => 7,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                5 => [
                    'horse_uid' => 3032783,
                    'style_name' => 'Union Park',
                    'country_origin_code' => 'FR',
                    'weight_carried_lbs' => 164,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 17,
                    'horse_age' => 5,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                6 => [
                    'horse_uid' => 2577994,
                    'style_name' => 'Balkos',
                    'country_origin_code' => 'FR',
                    'weight_carried_lbs' => 163,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 18,
                    'horse_age' => 6,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                7 => [
                    'horse_uid' => 3046857,
                    'style_name' => 'Coole Arcade',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 161,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 27,
                    'horse_age' => 7,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                8 => [
                    'horse_uid' => 2392005,
                    'style_name' => 'Krickett',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 161,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 28,
                    'horse_age' => 8,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                9 => [
                    'horse_uid' => 855452,
                    'style_name' => 'Danegeld',
                    'country_origin_code' => 'GB',
                    'weight_carried_lbs' => 160,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 29,
                    'horse_age' => 9,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                10 => [
                    'horse_uid' => 2548821,
                    'style_name' => 'Working Capitol',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 159,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 32,
                    'horse_age' => 7,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                11 => [
                    'horse_uid' => 2655963,
                    'style_name' => 'Iridescent',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 158,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 34,
                    'horse_age' => 7,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                12 => [
                    'horse_uid' => 3187255,
                    'style_name' => 'Tangental',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 158,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 35,
                    'horse_age' => 5,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                13 => [
                    'horse_uid' => 1460341,
                    'style_name' => 'Just Another Lady',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 155,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 44,
                    'horse_age' => 8,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                14 => [
                    'horse_uid' => 1148889,
                    'style_name' => 'Charlotte Wells',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 153,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 46,
                    'horse_age' => 9,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                15 => [
                    'horse_uid' => 880101,
                    'style_name' => 'De Bennette',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 153,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 48,
                    'horse_age' => 12,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
                16 => [
                    'horse_uid' => 3136491,
                    'style_name' => 'Sweet Will',
                    'country_origin_code' => 'IRE',
                    'weight_carried_lbs' => 151,
                    'weights_raised_lbs' => null,
                    'extra_weight_lbs' => 0,
                    'saddle_cloth_no' => 49,
                    'horse_age' => 4,
                    'minimum_weight_lbs' => 138,
                    'three_yo_min_weight_lbs' => null,
                ],
            ],

            //Models\Bo\RaceCards\RaceInstance:1738 ->getHighestOfficialRating()
            '2e74f254ac8f430b06caa5ee8d9c0221' => [
                0 => [
                    'horse_uid' => 2550258,
                    'start_number' => 1,
                    'horse_name' => 'Irregularheartbeat',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 95,
                    'weight_carried_lbs' => 168,
                ],
                1 => [
                    'horse_uid' => 1504646,
                    'start_number' => 2,
                    'horse_name' => 'Fallen Forest',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 94,
                    'weight_carried_lbs' => 167,
                ],
                2 => [
                    'horse_uid' => 3075237,
                    'start_number' => 3,
                    'horse_name' => 'Clonbury Bridge',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 93,
                    'weight_carried_lbs' => 165,
                ],
                3 => [
                    'horse_uid' => 2214059,
                    'start_number' => 4,
                    'horse_name' => 'Vitudurum',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 92,
                    'weight_carried_lbs' => 165,
                ],
                4 => [
                    'horse_uid' => 3032783,
                    'start_number' => 17,
                    'horse_name' => 'Union Park',
                    'country_origin_code' => 'FR',
                    'official_rating' => 92,
                    'weight_carried_lbs' => 164,
                ],
                5 => [
                    'horse_uid' => 3136491,
                    'start_number' => 14,
                    'horse_name' => 'Sweet Will',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 92,
                    'weight_carried_lbs' => 151,
                ],
                6 => [
                    'horse_uid' => 3039431,
                    'start_number' => 5,
                    'horse_name' => 'Added Bonus',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 91,
                    'weight_carried_lbs' => 164,
                ],
                7 => [
                    'horse_uid' => 2577994,
                    'start_number' => 6,
                    'horse_name' => 'Balkos',
                    'country_origin_code' => 'FR',
                    'official_rating' => 90,
                    'weight_carried_lbs' => 163,
                ],
                8 => [
                    'horse_uid' => 2392005,
                    'start_number' => 8,
                    'horse_name' => 'Krickett',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 88,
                    'weight_carried_lbs' => 161,
                ],
                9 => [
                    'horse_uid' => 3046857,
                    'start_number' => 7,
                    'horse_name' => 'Coole Arcade',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 88,
                    'weight_carried_lbs' => 161,
                ],
                10 => [
                    'horse_uid' => 855452,
                    'start_number' => 9,
                    'horse_name' => 'Danegeld',
                    'country_origin_code' => 'GB',
                    'official_rating' => 87,
                    'weight_carried_lbs' => 160,
                ],
                11 => [
                    'horse_uid' => 3187255,
                    'start_number' => 10,
                    'horse_name' => 'Tangental',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 86,
                    'weight_carried_lbs' => 158,
                ],
                12 => [
                    'horse_uid' => 2548821,
                    'start_number' => 16,
                    'horse_name' => 'Working Capitol',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 86,
                    'weight_carried_lbs' => 159,
                ],
                13 => [
                    'horse_uid' => 2655963,
                    'start_number' => 15,
                    'horse_name' => 'Iridescent',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 85,
                    'weight_carried_lbs' => 158,
                ],
                14 => [
                    'horse_uid' => 1460341,
                    'start_number' => 11,
                    'horse_name' => 'Just Another Lady',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 82,
                    'weight_carried_lbs' => 155,
                ],
                15 => [
                    'horse_uid' => 1148889,
                    'start_number' => 12,
                    'horse_name' => 'Charlotte Wells',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 80,
                    'weight_carried_lbs' => 153,
                ],
                16 => [
                    'horse_uid' => 880101,
                    'start_number' => 13,
                    'horse_name' => 'De Bennette',
                    'country_origin_code' => 'IRE',
                    'official_rating' => 80,
                    'weight_carried_lbs' => 153,
                ],
            ],

            //Models\RaceInstancePrize:228 ->getForRaceInstanceId()
            '6deda17c7dc402232abc44803fa80015' => [
                0 => [
                    'position_no' => 1,
                    'prize_sterling' => 5267.86,
                    'prize_euro' => 5900,
                    'prize_usd' => 7216.96,
                ],
                1 => [
                    'position_no' => 2,
                    'prize_sterling' => 1696.43,
                    'prize_euro' => 1900,
                    'prize_usd' => 2324.11,
                ],
                2 => [
                    'position_no' => 3,
                    'prize_sterling' => 803.57,
                    'prize_euro' => 900,
                    'prize_usd' => 1100.89,
                ],
                3 => [
                    'position_no' => 4,
                    'prize_sterling' => 357.14,
                    'prize_euro' => 400,
                    'prize_usd' => 489.29,
                ],
                4 => [
                    'position_no' => 5,
                    'prize_sterling' => 178.57,
                    'prize_euro' => 200,
                    'prize_usd' => 244.64,
                ],
                5 => [
                    'position_no' => 6,
                    'prize_sterling' => 89.29,
                    'prize_euro' => 100,
                    'prize_usd' => 122.32,
                ],
            ],

            //Models\Bo\RaceCards\RaceInstance:1269 ->getOtherDeclaration()
            '21f49a615bf3f595458f1068e5b864c0' => [
            ],

            //Models\Bo\RaceCards\RaceInstance:1304 ->getForfeits()
            'd998fc82fe094271e5ecd8f17dd8a0fe' => [
            ],

            //Api\DataProvider\Bo\RaceCards\RaceWFA:96 ->getRaceInfo()
            '54a0a456c2987f7f7238e19e3530a14b' => [
                [
                    'race_type_code' => 'H',
                    'race_datetime' => '2018-06-05 14:15:00',
                    'race_status_code' => 'R',
                    'distance_yard' => 3902,
                    'going_type_code' => 'G',
                ],
            ],

            //Api\DataProvider\Bo\RaceCards\RaceWFA:64 ->getTopStats()
            '7189ce6ec563792461c4a18d52444759' => [
                [
                    'max_age' => 10,
                    'min_age' => 4,
                    'top_age' => 6,
                ],
            ],

            //Api\DataProvider\Bo\RaceCards\RaceWFA:226 ->getRaceHorses()
            '38a34f34570ab0c7fcc9c0042552f086' => [
                [
                    'horse_uid' => 1021466,
                    'adjusted_age' => 4,
                    'age' => 4,
                    'weight_carried_lbs' => 150,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 1044041,
                    'adjusted_age' => 4,
                    'age' => 4,
                    'weight_carried_lbs' => 158,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 969025,
                    'adjusted_age' => 5,
                    'age' => 6,
                    'weight_carried_lbs' => 166,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 888963,
                    'adjusted_age' => 5,
                    'age' => 6,
                    'weight_carried_lbs' => 164,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 1178848,
                    'adjusted_age' => 5,
                    'age' => 6,
                    'weight_carried_lbs' => 157,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 903943,
                    'adjusted_age' => 5,
                    'age' => 7,
                    'weight_carried_lbs' => 162,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 938282,
                    'adjusted_age' => 5,
                    'age' => 7,
                    'weight_carried_lbs' => 155,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 841587,
                    'adjusted_age' => 5,
                    'age' => 7,
                    'weight_carried_lbs' => 146,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 1205113,
                    'adjusted_age' => 5,
                    'age' => 7,
                    'weight_carried_lbs' => 153,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
                [
                    'horse_uid' => 824468,
                    'adjusted_age' => 5,
                    'age' => 10,
                    'weight_carried_lbs' => 140,
                    'wfage' => 4,
                    'wfa' => 0,
                    'currhp' => 0,
                    'currhp2' => 0,
                    'lsnum' => 0,
                    'lsnum2' => 0,
                ],
            ],

            //Api\DataProvider\Bo\RaceCards\RaceWFA:303 ->getWfAgesJumps()
            '4051c7c91f5abef5dcd8fed3ed74f9d2' => [
                [
                    'age' => 4,
                    'wfa' => 17,
                    'race_type_code' => 'C',
                ],
                [
                    'age' => 4,
                    'wfa' => 3,
                    'race_type_code' => 'H',
                ],
            ],

            //Api\DataProvider\Bo\RaceCards:832 ->getRaceAttributes()
            '9ca651f17e13b65eeaf058d8330006ec' => [
                0 => [
                    'race_attrib_desc' => '4yo+',
                    'race_attrib_code' => 'Age',
                    'race_attrib_uid' => 20,
                    'race_instance_uid' => 778172,
                ],
                1 => [
                    'race_attrib_desc' => 'H',
                    'race_attrib_code' => 'Type',
                    'race_attrib_uid' => 152,
                    'race_instance_uid' => 778172,
                ],
                2 => [
                    'race_attrib_desc' => 'Hcap',
                    'race_attrib_code' => 'Handicap',
                    'race_attrib_uid' => 200,
                    'race_instance_uid' => 778172,
                ],
                3 => [
                    'race_attrib_desc' => 'Turf',
                    'race_attrib_code' => 'Surface',
                    'race_attrib_uid' => 411,
                    'race_instance_uid' => 778172,
                ],
                4 => [
                    'race_attrib_desc' => 'Racing TV',
                    'race_attrib_code' => 'TV',
                    'race_attrib_uid' => 506,
                    'race_instance_uid' => 778172,
                ],
            ],

            //Api\DataProvider\Bo\RaceCards:832 ->getCourseMap()
            'da82ddaef0ed4bc9a74561b490d86913' => [
                0 => [
                    'course_uid' => 177,
                    'course_name' => 'CLONMEL',
                    'latitude' => 52.330986,
                    'longitude' => -7.781153,
                    'zoom' => 14,
                    'country_code' => 'IRE',
                    'course_type_code' => 'B',
                    'race_type_code' => 'H',
                    'straight_round_jubilee' => null,
                    'course_comment' => 'right-handed, undulating, stiff uphill finish (1m2f)',
                    'rp_detailed_flat_desc' => 'Right-handed, undulating track with stiff uphill finish of 2 1/2f. Circuit 1m2f.',
                    'rp_detailed_aw_desc' => null,
                    'rp_detailed_jump_desc' => 'Right-handed, undulating track with stiff uphill finish of 2 1/2f. Circuit 1m2f.',
                    'rp_detailed_hurdle_desc' => null,
                    'rp_detailed_chase_desc' => null,
                ],
            ],
        ];
    }
}
