<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Profile\Owner\Horses;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\Profile\Owner\Horses
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/profile/owner/199331/horses/2018/GB/flat/aw';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Models\Bo\OwnerProfile\RaceInstance:796 ->getHorses()
            'a27ea5a407b60f023cacc2b511619370' => [
                [
                    'races_number' => 3,
                    'place_1st_number' => 2,
                    'win_prize' => 27580.0,
                    'total_prize' => 29910.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 27580.0,
                    'net_total_prize_money' => 29910.0,
                    'stake' => 2.409,
                    'rpr' => 102,
                    'horse_uid' => 978804,
                    'horse_style_name' => 'Dubawi Fifty',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 695130,
                    'trainer_uid' => 16945,
                    'trainer_style_name' => 'Karen McLintock',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 5530.99,
                    'total_prize' => 5530.99,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 5530.99,
                    'net_total_prize_money' => 5530.99,
                    'stake' => 3.5,
                    'rpr' => null,
                    'horse_uid' => 1558829,
                    'horse_style_name' => 'Crack On Crack On',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 698715,
                    'trainer_uid' => 5863,
                    'trainer_style_name' => 'Clive Cox',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 5530.99,
                    'total_prize' => 5530.99,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 5530.99,
                    'net_total_prize_money' => 5530.99,
                    'stake' => 1.375,
                    'rpr' => 96,
                    'horse_uid' => 1008763,
                    'horse_style_name' => 'Now Children',
                    'country_origin_code' => 'IRE',
                    'max_race_instance_uid' => 692584,
                    'trainer_uid' => 5863,
                    'trainer_style_name' => 'Clive Cox',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 1,
                    'win_prize' => 3105.12,
                    'total_prize' => 3905.12,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 3105.12,
                    'net_total_prize_money' => 3905.12,
                    'stake' => -1.5,
                    'rpr' => 74,
                    'horse_uid' => 1605448,
                    'horse_style_name' => 'Mighty Mac',
                    'country_origin_code' => 'IRE',
                    'max_race_instance_uid' => 696883,
                    'trainer_uid' => 13917,
                    'trainer_style_name' => 'Ralph Beckett',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 3881.4,
                    'total_prize' => 3881.4,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 3881.4,
                    'net_total_prize_money' => 3881.4,
                    'stake' => 8.0,
                    'rpr' => 84,
                    'horse_uid' => 1135280,
                    'horse_style_name' => 'Come On Come On',
                    'country_origin_code' => 'IRE',
                    'max_race_instance_uid' => 697121,
                    'trainer_uid' => 5863,
                    'trainer_style_name' => 'Clive Cox',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 3752.02,
                    'total_prize' => 3752.02,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 3752.02,
                    'net_total_prize_money' => 3752.02,
                    'stake' => 16.0,
                    'rpr' => 80,
                    'horse_uid' => 1787819,
                    'horse_style_name' => 'Good Boy Alfie',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 692183,
                    'trainer_uid' => 24548,
                    'trainer_style_name' => 'Keith Dalgleish',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 2887.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 2887.5,
                    'stake' => -1.0,
                    'rpr' => 97,
                    'horse_uid' => 859100,
                    'horse_style_name' => 'Mixboy',
                    'country_origin_code' => 'FR',
                    'max_race_instance_uid' => 692971,
                    'trainer_uid' => 24548,
                    'trainer_style_name' => 'Keith Dalgleish',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 924.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 924.0,
                    'stake' => -1.0,
                    'rpr' => 69,
                    'horse_uid' => 1276372,
                    'horse_style_name' => 'Costa Percy',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 698697,
                    'trainer_uid' => 15552,
                    'trainer_style_name' => 'Jennie Candlish',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 600.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 600.0,
                    'stake' => -2.0,
                    'rpr' => 61,
                    'horse_uid' => 1558802,
                    'horse_style_name' => 'Rose Tinted Spirit',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 692227,
                    'trainer_uid' => 13917,
                    'trainer_style_name' => 'Ralph Beckett',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 461.76,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 461.76,
                    'stake' => -1.0,
                    'rpr' => 67,
                    'horse_uid' => 1911832,
                    'horse_style_name' => 'Get Back Get Back',
                    'country_origin_code' => 'IRE',
                    'max_race_instance_uid' => 696853,
                    'trainer_uid' => 5863,
                    'trainer_style_name' => 'Clive Cox',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 400.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 400.0,
                    'stake' => -1.0,
                    'rpr' => 51,
                    'horse_uid' => 1485777,
                    'horse_style_name' => 'Hello My Sunshine',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 691120,
                    'trainer_uid' => 16945,
                    'trainer_style_name' => 'Karen McLintock',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 300.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 300.0,
                    'stake' => -1.0,
                    'rpr' => null,
                    'horse_uid' => 997693,
                    'horse_style_name' => 'Youre Always Right',
                    'country_origin_code' => 'IRE',
                    'max_race_instance_uid' => 691104,
                    'trainer_uid' => 28343,
                    'trainer_style_name' => 'Johnny Farrelly',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 91,
                    'horse_uid' => 872527,
                    'horse_style_name' => 'Keep In Line',
                    'country_origin_code' => 'GER',
                    'max_race_instance_uid' => 694685,
                    'trainer_uid' => 13928,
                    'trainer_style_name' => 'Alan King',
                    'trainer_ptp_type_code' => 'N',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 37,
                    'horse_uid' => 1828573,
                    'horse_style_name' => 'Where\'s Mummy',
                    'country_origin_code' => 'GB',
                    'max_race_instance_uid' => 696247,
                    'trainer_uid' => 20451,
                    'trainer_style_name' => 'Neil Mulholland',
                    'trainer_ptp_type_code' => 'N',
                ],
            ],
        ];
    }
}
