<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\RaceCards\TenYearTrends\General;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

class Test extends ApiRouteTestPrototype
{

    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/racecards/ten-year-trends/701456';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:511 ->getRaceInfo()
            'a6b96ec4cf0e21526306761a577bc797' => [
                [
                    'race_type_code' => 'X',
                    'race_group_code' => 'H',
                ],
            ],
            //Api\DataProvider\Bo\LastYearRaces:114 ->getPastRacesIDs()
            '711cfe80d9d45a0ac6938759c02d6b3b' => [
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 506277,
                    'race_datetime' => '2010-05-25 16:00:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 531168,
                    'race_datetime' => '2011-05-24 16:00:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 555004,
                    'race_datetime' => '2012-05-29 16:20:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 579400,
                    'race_datetime' => '2013-06-04 16:15:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 601884,
                    'race_datetime' => '2014-05-27 15:40:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 625848,
                    'race_datetime' => '2015-05-26 15:40:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 650648,
                    'race_datetime' => '2016-05-31 20:50:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 675397,
                    'race_datetime' => '2017-05-30 14:40:00',
                ],
                [
                    'root_uid' => 701456,
                    'race_instance_uid' => 701456,
                    'race_datetime' => '2018-05-29 13:40:00',
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:569 ->getStats()
            '7b394253f7db4b4e9bed00bcbe85c1c8' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:574 ->getStats()
            '3ced55a90f138095974413b15aa7bb16' => [
                [
                    'diff_ages' => 1,
                    'diff_weights' => 17,
                    'no_of_races' => 8,
                    'no_of_races_or' => 8,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:608 ->getWinStats()
            '78351f16a8d5a947b25e6a3f49aa176c' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:614 ->getWinStats()
            '7dda2e569f2b476733a2279def79a7dc' => [
                [
                    'min_wt' => 124,
                    'max_wt' => 133,
                    'min_or' => 63,
                    'max_or' => 75,
                    'min_age' => 3,
                    'max_age' => 3,
                    'min_sp' => 1.375,
                    'max_sp' => 14.0,
                    'min_runners' => 9,
                    'max_runners' => 14,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:889 ->getOddsValues()
            'e281c8805a62251c63e45bf4748ecdbe' => [
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '12',
                    'horse_uid' => 742039,
                    'odds_value' => 1.375,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '2',
                    'horse_uid' => 732523,
                    'odds_value' => 5.5,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '9',
                    'horse_uid' => 724478,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '1',
                    'horse_uid' => 740110,
                    'odds_value' => 11.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '4',
                    'horse_uid' => 737651,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '3',
                    'horse_uid' => 737463,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '10',
                    'horse_uid' => 739225,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '7',
                    'horse_uid' => 734073,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '5',
                    'horse_uid' => 739291,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '6',
                    'horse_uid' => 730511,
                    'odds_value' => 22.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '8',
                    'horse_uid' => 731008,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '11',
                    'horse_uid' => 736167,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '13',
                    'horse_uid' => 729760,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '6',
                    'horse_uid' => 774371,
                    'odds_value' => 3.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '2',
                    'horse_uid' => 764122,
                    'odds_value' => 4.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '5',
                    'horse_uid' => 749337,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '3',
                    'horse_uid' => 782045,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '11',
                    'horse_uid' => 758583,
                    'odds_value' => 6.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '1',
                    'horse_uid' => 749733,
                    'odds_value' => 11.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '4',
                    'horse_uid' => 755942,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '13',
                    'horse_uid' => 761732,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '10',
                    'horse_uid' => 759340,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '14',
                    'horse_uid' => 753235,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '7',
                    'horse_uid' => 759361,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '9',
                    'horse_uid' => 758186,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '8',
                    'horse_uid' => 754194,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '12',
                    'horse_uid' => 760954,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '1',
                    'horse_uid' => 795409,
                    'odds_value' => 1.375,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '6',
                    'horse_uid' => 794202,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '3',
                    'horse_uid' => 797337,
                    'odds_value' => 6.5,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '4',
                    'horse_uid' => 791435,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '9',
                    'horse_uid' => 779165,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '13',
                    'horse_uid' => 789957,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '10',
                    'horse_uid' => 785089,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '8',
                    'horse_uid' => 779344,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '7',
                    'horse_uid' => 783314,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '5',
                    'horse_uid' => 783465,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '12',
                    'horse_uid' => 789233,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '2',
                    'horse_uid' => 785638,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '11',
                    'horse_uid' => 787286,
                    'odds_value' => 80.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '5',
                    'horse_uid' => 827739,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '7',
                    'horse_uid' => 821748,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '4',
                    'horse_uid' => 812147,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '3',
                    'horse_uid' => 802215,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '2',
                    'horse_uid' => 829389,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '1',
                    'horse_uid' => 814016,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '6',
                    'horse_uid' => 805613,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '8',
                    'horse_uid' => 814926,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '9',
                    'horse_uid' => 813908,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '3',
                    'horse_uid' => 842168,
                    'odds_value' => 2.25,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '5',
                    'horse_uid' => 842021,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '2',
                    'horse_uid' => 831606,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '7',
                    'horse_uid' => 832502,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '1',
                    'horse_uid' => 840269,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '4',
                    'horse_uid' => 839135,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '10',
                    'horse_uid' => 828078,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '13',
                    'horse_uid' => 839574,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '8',
                    'horse_uid' => 828212,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '12',
                    'horse_uid' => 838210,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '11',
                    'horse_uid' => 838880,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '6',
                    'horse_uid' => 842777,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '9',
                    'horse_uid' => 839241,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '2',
                    'horse_uid' => 869349,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '4',
                    'horse_uid' => 871688,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '13',
                    'horse_uid' => 874868,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '3',
                    'horse_uid' => 855781,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '7',
                    'horse_uid' => 852772,
                    'odds_value' => 10.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '12',
                    'horse_uid' => 867550,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '9',
                    'horse_uid' => 880286,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '6',
                    'horse_uid' => 863686,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '1',
                    'horse_uid' => 866002,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '8',
                    'horse_uid' => 858734,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '14',
                    'horse_uid' => 866929,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '10',
                    'horse_uid' => 870780,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '5',
                    'horse_uid' => 859753,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '11',
                    'horse_uid' => 861301,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '3',
                    'horse_uid' => 503615,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '1',
                    'horse_uid' => 889985,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '2',
                    'horse_uid' => 899105,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '5',
                    'horse_uid' => 889192,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '4',
                    'horse_uid' => 882473,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '7',
                    'horse_uid' => 895844,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '6',
                    'horse_uid' => 885692,
                    'odds_value' => 10.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '8',
                    'horse_uid' => 885999,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '9',
                    'horse_uid' => 900517,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '1',
                    'horse_uid' => 1214424,
                    'odds_value' => 1.625,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '2',
                    'horse_uid' => 1158639,
                    'odds_value' => 3.5,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '7',
                    'horse_uid' => 1013248,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '3',
                    'horse_uid' => 1007856,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '4',
                    'horse_uid' => 1201686,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '6',
                    'horse_uid' => 1046139,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '5',
                    'horse_uid' => 1030763,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '9',
                    'horse_uid' => 1049199,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '8',
                    'horse_uid' => 1052576,
                    'odds_value' => 66.0,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:1057 ->getLastYearsWinRaces()
            'a3ae7da7e1ea6c1e96406a5123b1a563' => [
                [
                    'race_instance_uid' => 531168,
                    'race_datetime' => '2011-05-24 16:00:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 14,
                    'horse_uid' => 749733,
                    'age' => 3,
                    'rpr' => 72,
                    'weight_carried_lbs' => 128,
                    'adj_weight_carried_lbs' => 128,
                    'odds_value' => 11.0,
                    'odds_desc' => '11/1',
                    'trainer_uid' => 9003,
                    'trainer_name' => 'Marco Botti',
                    'trainer_search_name' => 'BOTTI',
                    'jockey_uid' => 83607,
                    'jockey_name' => 'Adam Kirby',
                    'jockey_search_name' => 'KIRBY',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_datetime' => '2010-05-25 16:00:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 740110,
                    'age' => 3,
                    'rpr' => 72,
                    'weight_carried_lbs' => 127,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 11.0,
                    'odds_desc' => '11/1',
                    'trainer_uid' => 144,
                    'trainer_name' => 'Alan Bailey',
                    'trainer_search_name' => 'BAILEY',
                    'jockey_uid' => 7458,
                    'jockey_name' => 'Franny Norton',
                    'jockey_search_name' => 'NORTON',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_datetime' => '2017-05-30 14:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 1214424,
                    'age' => 3,
                    'rpr' => 70,
                    'weight_carried_lbs' => 133,
                    'adj_weight_carried_lbs' => 133,
                    'odds_value' => 1.625,
                    'odds_desc' => '13/8F',
                    'trainer_uid' => 9546,
                    'trainer_name' => 'Saeed bin Suroor',
                    'trainer_search_name' => 'SUROOR',
                    'jockey_uid' => 83746,
                    'jockey_name' => 'Silvestre De Sousa',
                    'jockey_search_name' => 'SOUSA',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_datetime' => '2012-05-29 16:20:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 795409,
                    'age' => 3,
                    'rpr' => 75,
                    'weight_carried_lbs' => 133,
                    'adj_weight_carried_lbs' => 133,
                    'odds_value' => 1.375,
                    'odds_desc' => '11/8F',
                    'trainer_uid' => 10613,
                    'trainer_name' => 'Jeremy Noseda',
                    'trainer_search_name' => 'NOSEDA',
                    'jockey_uid' => 79202,
                    'jockey_name' => 'Ryan Moore',
                    'jockey_search_name' => 'MOORE',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_datetime' => '2014-05-27 15:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 840269,
                    'age' => 3,
                    'rpr' => 64,
                    'weight_carried_lbs' => 124,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 12.0,
                    'odds_desc' => '12/1',
                    'trainer_uid' => 99,
                    'trainer_name' => 'Chris Wall',
                    'trainer_search_name' => 'WALL',
                    'jockey_uid' => 85841,
                    'jockey_name' => 'Ashley Morgan',
                    'jockey_search_name' => 'MORGAN',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_datetime' => '2013-06-04 16:15:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 814016,
                    'age' => 3,
                    'rpr' => 70,
                    'weight_carried_lbs' => 128,
                    'adj_weight_carried_lbs' => 128,
                    'odds_value' => 12.0,
                    'odds_desc' => '12/1',
                    'trainer_uid' => 18920,
                    'trainer_name' => 'Eve Johnson Houghton',
                    'trainer_search_name' => 'HOUGHTON',
                    'jockey_uid' => 86606,
                    'jockey_name' => 'John Fahy',
                    'jockey_search_name' => 'FAHY',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_datetime' => '2016-05-31 20:50:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 889985,
                    'age' => 3,
                    'rpr' => 63,
                    'weight_carried_lbs' => 127,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 4.0,
                    'odds_desc' => '4/1',
                    'trainer_uid' => 9036,
                    'trainer_name' => 'Ed Dunlop',
                    'trainer_search_name' => 'DUNLOP',
                    'jockey_uid' => 76957,
                    'jockey_name' => 'Paul Hanagan',
                    'jockey_search_name' => 'HANAGAN',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_datetime' => '2015-05-26 15:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 14,
                    'horse_uid' => 866002,
                    'age' => 3,
                    'rpr' => 69,
                    'weight_carried_lbs' => 132,
                    'adj_weight_carried_lbs' => 132,
                    'odds_value' => 14.0,
                    'odds_desc' => '14/1',
                    'trainer_uid' => 19662,
                    'trainer_name' => 'Jeremy Gask',
                    'trainer_search_name' => 'GASK',
                    'jockey_uid' => 88632,
                    'jockey_name' => 'Harry Bentley',
                    'jockey_search_name' => 'BENTLEY',
                    'rule4_value' => 0.0,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:236 ->getMinMaxSPDesc()
            'a2ce639babaa1a4d2b21e4fe7e7b4702' => [
                [
                    'min_sp_desc' => '11/8F',
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:252 ->getMinMaxSPDesc()
            '9f7b888de8102451a8de79e1f977a733' => [
                [
                    'max_sp_desc' => '14/1',
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:540 ->getAllOddsList()
            '1f02442b0bd8e6675ea28bc0d8d26fa2' => [
                [
                    'odds_value' => 0.015,
                    'odds_desc' => '1/66',
                ],
                [
                    'odds_value' => 0.025,
                    'odds_desc' => '1/40',
                ],
                [
                    'odds_value' => 0.03,
                    'odds_desc' => '1/33',
                ],
                [
                    'odds_value' => 0.04,
                    'odds_desc' => '1/25',
                ],
                [
                    'odds_value' => 0.05,
                    'odds_desc' => '1/20',
                ],
                [
                    'odds_value' => 0.063,
                    'odds_desc' => '1/16',
                ],
                [
                    'odds_value' => 0.071,
                    'odds_desc' => '1/14',
                ],
                [
                    'odds_value' => 0.083,
                    'odds_desc' => '1/12',
                ],
                [
                    'odds_value' => 0.091,
                    'odds_desc' => '1/11',
                ],
                [
                    'odds_value' => 0.1,
                    'odds_desc' => '1/10',
                ],
                [
                    'odds_value' => 0.111,
                    'odds_desc' => '1/9',
                ],
                [
                    'odds_value' => 0.125,
                    'odds_desc' => '1/8',
                ],
                [
                    'odds_value' => 0.143,
                    'odds_desc' => '1/7',
                ],
                [
                    'odds_value' => 0.154,
                    'odds_desc' => '2/13',
                ],
                [
                    'odds_value' => 0.167,
                    'odds_desc' => '1/6',
                ],
                [
                    'odds_value' => 0.182,
                    'odds_desc' => '2/11',
                ],
                [
                    'odds_value' => 0.2,
                    'odds_desc' => '1/5',
                ],
                [
                    'odds_value' => 0.222,
                    'odds_desc' => '2/9',
                ],
                [
                    'odds_value' => 0.25,
                    'odds_desc' => '1/4',
                ],
                [
                    'odds_value' => 0.286,
                    'odds_desc' => '2/7',
                ],
                [
                    'odds_value' => 0.3,
                    'odds_desc' => '30/100',
                ],
                [
                    'odds_value' => 0.333,
                    'odds_desc' => '1/3',
                ],
                [
                    'odds_value' => 0.364,
                    'odds_desc' => '4/11',
                ],
                [
                    'odds_value' => 0.4,
                    'odds_desc' => '2/5',
                ],
                [
                    'odds_value' => 0.444,
                    'odds_desc' => '4/9',
                ],
                [
                    'odds_value' => 0.471,
                    'odds_desc' => '40/85',
                ],
                [
                    'odds_value' => 0.5,
                    'odds_desc' => '1/2',
                ],
                [
                    'odds_value' => 0.533,
                    'odds_desc' => '8/15',
                ],
                [
                    'odds_value' => 0.571,
                    'odds_desc' => '4/7',
                ],
                [
                    'odds_value' => 0.615,
                    'odds_desc' => '8/13',
                ],
                [
                    'odds_value' => 0.667,
                    'odds_desc' => '4/6',
                ],
                [
                    'odds_value' => 0.727,
                    'odds_desc' => '8/11',
                ],
                [
                    'odds_value' => 0.8,
                    'odds_desc' => '4/5',
                ],
                [
                    'odds_value' => 0.833,
                    'odds_desc' => '5/6',
                ],
                [
                    'odds_value' => 0.909,
                    'odds_desc' => '10/11',
                ],
                [
                    'odds_value' => 1.0,
                    'odds_desc' => 'Evs',
                ],
                [
                    'odds_value' => 1.05,
                    'odds_desc' => '21/20',
                ],
                [
                    'odds_value' => 1.1,
                    'odds_desc' => '11/10',
                ],
                [
                    'odds_value' => 1.2,
                    'odds_desc' => '6/5',
                ],
                [
                    'odds_value' => 1.25,
                    'odds_desc' => '5/4',
                ],
                [
                    'odds_value' => 1.375,
                    'odds_desc' => '11/8',
                ],
                [
                    'odds_value' => 1.5,
                    'odds_desc' => '6/4',
                ],
                [
                    'odds_value' => 1.625,
                    'odds_desc' => '13/8',
                ],
                [
                    'odds_value' => 1.75,
                    'odds_desc' => '7/4',
                ],
                [
                    'odds_value' => 1.875,
                    'odds_desc' => '15/8',
                ],
                [
                    'odds_value' => 2.0,
                    'odds_desc' => '2/1',
                ],
                [
                    'odds_value' => 2.125,
                    'odds_desc' => '85/40',
                ],
                [
                    'odds_value' => 2.25,
                    'odds_desc' => '9/4',
                ],
                [
                    'odds_value' => 2.375,
                    'odds_desc' => '95/40',
                ],
                [
                    'odds_value' => 2.5,
                    'odds_desc' => '5/2',
                ],
                [
                    'odds_value' => 2.75,
                    'odds_desc' => '11/4',
                ],
                [
                    'odds_value' => 3.0,
                    'odds_desc' => '3/1',
                ],
                [
                    'odds_value' => 3.333,
                    'odds_desc' => '100/30',
                ],
                [
                    'odds_value' => 3.5,
                    'odds_desc' => '7/2',
                ],
                [
                    'odds_value' => 4.0,
                    'odds_desc' => '4/1',
                ],
                [
                    'odds_value' => 4.5,
                    'odds_desc' => '9/2',
                ],
                [
                    'odds_value' => 5.0,
                    'odds_desc' => '5/1',
                ],
                [
                    'odds_value' => 5.5,
                    'odds_desc' => '11/2',
                ],
                [
                    'odds_value' => 6.0,
                    'odds_desc' => '6/1',
                ],
                [
                    'odds_value' => 6.5,
                    'odds_desc' => '13/2',
                ],
                [
                    'odds_value' => 7.0,
                    'odds_desc' => '7/1',
                ],
                [
                    'odds_value' => 7.5,
                    'odds_desc' => '15/2',
                ],
                [
                    'odds_value' => 8.0,
                    'odds_desc' => '8/1',
                ],
                [
                    'odds_value' => 8.5,
                    'odds_desc' => '17/2',
                ],
                [
                    'odds_value' => 9.0,
                    'odds_desc' => '9/1',
                ],
                [
                    'odds_value' => 9.5,
                    'odds_desc' => '19/2',
                ],
                [
                    'odds_value' => 10.0,
                    'odds_desc' => '10/1',
                ],
                [
                    'odds_value' => 11.0,
                    'odds_desc' => '11/1',
                ],
                [
                    'odds_value' => 12.0,
                    'odds_desc' => '12/1',
                ],
                [
                    'odds_value' => 13.0,
                    'odds_desc' => '13/1',
                ],
                [
                    'odds_value' => 14.0,
                    'odds_desc' => '14/1',
                ],
                [
                    'odds_value' => 15.0,
                    'odds_desc' => '15/1',
                ],
                [
                    'odds_value' => 16.0,
                    'odds_desc' => '16/1',
                ],
                [
                    'odds_value' => 18.0,
                    'odds_desc' => '18/1',
                ],
                [
                    'odds_value' => 20.0,
                    'odds_desc' => '20/1',
                ],
                [
                    'odds_value' => 22.0,
                    'odds_desc' => '22/1',
                ],
                [
                    'odds_value' => 25.0,
                    'odds_desc' => '25/1',
                ],
                [
                    'odds_value' => 28.0,
                    'odds_desc' => '28/1',
                ],
                [
                    'odds_value' => 33.0,
                    'odds_desc' => '33/1',
                ],
                [
                    'odds_value' => 40.0,
                    'odds_desc' => '40/1',
                ],
                [
                    'odds_value' => 50.0,
                    'odds_desc' => '50/1',
                ],
                [
                    'odds_value' => 66.0,
                    'odds_desc' => '66/1',
                ],
                [
                    'odds_value' => 100.0,
                    'odds_desc' => '100/1',
                ],
                [
                    'odds_value' => 150.0,
                    'odds_desc' => '150/1',
                ],
                [
                    'odds_value' => 200.0,
                    'odds_desc' => '200/1',
                ],
                [
                    'odds_value' => 250.0,
                    'odds_desc' => '250/1',
                ],
                [
                    'odds_value' => 500.0,
                    'odds_desc' => '500/1',
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:754 ->createPastTrainers()
            '5e1d731d49757aae17ddba780117b5ca' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:323 ->getWinningTrainers()
            'f93c850d37116f5efe1dcd3c0b80a638' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:327 ->getWinningTrainers()
            '998b8ff5daf620a8a295a101a818475f' => [
                [
                    'trainer_uid' => 9036,
                    'trainer_name' => 'Ed Dunlop',
                    'trainer_search_name' => 'DUNLOP',
                    'wins' => 1,
                    'placed' => 1,
                    'runners' => 6,
                    'race_datetime' => '2018-05-29 13:40:00',
                    'course_style_name' => 'Lingfield (A.W)',
                    'course_name' => 'LINGFIELD (A.W)',
                    'horse_uid' => 1592896,
                    'horse_style_name' => 'Global Spirit',
                    'horse_country_origin_code' => 'GB',
                    'rp_owner_choice' => 'a',
                    'owner_uid' => 114631,
                ],
                [
                    'trainer_uid' => 9546,
                    'trainer_name' => 'Saeed bin Suroor',
                    'trainer_search_name' => 'SUROOR',
                    'wins' => 1,
                    'placed' => 0,
                    'runners' => 1,
                    'race_datetime' => '2018-05-29 13:40:00',
                    'course_style_name' => 'Lingfield (A.W)',
                    'course_name' => 'LINGFIELD (A.W)',
                    'horse_uid' => 1444072,
                    'horse_style_name' => 'Al Mustashar',
                    'horse_country_origin_code' => 'IRE',
                    'rp_owner_choice' => 'a',
                    'owner_uid' => 49845,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:778 ->createPastJockeys()
            'cb88cf2a02a8ef66559128bf03dd66eb' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:393 ->getJockeys()
            '9a23dfb20f17adfa29429cc5956a19d4' => [
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:397 ->getJockeys()
            '438f3c215ff7f8488024b86a3c1bd758' => [
                [
                    'jockey_uid' => 79202,
                    'jockey_name' => 'Ryan Moore',
                    'jockey_search_name' => 'MOORE',
                    'wins' => 1,
                    'placed' => 1,
                    'rides' => 3,
                    'race_datetime' => '2018-05-29 13:40:00',
                    'course_style_name' => 'Lingfield (A.W)',
                    'course_name' => 'LINGFIELD (A.W)',
                    'horse_uid' => 1601872,
                    'horse_style_name' => 'Beachwalk',
                    'horse_country_origin_code' => 'GB',
                    'rp_owner_choice' => 'a',
                    'owner_uid' => 16105,
                ],
                [
                    'jockey_uid' => 88632,
                    'jockey_name' => 'Harry Bentley',
                    'jockey_search_name' => 'BENTLEY',
                    'wins' => 1,
                    'placed' => 0,
                    'rides' => 1,
                    'race_datetime' => '2018-05-29 13:40:00',
                    'course_style_name' => 'Lingfield (A.W)',
                    'course_name' => 'LINGFIELD (A.W)',
                    'horse_uid' => 1444252,
                    'horse_style_name' => 'Pesky Wabbitt',
                    'horse_country_origin_code' => 'GB',
                    'rp_owner_choice' => 'a',
                    'owner_uid' => 179531,
                ],
                [
                    'jockey_uid' => 83746,
                    'jockey_name' => 'Silvestre De Sousa',
                    'jockey_search_name' => 'SOUSA',
                    'wins' => 1,
                    'placed' => 0,
                    'rides' => 1,
                    'race_datetime' => '2018-05-29 13:40:00',
                    'course_style_name' => 'Lingfield (A.W)',
                    'course_name' => 'LINGFIELD (A.W)',
                    'horse_uid' => 1413765,
                    'horse_style_name' => 'Knockout Blow',
                    'horse_country_origin_code' => 'GB',
                    'rp_owner_choice' => 'a',
                    'owner_uid' => 4643,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:481 ->getPreviousRun()
            '1ea3adb9a6bc806d28e9d85b7fdfb437' => [
                [
                    'wins' => 2,
                    'placed' => 1,
                    'lost' => 5,
                    'debuts' => 0,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:1057 ->getLastYearsWinRaces()
            'a3ae7da7e1ea6c1e96406a5123b1a563' => [
                [
                    'race_instance_uid' => 531168,
                    'race_datetime' => '2011-05-24 16:00:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 14,
                    'horse_uid' => 749733,
                    'age' => 3,
                    'rpr' => 72,
                    'weight_carried_lbs' => 128,
                    'adj_weight_carried_lbs' => 128,
                    'odds_value' => 11.0,
                    'odds_desc' => '11/1',
                    'trainer_uid' => 9003,
                    'trainer_name' => 'Marco Botti',
                    'trainer_search_name' => 'BOTTI',
                    'jockey_uid' => 83607,
                    'jockey_name' => 'Adam Kirby',
                    'jockey_search_name' => 'KIRBY',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_datetime' => '2010-05-25 16:00:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 740110,
                    'age' => 3,
                    'rpr' => 72,
                    'weight_carried_lbs' => 127,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 11.0,
                    'odds_desc' => '11/1',
                    'trainer_uid' => 144,
                    'trainer_name' => 'Alan Bailey',
                    'trainer_search_name' => 'BAILEY',
                    'jockey_uid' => 7458,
                    'jockey_name' => 'Franny Norton',
                    'jockey_search_name' => 'NORTON',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_datetime' => '2017-05-30 14:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 1214424,
                    'age' => 3,
                    'rpr' => 70,
                    'weight_carried_lbs' => 133,
                    'adj_weight_carried_lbs' => 133,
                    'odds_value' => 1.625,
                    'odds_desc' => '13/8F',
                    'trainer_uid' => 9546,
                    'trainer_name' => 'Saeed bin Suroor',
                    'trainer_search_name' => 'SUROOR',
                    'jockey_uid' => 83746,
                    'jockey_name' => 'Silvestre De Sousa',
                    'jockey_search_name' => 'SOUSA',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_datetime' => '2012-05-29 16:20:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 795409,
                    'age' => 3,
                    'rpr' => 75,
                    'weight_carried_lbs' => 133,
                    'adj_weight_carried_lbs' => 133,
                    'odds_value' => 1.375,
                    'odds_desc' => '11/8F',
                    'trainer_uid' => 10613,
                    'trainer_name' => 'Jeremy Noseda',
                    'trainer_search_name' => 'NOSEDA',
                    'jockey_uid' => 79202,
                    'jockey_name' => 'Ryan Moore',
                    'jockey_search_name' => 'MOORE',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_datetime' => '2014-05-27 15:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 13,
                    'horse_uid' => 840269,
                    'age' => 3,
                    'rpr' => 64,
                    'weight_carried_lbs' => 124,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 12.0,
                    'odds_desc' => '12/1',
                    'trainer_uid' => 99,
                    'trainer_name' => 'Chris Wall',
                    'trainer_search_name' => 'WALL',
                    'jockey_uid' => 85841,
                    'jockey_name' => 'Ashley Morgan',
                    'jockey_search_name' => 'MORGAN',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_datetime' => '2013-06-04 16:15:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 814016,
                    'age' => 3,
                    'rpr' => 70,
                    'weight_carried_lbs' => 128,
                    'adj_weight_carried_lbs' => 128,
                    'odds_value' => 12.0,
                    'odds_desc' => '12/1',
                    'trainer_uid' => 18920,
                    'trainer_name' => 'Eve Johnson Houghton',
                    'trainer_search_name' => 'HOUGHTON',
                    'jockey_uid' => 86606,
                    'jockey_name' => 'John Fahy',
                    'jockey_search_name' => 'FAHY',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_datetime' => '2016-05-31 20:50:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 9,
                    'horse_uid' => 889985,
                    'age' => 3,
                    'rpr' => 63,
                    'weight_carried_lbs' => 127,
                    'adj_weight_carried_lbs' => 127,
                    'odds_value' => 4.0,
                    'odds_desc' => '4/1',
                    'trainer_uid' => 9036,
                    'trainer_name' => 'Ed Dunlop',
                    'trainer_search_name' => 'DUNLOP',
                    'jockey_uid' => 76957,
                    'jockey_name' => 'Paul Hanagan',
                    'jockey_search_name' => 'HANAGAN',
                    'rule4_value' => 0.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_datetime' => '2015-05-26 15:40:00',
                    'race_group_code' => 'H',
                    'race_type_code' => 'X',
                    'no_of_runners' => 14,
                    'horse_uid' => 866002,
                    'age' => 3,
                    'rpr' => 69,
                    'weight_carried_lbs' => 132,
                    'adj_weight_carried_lbs' => 132,
                    'odds_value' => 14.0,
                    'odds_desc' => '14/1',
                    'trainer_uid' => 19662,
                    'trainer_name' => 'Jeremy Gask',
                    'trainer_search_name' => 'GASK',
                    'jockey_uid' => 88632,
                    'jockey_name' => 'Harry Bentley',
                    'jockey_search_name' => 'BENTLEY',
                    'rule4_value' => 0.0,
                ],
            ],
            //Api\DataProvider\Bo\RaceCards\TenYearTrends:889 ->getOddsValues()
            'e281c8805a62251c63e45bf4748ecdbe' => [
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '12',
                    'horse_uid' => 742039,
                    'odds_value' => 1.375,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '2',
                    'horse_uid' => 732523,
                    'odds_value' => 5.5,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '9',
                    'horse_uid' => 724478,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '1',
                    'horse_uid' => 740110,
                    'odds_value' => 11.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '4',
                    'horse_uid' => 737651,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '3',
                    'horse_uid' => 737463,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '10',
                    'horse_uid' => 739225,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '7',
                    'horse_uid' => 734073,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '5',
                    'horse_uid' => 739291,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '6',
                    'horse_uid' => 730511,
                    'odds_value' => 22.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '8',
                    'horse_uid' => 731008,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '11',
                    'horse_uid' => 736167,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 506277,
                    'race_outcome_code' => '13',
                    'horse_uid' => 729760,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '6',
                    'horse_uid' => 774371,
                    'odds_value' => 3.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '2',
                    'horse_uid' => 764122,
                    'odds_value' => 4.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '5',
                    'horse_uid' => 749337,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '3',
                    'horse_uid' => 782045,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '11',
                    'horse_uid' => 758583,
                    'odds_value' => 6.5,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '1',
                    'horse_uid' => 749733,
                    'odds_value' => 11.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '4',
                    'horse_uid' => 755942,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '13',
                    'horse_uid' => 761732,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '10',
                    'horse_uid' => 759340,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '14',
                    'horse_uid' => 753235,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '7',
                    'horse_uid' => 759361,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '9',
                    'horse_uid' => 758186,
                    'odds_value' => 40.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '8',
                    'horse_uid' => 754194,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 531168,
                    'race_outcome_code' => '12',
                    'horse_uid' => 760954,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '1',
                    'horse_uid' => 795409,
                    'odds_value' => 1.375,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '6',
                    'horse_uid' => 794202,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '3',
                    'horse_uid' => 797337,
                    'odds_value' => 6.5,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '4',
                    'horse_uid' => 791435,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '9',
                    'horse_uid' => 779165,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '13',
                    'horse_uid' => 789957,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '10',
                    'horse_uid' => 785089,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '8',
                    'horse_uid' => 779344,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '7',
                    'horse_uid' => 783314,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '5',
                    'horse_uid' => 783465,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '12',
                    'horse_uid' => 789233,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '2',
                    'horse_uid' => 785638,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 555004,
                    'race_outcome_code' => '11',
                    'horse_uid' => 787286,
                    'odds_value' => 80.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '5',
                    'horse_uid' => 827739,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '7',
                    'horse_uid' => 821748,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '4',
                    'horse_uid' => 812147,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '3',
                    'horse_uid' => 802215,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '2',
                    'horse_uid' => 829389,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '1',
                    'horse_uid' => 814016,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '6',
                    'horse_uid' => 805613,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '8',
                    'horse_uid' => 814926,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 579400,
                    'race_outcome_code' => '9',
                    'horse_uid' => 813908,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '3',
                    'horse_uid' => 842168,
                    'odds_value' => 2.25,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '5',
                    'horse_uid' => 842021,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '2',
                    'horse_uid' => 831606,
                    'odds_value' => 5.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '7',
                    'horse_uid' => 832502,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '1',
                    'horse_uid' => 840269,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '4',
                    'horse_uid' => 839135,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '10',
                    'horse_uid' => 828078,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '13',
                    'horse_uid' => 839574,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '8',
                    'horse_uid' => 828212,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '12',
                    'horse_uid' => 838210,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '11',
                    'horse_uid' => 838880,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '6',
                    'horse_uid' => 842777,
                    'odds_value' => 50.0,
                ],
                [
                    'race_instance_uid' => 601884,
                    'race_outcome_code' => '9',
                    'horse_uid' => 839241,
                    'odds_value' => 66.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '2',
                    'horse_uid' => 869349,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '4',
                    'horse_uid' => 871688,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '13',
                    'horse_uid' => 874868,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '3',
                    'horse_uid' => 855781,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '7',
                    'horse_uid' => 852772,
                    'odds_value' => 10.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '12',
                    'horse_uid' => 867550,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '9',
                    'horse_uid' => 880286,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '6',
                    'horse_uid' => 863686,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '1',
                    'horse_uid' => 866002,
                    'odds_value' => 14.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '8',
                    'horse_uid' => 858734,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '14',
                    'horse_uid' => 866929,
                    'odds_value' => 16.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '10',
                    'horse_uid' => 870780,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '5',
                    'horse_uid' => 859753,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 625848,
                    'race_outcome_code' => '11',
                    'horse_uid' => 861301,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '3',
                    'horse_uid' => 503615,
                    'odds_value' => 3.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '1',
                    'horse_uid' => 889985,
                    'odds_value' => 4.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '2',
                    'horse_uid' => 899105,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '5',
                    'horse_uid' => 889192,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '4',
                    'horse_uid' => 882473,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '7',
                    'horse_uid' => 895844,
                    'odds_value' => 8.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '6',
                    'horse_uid' => 885692,
                    'odds_value' => 10.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '8',
                    'horse_uid' => 885999,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 650648,
                    'race_outcome_code' => '9',
                    'horse_uid' => 900517,
                    'odds_value' => 33.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '1',
                    'horse_uid' => 1214424,
                    'odds_value' => 1.625,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '2',
                    'horse_uid' => 1158639,
                    'odds_value' => 3.5,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '7',
                    'horse_uid' => 1013248,
                    'odds_value' => 6.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '3',
                    'horse_uid' => 1007856,
                    'odds_value' => 7.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '4',
                    'horse_uid' => 1201686,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '6',
                    'horse_uid' => 1046139,
                    'odds_value' => 12.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '5',
                    'horse_uid' => 1030763,
                    'odds_value' => 20.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '9',
                    'horse_uid' => 1049199,
                    'odds_value' => 25.0,
                ],
                [
                    'race_instance_uid' => 675397,
                    'race_outcome_code' => '8',
                    'horse_uid' => 1052576,
                    'odds_value' => 66.0,
                ],
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            'b3a59c393077773e5cb07d03004d1aa6' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            'ecebf81f3997d0e5d942ff879d613e53' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '4ae726271072396a619d51fbc395cf08' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            'b8b9a12a144498320c2db81be46837a6' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '42401c9dd53f067481d533f8edd3e382' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '0deaaa39ca87e4dfbaf6164d34aecda9' => [
            ],
        ];
    }
}
