<?php

$_SERVER['AUTH_DB_ADAPTER_API_HORSES'] = "Sybase";
$_SERVER['AUTH_DB_SERVERNAME_API_HORSES'] = "TEST15";
$_SERVER['AUTH_DB_USERNAME_API_HORSES'] = "EPAMstaff1";
$_SERVER['AUTH_DB_PASSWORD_API_HORSES'] = "staff1EPAM";
$_SERVER['AUTH_DB_NAME_API_HORSES'] = "api_horses";
$_SERVER['AUTH_DB_WORKHORSE_API_HORSES'] = "work_horse";
$_SERVER['AUTH_DB_GLOBAL_HORSES_API_HORSES'] = "foreign_horses_113";
$_SERVER['CTRL_DB_PERSISTENT_API_HORSES'] = 1;
$_SERVER['AUTH_DB_METATAGS_API_HORSES'] = 'metatags_113';
$_SERVER['AUTH_DB_STORIES_API_HORSES'] = 'stories_113';
