<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\OwnerGroups\HorseList;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 * @package Tests\Controllers\Horses\OwnerGroups\HorseList
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/owner-groups/11/horse-list';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\OwnerGroups\HorseList:97 ->getData()
            'd2fec6ec9aa2c7cf66a667e4144dd514' => [
                [
                    'horse_uid' => 1456802,
                    'horse_name' => 'Addeybb',
                    'age' => 4,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 2001872,
                    'horse_name' => 'Ajddarr',
                    'age' => 3,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 31779,
                    'trainer_name' => 'Owen Burrows',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1685854,
                    'horse_name' => 'Allieyf',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1191239,
                    'horse_name' => 'Ashwass',
                    'age' => 4,
                    'horse_country_origin_code' => 'USA',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1371665,
                    'horse_name' => 'Bahlwan',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 900506,
                    'horse_name' => 'Ennaadd',
                    'age' => 5,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1860162,
                    'horse_name' => 'Eyelool',
                    'age' => 2,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1570473,
                    'horse_name' => 'Faadhel',
                    'age' => 3,
                    'horse_country_origin_code' => 'GER',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 964585,
                    'horse_name' => 'Horroob',
                    'age' => 4,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1999842,
                    'horse_name' => 'Kaanoon',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1909716,
                    'horse_name' => 'Katleen',
                    'age' => 3,
                    'horse_country_origin_code' => 'USA',
                    'trainer_uid' => 31779,
                    'trainer_name' => 'Owen Burrows',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748786,
                    'horse_name' => 'Mackaar',
                    'age' => 2,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748922,
                    'horse_name' => 'Mannguy',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 30020,
                    'trainer_name' => 'Simon Crisford',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1671428,
                    'horse_name' => 'Masaarr',
                    'age' => 3,
                    'horse_country_origin_code' => 'USA',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1860173,
                    'horse_name' => 'Mawakib',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748965,
                    'horse_name' => 'Mofaaji',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 30020,
                    'trainer_name' => 'Simon Crisford',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1371649,
                    'horse_name' => 'Monadee',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1702739,
                    'horse_name' => 'Monteja',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1990245,
                    'horse_name' => 'Montshi',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 31779,
                    'trainer_name' => 'Owen Burrows',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748852,
                    'horse_name' => 'Montzar',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1371888,
                    'horse_name' => 'Mosalim',
                    'age' => 3,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748990,
                    'horse_name' => 'Nabbeyl',
                    'age' => 2,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1036296,
                    'horse_name' => 'Novoman',
                    'age' => 4,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1891510,
                    'horse_name' => 'Raaqyah',
                    'age' => 3,
                    'horse_country_origin_code' => 'USA',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1554591,
                    'horse_name' => 'Red Mist',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 30020,
                    'trainer_name' => 'Simon Crisford',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1609732,
                    'horse_name' => 'Romaana',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 30020,
                    'trainer_name' => 'Simon Crisford',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1740909,
                    'horse_name' => 'Sajanjl',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 30020,
                    'trainer_name' => 'Simon Crisford',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 2001150,
                    'horse_name' => 'Sharamm',
                    'age' => 3,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1860178,
                    'horse_name' => 'Spotton',
                    'age' => 2,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1935971,
                    'horse_name' => 'Ta Allak',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1904526,
                    'horse_name' => 'Tamaara',
                    'age' => 3,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748945,
                    'horse_name' => 'Tammooz',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1150141,
                    'horse_name' => 'To Dibba',
                    'age' => 4,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1371590,
                    'horse_name' => 'To Wafij',
                    'age' => 3,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 998322,
                    'horse_name' => 'Tobrave',
                    'age' => 4,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1748823,
                    'horse_name' => 'Two Bids',
                    'age' => 2,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1122732,
                    'horse_name' => 'Wadigor',
                    'age' => 5,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1692216,
                    'horse_name' => 'Wohileh',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 31779,
                    'trainer_name' => 'Owen Burrows',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 964707,
                    'horse_name' => 'Yabrave',
                    'age' => 4,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1697366,
                    'horse_name' => 'Yajooll',
                    'age' => 3,
                    'horse_country_origin_code' => 'GB',
                    'trainer_uid' => 3415,
                    'trainer_name' => 'William Haggas',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
                [
                    'horse_uid' => 1139475,
                    'horse_name' => 'Yalawin',
                    'age' => 4,
                    'horse_country_origin_code' => 'IRE',
                    'trainer_uid' => 24890,
                    'trainer_name' => 'Roger Varian',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 14781,
                    'owner_name' => 'Sheikh Ahmed Al Maktoum',
                    'black_type' => 'N',
                ],
            ],
            //Api\DataProvider\Bo\OwnerGroups\OwnerGroupsProvider:94 ->getBlackTypeRunners()
            '77f7d6b690f979f0e3506601a71ce14e' => [
                [
                    'horse_uid' => 1371590,
                    'position' => 3,
                    'race_group_uid' => 3,
                    'no_of_runners' => 13,
                ],
                [
                    'horse_uid' => 1456802,
                    'position' => 1,
                    'race_group_uid' => 2,
                    'no_of_runners' => 8,
                ],
                [
                    'horse_uid' => 1554591,
                    'position' => 4,
                    'race_group_uid' => 2,
                    'no_of_runners' => 8,
                ],
            ]
        ];
    }
}
