<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Tipping\Multiples;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/** This test covers the implementation for the logic described in the following stories:
 * https://racingpost.atlassian.net/browse/AD-1600
 * https://racingpost.atlassian.net/browse/AD-1603
 *
 * Class Test
 *
 * @package Tests\Controllers\Horses\Tipping\Multiples
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/tipping/multiples/2019-04-02';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\Tipping:98 ->getMultiplesTipping()
            '4718045e0a1ff2af37b208ce037d0d40' => [
                [
                    'race_instance_uid' => 722021,
                    'race_datetime' => '2019-03-07T14:40:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Quite By Chance',
                    'horse_uid' => 828324,
                    'saddle_cloth_no' => 1,
                    'owner_uid' => 208953,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Angus Cheleda',
                    'trainer_name' => 'Colin Tizzard',
                    'verdict' => 'There are only a couple who have got to within anywhere near a stone of his lifetime best and I\'m full of hope that he will prove different class.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Bankers',
                    'category_uid' => 1,
                    'max_tips' => 5,
                    'min_tips' => 3
                ],
                [
                    'race_instance_uid' => 722023,
                    'race_datetime' => '2019-03-07T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Bankers',
                    'category_uid' => 1,
                    'max_tips' => 5,
                    'min_tips' => 3
                ],
                [
                    'race_instance_uid' => 770466,
                    'race_datetime' => '2019-03-07T17:30:00+00:00',
                    'course_name' => 'Wetherby',
                    'diffusion_course_name' => 'WETHERBY',
                    'horse_name' => 'Exelerator Express',
                    'horse_uid' => 2479615,
                    'saddle_cloth_no' => 2,
                    'owner_uid' => 272782,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Sam Twiston-Davies',
                    'trainer_name' => 'Neil Mulholland',
                    'verdict' => 'The race should be there for the taking for Exelerator Express, who dotted up in a novice hurdle at Doncaster in February, beating several subsequent winners that include the 130-rated Goobinator.',
                    'tipster_uid' => 371,
                    'tipster_name' => 'Tom Collins',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Bankers',
                    'category_uid' => 1,
                    'max_tips' => 5,
                    'min_tips' => 3
                ],
                [
                    'race_instance_uid' => 722021,
                    'race_datetime' => '2019-03-07T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Christmas Dudes',
                    'category_uid' => 2,
                    'max_tips' => 5,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722022,
                    'race_datetime' => '2019-03-08T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Christmas Dudes',
                    'category_uid' => 2,
                    'max_tips' => 5,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722023,
                    'race_datetime' => '2019-03-11T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722024,
                    'race_datetime' => '2019-03-12T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722025,
                    'race_datetime' => '2019-03-13T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722026,
                    'race_datetime' => '2019-03-14T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722027,
                    'race_datetime' => '2019-03-15T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722028,
                    'race_datetime' => '2019-03-16T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722029,
                    'race_datetime' => '2019-03-17T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722030,
                    'race_datetime' => '2019-03-18T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Findusatgorcombe',
                    'horse_uid' => 973245,
                    'saddle_cloth_no' => 9,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Bryony Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'He is only a low-grade chaser with a mark of just 84, but he has been one I have been watching for a while and he has been placed in a race that he can finally win.',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Paul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ],
                [
                    'race_instance_uid' => 722030,
                    'race_datetime' => '2019-03-18T16:55:00+00:00',
                    'course_name' => 'Wincanton',
                    'diffusion_course_name' => 'WINCANTON',
                    'horse_name' => 'Differenthorse',
                    'horse_uid' => 973254,
                    'saddle_cloth_no' => 12,
                    'owner_uid' => 245527,
                    'newspaper_uid' => 85,
                    'selection_desc' => null,
                    'jockey_name' => 'Jack Frost',
                    'trainer_name' => 'Jimmy Frost',
                    'verdict' => 'This tip should not make it into the final result set, because our tipping category already has one for the same race',
                    'tipster_uid' => 1,
                    'tipster_name' => 'Zaul Kealy',
                    'tipster_type' => 'RP Tipping',
                    'tip_type' => 'specialist',
                    'non_runner' => false,
                    'tip_category' => 'Simpsons Tipsters',
                    'category_uid' => 3,
                    'max_tips' => 4,
                    'min_tips' => 2
                ]
            ],
        ];
    }
}
