<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\RaceCards\Runners;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\RaceCards\Runners
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/racecards/runners/777494';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Models\Bo\RaceCards\RaceInstance:4177 ->checkRaceAbandoned()
            'fc5156ac65eb299c6ade1e52f85a0a5e' => [
                [
                    'race_status_code' => 'R',
                ],
            ],

            //Models\Bo\RaceCards\RaceInstance:83 ->getRaceInstance()
            '44acdc5c565d09601d674130c3ae9cbf' => [
                [
                    'race_id' => 777494,
                    'race_type_code' => 'C',
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_status_code' => 'R',
                    'distance_yard' => 4435,
                    'race_group_code' => 'H',
                    'course_uid' => 90,
                    'rp_abbrev_3' => 'WCN',
                    'country_code' => 'GB',
                    'course_name' => 'WINCANTON',
                    'course_style_name' => 'Wincanton',
                    'going_type_code' => 'G ',
                    'going_type_desc' => 'Good',
                    'declared_runners' => 23,
                    'no_of_runners' => 23,
                    'rp_tv_text' => 'RTV',
                ]
            ],

            //Models\Bo\RaceCards\Runners:348 ->createTmpTableMain()
            '92b572547a493fa4641ca5cf5c9834e4' => [
            ],

            //Models\Bo\RaceCards\Runners:44 ->getRunners()
            '71cbc348099584b9d04f196109755aab' => [
                [
                    'saddle_cloth_no' => 5,
                    'draw' => 0,
                    'race_type_code' => 'C',
                    'race_status_code' => 'O',
                    'distance_yard' => 4435,
                    'track_code' => null,
                    'course_uid' => 90,
                    'course_country_code' => 'GB ',
                    'straight_round_jubilee_code' => null,
                    'owner_uid' => 44091,
                    'breeder_uid' => 1048181,
                    'style_name' => 'Damien Coveliers',
                    'owner_name' => 'Mrs Julien Turner',
                    'eliminator_no' => 0,
                    'horse_uid' => 863603,
                    'horse_name' => 'Apple\'s Queen',
                    'country_origin_code' => 'FR',
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'rp_horse_head_gear_code' => null,
                    'horse_head_gear_desc' => null,
                    'first_time_yn' => null,
                    'extra_weight_lbs' => 0,
                    'horse_age' => 11,
                    'weight_carried_lbs' => 158,
                    'official_rating' => 89,
                    'official_rating_today' => null,
                    'jockey_uid' => 81266,
                    'jockey_name' => 'Daryl Jacob',
                    'aka_style_name' => 'D Jacob',
                    'weight_allowance_lbs' => 0,
                    'trainer_uid' => 27232,
                    'trainer_style_name' => 'Robert Walford',
                    'short_trainer_name' => 'R Walford',
                    'trainer_search_name' => 'R Walford',
                    'trainer_ptp_type_code' => 'N',
                    'trainer_country_code' => 'GB',
                    'rp_postmark' => 0,
                    'num_topspeed_best_rating' => 0,
                    'rp_topspeed' => 0,
                    'rp_owner_choice' => 'a',
                    'non_runner' => null,
                    'irish_reserve_yn' => 'N',
                    'allowance' => null,
                    'extra_weight' => null,
                    'horse_colour_code' => 'GR',
                    'horse_sex_code' => 'G',
                    'sire_id' => 522866,
                    'sire_name' => 'Saddler Maker',
                    'sire_country' => 'IRE',
                    'first_season_sire_id' => null,
                    'dam_id' => 467127,
                    'dam_name' => 'Queenhood',
                    'dam_country' => 'FR',
                    'damsire_id' => 55444,
                    'damsire_name' => 'Linamix',
                    'damsire_country' => 'FR',
                    'longSpotlight' => 'Winner of seven points but 0-9 over regulation fences; won a point for Sally Alner at Larkhill in December but pulled up on rules return for this trainer at Exeter (3m, heavy) in January; comes with risks attached.                     ',
                    'diomed' => 'Multiple point winner but 0-9 over regulation fences and pulled up on recent stable debut',
                    'current_official_rating' => 89,
                    'figures' => null,
                    'figures_calculated' => null,
                    'lh_weight_carried_lbs' => null,
                    'out_of_handicap' => null,
                    'beaten_favourite' => 'N',
                    'forecast_odds_value' => 12.0,
                    'forecast_odds_desc' => '12/1',
                    'course_and_distance_wins' => 0,
                    'course_wins' => 0,
                    'distance_wins' => 0,
                    'running_conditions' => null,
                    'date_gelded' => null,
                    'gelding_first_time' => 0,
                    'rp_postmark_improver' => 'N',
                    'owner_group_uid' => null,
                    'race_group_uid' => 6,
                    'early_closing_race_yn' => null,
                    'trainer_stylename' => 'Robert Walford',
                    'official_rating_horse' => null,
                    'handicap_first_time' => 'N',
                    'is_jockey_first_time' => 'Y',
                    'race_group_code' => 'H',
                    'horse_date_of_birth' => '2010-03-28 00:00:00',
                    'star_rating' => 2,
                    'jockey_last_14_days' => null,
                    'new_trainer_races_count' => null,
                    'ten_to_follow_horse' => null,
                    'reasoning' => null,
                    'plus10_horse' => 'N',
                    'yearling_bonus_horse' => 'N',
                    'is_wind_surgery_first_time' => null,
                    'is_wind_surgery_second_time' => null,
                    'selection_cnt' => null,
                    'trainer_rtf' => null,
                    'unadjusted_rp_postmark' => 68,
                ],
                [
                    'saddle_cloth_no' => 11,
                    'draw' => 0,
                    'race_type_code' => 'C',
                    'race_status_code' => 'O',
                    'distance_yard' => 4435,
                    'track_code' => null,
                    'course_uid' => 90,
                    'course_country_code' => 'GB ',
                    'straight_round_jubilee_code' => null,
                    'owner_uid' => 275789,
                    'breeder_uid' => 2345,
                    'style_name' => 'Martin J Dibbs',
                    'owner_name' => 'Nigel Mackenzie',
                    'eliminator_no' => 0,
                    'horse_uid' => 829759,
                    'horse_name' => 'Lawsons Thorns',
                    'country_origin_code' => 'IRE',
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'rp_horse_head_gear_code' => 'h',
                    'horse_head_gear_desc' => 'hood',
                    'first_time_yn' => 'N',
                    'extra_weight_lbs' => 0,
                    'horse_age' => 12,
                    'weight_carried_lbs' => 144,
                    'official_rating' => 75,
                    'official_rating_today' => null,
                    'jockey_uid' => 91230,
                    'jockey_name' => 'James Best',
                    'aka_style_name' => 'J Best',
                    'weight_allowance_lbs' => 0,
                    'trainer_uid' => 6636,
                    'trainer_style_name' => 'Linda Blackford',
                    'short_trainer_name' => 'L Blackford',
                    'trainer_search_name' => 'L Blackford',
                    'trainer_ptp_type_code' => 'N',
                    'trainer_country_code' => 'GB',
                    'rp_postmark' => 0,
                    'num_topspeed_best_rating' => 0,
                    'rp_topspeed' => 0,
                    'rp_owner_choice' => 'a',
                    'non_runner' => null,
                    'irish_reserve_yn' => 'N',
                    'allowance' => null,
                    'extra_weight' => null,
                    'horse_colour_code' => 'B',
                    'horse_sex_code' => 'G',
                    'sire_id' => 96595,
                    'sire_name' => 'Presenting',
                    'sire_country' => 'GB',
                    'first_season_sire_id' => null,
                    'dam_id' => 635369,
                    'dam_name' => 'Ardnurcher',
                    'dam_country' => 'IRE',
                    'damsire_id' => 305187,
                    'damsire_name' => 'King\'s Ride',
                    'damsire_country' => 'IRE',
                    'longSpotlight' => 'Won three points in the summer of 2019 but was pulled up in that sphere the last twice; has a lot to prove back over regulation fences.             ',
                    'diomed' => 'Lost his way in points the last twice; difficult to fancy back over regulation fences',
                    'current_official_rating' => 75,
                    'figures' => null,
                    'figures_calculated' => null,
                    'lh_weight_carried_lbs' => null,
                    'out_of_handicap' => null,
                    'beaten_favourite' => 'N',
                    'forecast_odds_value' => 33.0,
                    'forecast_odds_desc' => '33/1',
                    'course_and_distance_wins' => 0,
                    'course_wins' => 0,
                    'distance_wins' => 0,
                    'running_conditions' => null,
                    'date_gelded' => '2010-09-17 00:00:00',
                    'gelding_first_time' => 0,
                    'rp_postmark_improver' => 'N',
                    'owner_group_uid' => null,
                    'race_group_uid' => 6,
                    'early_closing_race_yn' => null,
                    'trainer_stylename' => 'Linda Blackford',
                    'official_rating_horse' => null,
                    'handicap_first_time' => 'N',
                    'is_jockey_first_time' => 'Y',
                    'race_group_code' => 'H',
                    'horse_date_of_birth' => '2009-04-09 00:00:00',
                    'star_rating' => 1,
                    'jockey_last_14_days' => null,
                    'new_trainer_races_count' => 1,
                    'ten_to_follow_horse' => null,
                    'reasoning' => null,
                    'plus10_horse' => 'N',
                    'yearling_bonus_horse' => 'N',
                    'is_wind_surgery_first_time' => null,
                    'is_wind_surgery_second_time' => null,
                    'selection_cnt' => null,
                    'trainer_rtf' => null,
                    'unadjusted_rp_postmark' => null,
                ]
            ],

            //Models\Bo\RaceCards\Runners:508 ->createTmpTableHorseRaces()
            '22297cbc555068e433c7d569f676651c' => [
            ],

            //Models\Bo\RaceCards\Runners:547 ->createTmpTableLastSurgery()
            'af64981bb085e581470168b9913a08b4' => [
            ],

            //Models\Bo\RaceCards\Runners:583 ->countRacesAfterSurgery()
            'ea07916079682d71a5734a314ac8c54f' => [
                [
                    'race_count' => 1,
                    'horse_uid' => 1266767,
                    'information_receipt_date' => '2017-04-19 15:35:00'
                ]
            ],

            //Models\Bo\RaceCards\Runners:630 ->dropTmpTable()
            'f268da9b3574e32b5a7f04bb65cb9fb7' => [
            ],

            //Models\Bo\RaceCards\Runners:639 ->getWfaPerAges()
            '7595e5588b19bc8e245585d1fbec7935' => [
                0 => [
                    'weight_allowance_lbs' => 13,
                    'age' => 3,
                    'distance_furlongs' => 5,
                    'race_type_code' => 'F',
                ],
                1 => [
                    'weight_allowance_lbs' => 14,
                    'age' => 3,
                    'distance_furlongs' => 6,
                    'race_type_code' => 'F',
                ],
                2 => [
                    'weight_allowance_lbs' => 16,
                    'age' => 3,
                    'distance_furlongs' => 7,
                    'race_type_code' => 'F',
                ],
                3 => [
                    'weight_allowance_lbs' => 18,
                    'age' => 3,
                    'distance_furlongs' => 8,
                    'race_type_code' => 'F',
                ],
                4 => [
                    'weight_allowance_lbs' => 20,
                    'age' => 3,
                    'distance_furlongs' => 9,
                    'race_type_code' => 'F',
                ],
                5 => [
                    'weight_allowance_lbs' => 21,
                    'age' => 3,
                    'distance_furlongs' => 10,
                    'race_type_code' => 'F',
                ],
                6 => [
                    'weight_allowance_lbs' => 22,
                    'age' => 3,
                    'distance_furlongs' => 11,
                    'race_type_code' => 'F',
                ],
                7 => [
                    'weight_allowance_lbs' => 23,
                    'age' => 3,
                    'distance_furlongs' => 12,
                    'race_type_code' => 'F',
                ],
                8 => [
                    'weight_allowance_lbs' => 1,
                    'age' => 4,
                    'distance_furlongs' => 12,
                    'race_type_code' => 'F',
                ],
                9 => [
                    'weight_allowance_lbs' => 24,
                    'age' => 3,
                    'distance_furlongs' => 13,
                    'race_type_code' => 'F',
                ],
                10 => [
                    'weight_allowance_lbs' => 1,
                    'age' => 4,
                    'distance_furlongs' => 13,
                    'race_type_code' => 'F',
                ],
                11 => [
                    'weight_allowance_lbs' => 25,
                    'age' => 3,
                    'distance_furlongs' => 14,
                    'race_type_code' => 'F',
                ],
                12 => [
                    'weight_allowance_lbs' => 2,
                    'age' => 4,
                    'distance_furlongs' => 14,
                    'race_type_code' => 'F',
                ],
                13 => [
                    'weight_allowance_lbs' => 26,
                    'age' => 3,
                    'distance_furlongs' => 15,
                    'race_type_code' => 'F',
                ],
                14 => [
                    'weight_allowance_lbs' => 2,
                    'age' => 4,
                    'distance_furlongs' => 15,
                    'race_type_code' => 'F',
                ],
                15 => [
                    'weight_allowance_lbs' => 27,
                    'age' => 3,
                    'distance_furlongs' => 16,
                    'race_type_code' => 'F',
                ],
                16 => [
                    'weight_allowance_lbs' => 3,
                    'age' => 4,
                    'distance_furlongs' => 16,
                    'race_type_code' => 'F',
                ],
                17 => [
                    'weight_allowance_lbs' => 29,
                    'age' => 3,
                    'distance_furlongs' => 18,
                    'race_type_code' => 'F',
                ],
                18 => [
                    'weight_allowance_lbs' => 3,
                    'age' => 4,
                    'distance_furlongs' => 18,
                    'race_type_code' => 'F',
                ],
                19 => [
                    'weight_allowance_lbs' => 31,
                    'age' => 3,
                    'distance_furlongs' => 20,
                    'race_type_code' => 'F',
                ],
                20 => [
                    'weight_allowance_lbs' => 4,
                    'age' => 4,
                    'distance_furlongs' => 20,
                    'race_type_code' => 'F',
                ],
                21 => [
                    'weight_allowance_lbs' => 1,
                    'age' => 5,
                    'distance_furlongs' => 20,
                    'race_type_code' => 'C',
                ],
                22 => [
                    'weight_allowance_lbs' => 2,
                    'age' => 5,
                    'distance_furlongs' => 24,
                    'race_type_code' => 'C',
                ],
                23 => [
                    'weight_allowance_lbs' => 8,
                    'age' => 4,
                    'distance_furlongs' => 16,
                    'race_type_code' => 'H',
                ],
                24 => [
                    'weight_allowance_lbs' => 9,
                    'age' => 4,
                    'distance_furlongs' => 20,
                    'race_type_code' => 'H',
                ],
                25 => [
                    'weight_allowance_lbs' => 10,
                    'age' => 4,
                    'distance_furlongs' => 24,
                    'race_type_code' => 'H',
                ],
            ],

            //Models\Bo\RaceCards\Runners:696 ->getHorseYearlingAndPlus10()
            'fe2daf88c8349ce150da7dcc6aae1592' => [
                863603 => [
                    'horse_uid' => 863603,
                    'yearling_bonus_horse' => 0,
                    'plus10_horse' => 0,
                ],
            ],

            //Models\Bo\RaceCards\Runners:574 ->getJockeyStatistics()
            '3416af169c87ea4c4dada6fb5fffaf9a' => [
                [
                    'jockey_uid' => 81266,
                    'jockey_runs' => 22,
                    'jockey_wins' => 2,
                ],
                [
                    'jockey_uid' => 91230,
                    'jockey_runs' => 28,
                    'jockey_wins' => 1,
                ]
            ],

            //Models\Bo\RaceCards\Runners:736 ->getGoingWinner()
            '98e9b9de2ce7a13edab3e5501d4beb06' => [
                [
                    'horse_uid' => 863603,
                    'winner_count' => 4
                ]

            ],
            //Models\Bo\RaceCards\Runners:630 ->dropTmpTable()
            '9ee438da8697301551276b894669ab4c' => [
            ],
            //Models\Bo\RaceCards\Runners:630 ->dropTmpTable()
            'cd641fb1ce0c4e46718f19304c6edcfb' => [
            ],

            //Models\Bo\RaceCards\Runners:772 ->getBeatenFavourites()
            'e89992a98788ad09917557e3ad56ef95' => [
            ],
            //Models\Bo\RaceCards\Runners:772 ->getBeatenFavourites()
            'dadae20091e7d340f176834a531cd622' => [
            ],

            //Models\Bo\RaceCards\Runners:713 ->getHorseForms()
            '4b12774df99bb820f13ed2cf94121b44' => [
                [
                    'horse_uid' => 1266767,
                    'distance_yard' => 1320,
                    'straight_round_jubilee_code' => 'Y',
                    'track_code' => null,
                    'course_uid' => 174,
                    'race_type_code' => 'F',
                    'country_code' => 'GB ',
                ],
                [
                    'horse_uid' => 1266767,
                    'distance_yard' => 1540,
                    'straight_round_jubilee_code' => null,
                    'track_code' => null,
                    'course_uid' => 219,
                    'race_type_code' => 'F',
                    'country_code' => 'FR ',
                ],
                [
                    'horse_uid' => 1495055,
                    'distance_yard' => 1760,
                    'straight_round_jubilee_code' => 'W',
                    'track_code' => null,
                    'course_uid' => 38,
                    'race_type_code' => 'F',
                    'country_code' => 'GB ',
                ]
            ],
            //Models\Bo\RaceCards\Runners:713 ->getHorseFormsPerRaces()
            '7ee1e70675951f7025165aca15de7b5e' => [
            ],

            //Models\Bo\RaceCards\Horse:600 ->getLongHandicapPerRaces()
            'b8b68a733cfec10853fae56eb3fe70aa' => [
            ],

            //Models\Bo\RaceCards\Runners:600 ->getGeldingFirstTimeRunners()
            '9e952ba40cf3cb1a11546330e58aaee2' => [
            ],

            //Models\Bo\RaceCards\Runners:1427 ->getPreviousTrainers()
            '6ee4b804baec2632e3c452c623543af8' => [
                829759 => [
                    'horse_uid' => 829759,
                    'trainer_uid' => 20591,
                    'trainer_change_date' => '2021-01-13 00:00:00',
                    'trainer_search_name' => 'M Vanstone',
                    'trainer_ptp_type_code' => 'G',
                ],
                863603 => [
                    'horse_uid' => 863603,
                    'trainer_uid' => 16970,
                    'trainer_change_date' => '2021-01-13 00:00:00',
                    'trainer_search_name' => 'Mrs S Alner',
                    'trainer_ptp_type_code' => 'G',
                ]
            ],

            //Models\Bo\TrainerProfile\HorseRace:20 ->getRunningToForm()
            '38ae1268f6ad6c3d8a792949a87ede04' => [
                0 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 3073274,
                    'race_instance_uid' => 776640,
                    'race_datetime' => '2021-02-20 13:05:00',
                    'race_outcome_position' => 14,
                    'race_outcome_form_char' => '0',
                    'rp_postmark' => 74,
                    'rp_pre_postmark' => 104,
                    'race_distance' => 3365,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 0,
                    'runners' => 14,
                ],
                1 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 2903592,
                    'race_instance_uid' => 776635,
                    'race_datetime' => '2021-02-20 14:13:00',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                    'rp_postmark' => 139,
                    'rp_pre_postmark' => 139,
                    'race_distance' => 4435,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 7,
                ],
                2 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 1741610,
                    'race_instance_uid' => 776749,
                    'race_datetime' => '2021-02-28 15:40:00',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                    'rp_postmark' => 124,
                    'rp_pre_postmark' => 124,
                    'race_distance' => 4229,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 0,
                    'runners' => 12,
                ],
                3 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 2536717,
                    'race_instance_uid' => 777466,
                    'race_datetime' => '2021-03-01 15:15:00',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                    'rp_postmark' => 94,
                    'rp_pre_postmark' => 93,
                    'race_distance' => 5497,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 13,
                ],
                4 => [
                    'trainer_uid' => 6636,
                    'horse_uid' => 829759,
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                    'rp_postmark' => 0,
                    'rp_pre_postmark' => 0,
                    'race_distance' => 4435,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 11,
                ],
                5 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 863603,
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_outcome_position' => 9,
                    'race_outcome_form_char' => '0',
                    'rp_postmark' => 68,
                    'rp_pre_postmark' => 0,
                    'race_distance' => 4435,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 11,
                ],
                6 => [
                    'trainer_uid' => 6636,
                    'horse_uid' => 2418436,
                    'race_instance_uid' => 777495,
                    'race_datetime' => '2021-03-03 14:40:00',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                    'rp_postmark' => 86,
                    'rp_pre_postmark' => 86,
                    'race_distance' => 3365,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 15,
                ],
                7 => [
                    'trainer_uid' => 27232,
                    'horse_uid' => 2677181,
                    'race_instance_uid' => 777495,
                    'race_datetime' => '2021-03-03 14:40:00',
                    'race_outcome_position' => 11,
                    'race_outcome_form_char' => '0',
                    'rp_postmark' => 80,
                    'rp_pre_postmark' => 98,
                    'race_distance' => 3365,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 15,
                ],
                8 => [
                    'trainer_uid' => 6636,
                    'horse_uid' => 2082312,
                    'race_instance_uid' => 777508,
                    'race_datetime' => '2021-03-04 15:40:00',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                    'rp_postmark' => 0,
                    'rp_pre_postmark' => 0,
                    'race_distance' => 4181,
                    'dist_to_winner' => 0,
                    'race_group_uid' => 6,
                    'runners' => 16,
                ],
            ],

            //Models\HorseRace:274 ->getHorsesForm()
            '4edd7c448d2131fb7e1f472dc757263d' => [
                0 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 774410,
                    'race_datetime' => '2021-01-19 15:45:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                1 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 774346,
                    'race_datetime' => '2020-12-12 13:55:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                2 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 770348,
                    'race_datetime' => '2020-10-24 13:10:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                3 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 752372,
                    'race_datetime' => '2020-02-23 13:10:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 5,
                    'race_outcome_form_char' => '5',
                ],
                4 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 752371,
                    'race_datetime' => '2020-02-23 12:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                5 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 749948,
                    'race_datetime' => '2020-01-18 14:10:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                6 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 749009,
                    'race_datetime' => '2020-01-05 11:05:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                ],
                7 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 746441,
                    'race_datetime' => '2019-12-01 12:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'O',
                ],
                8 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 733356,
                    'race_datetime' => '2019-06-09 14:00:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                9 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 732609,
                    'race_datetime' => '2019-06-02 16:20:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                10 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 731291,
                    'race_datetime' => '2019-05-19 14:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                11 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 726194,
                    'race_datetime' => '2019-05-03 20:20:00',
                    'race_type_code' => 'U',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                12 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 729515,
                    'race_datetime' => '2019-04-28 15:55:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                13 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 727260,
                    'race_datetime' => '2019-04-07 15:45:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                14 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 727258,
                    'race_datetime' => '2019-04-07 14:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                15 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 726036,
                    'race_datetime' => '2019-03-23 15:25:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                16 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 725651,
                    'race_datetime' => '2019-03-17 14:50:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                17 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 724959,
                    'race_datetime' => '2019-03-10 15:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 5,
                    'race_outcome_form_char' => '5',
                ],
                18 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 723910,
                    'race_datetime' => '2019-02-24 14:20:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                19 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 723908,
                    'race_datetime' => '2019-02-24 13:10:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'U',
                ],
                20 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 718072,
                    'race_datetime' => '2018-12-02 12:40:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                21 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 704400,
                    'race_datetime' => '2018-06-03 14:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                22 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 703172,
                    'race_datetime' => '2018-05-20 14:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                ],
                23 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 701854,
                    'race_datetime' => '2018-05-06 14:00:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                24 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 699066,
                    'race_datetime' => '2018-04-08 15:20:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                25 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 697841,
                    'race_datetime' => '2018-03-25 15:30:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                26 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 695461,
                    'race_datetime' => '2018-02-24 14:50:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                27 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 694014,
                    'race_datetime' => '2018-02-04 14:00:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'U',
                ],
                28 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 674004,
                    'race_datetime' => '2017-05-18 18:10:00',
                    'race_type_code' => 'U',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                29 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 675163,
                    'race_datetime' => '2017-04-30 15:20:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                30 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 673227,
                    'race_datetime' => '2017-04-09 16:55:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                31 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 673222,
                    'race_datetime' => '2017-04-09 14:00:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                32 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 672036,
                    'race_datetime' => '2017-03-25 15:50:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                33 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 671506,
                    'race_datetime' => '2017-03-19 13:35:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'U',
                ],
                34 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668456,
                    'race_datetime' => '2017-03-01 15:40:00',
                    'race_type_code' => 'U',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                35 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 670008,
                    'race_datetime' => '2017-02-26 14:55:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                36 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 669180,
                    'race_datetime' => '2017-02-12 13:50:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                37 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 667925,
                    'race_datetime' => '2017-01-22 13:50:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                38 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 667176,
                    'race_datetime' => '2017-01-08 12:40:00',
                    'race_type_code' => 'P',
                    'race_outcome_position' => 1,
                    'race_outcome_form_char' => '1',
                ],
                39 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 646628,
                    'race_datetime' => '2016-04-15 19:10:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                40 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668244,
                    'race_datetime' => '2016-01-30 12:15:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'F',
                ],
                41 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668247,
                    'race_datetime' => '2016-01-13 13:05:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 6,
                    'race_outcome_form_char' => '6',
                ],
                42 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 640789,
                    'race_datetime' => '2015-12-28 15:15:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'P',
                ],
                43 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668245,
                    'race_datetime' => '2015-12-03 15:10:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 7,
                    'race_outcome_form_char' => '0',
                ],
                44 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668246,
                    'race_datetime' => '2015-11-22 14:30:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                45 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668249,
                    'race_datetime' => '2015-10-18 14:30:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 6,
                    'race_outcome_form_char' => '6',
                ],
                46 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 633543,
                    'race_datetime' => '2015-08-16 17:35:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 7,
                    'race_outcome_form_char' => '0',
                ],
                47 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 629522,
                    'race_datetime' => '2015-07-12 16:55:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 6,
                    'race_outcome_form_char' => '6',
                ],
                48 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 628010,
                    'race_datetime' => '2015-06-19 15:55:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 7,
                    'race_outcome_form_char' => '0',
                ],
                49 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 626597,
                    'race_datetime' => '2015-06-05 16:55:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                ],
                50 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 624553,
                    'race_datetime' => '2015-05-17 16:30:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                51 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 620736,
                    'race_datetime' => '2015-04-05 15:15:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 6,
                    'race_outcome_form_char' => '6',
                ],
                52 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 614195,
                    'race_datetime' => '2014-12-04 14:05:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 10,
                    'race_outcome_form_char' => '0',
                ],
                53 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 613299,
                    'race_datetime' => '2014-11-19 14:10:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                ],
                54 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 611690,
                    'race_datetime' => '2014-10-26 15:30:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 5,
                    'race_outcome_form_char' => '5',
                ],
                55 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 610574,
                    'race_datetime' => '2014-10-06 14:00:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
                56 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 668248,
                    'race_datetime' => '2014-08-03 13:30:00',
                    'race_type_code' => 'C',
                    'race_outcome_position' => 4,
                    'race_outcome_form_char' => '4',
                ],
                57 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 616174,
                    'race_datetime' => '2014-07-13 14:30:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 6,
                    'race_outcome_form_char' => '6',
                ],
                58 => [
                    'horse_uid' => 863603,
                    'race_instance_uid' => 605442,
                    'race_datetime' => '2014-06-16 12:00:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 9,
                    'race_outcome_form_char' => '0',
                ],
                59 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 596223,
                    'race_datetime' => '2014-03-13 14:55:00',
                    'race_type_code' => 'H',
                    'race_outcome_position' => 0,
                    'race_outcome_form_char' => 'F',
                ],
                60 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 593418,
                    'race_datetime' => '2014-01-17 15:55:00',
                    'race_type_code' => 'B',
                    'race_outcome_position' => 3,
                    'race_outcome_form_char' => '3',
                ],
                61 => [
                    'horse_uid' => 829759,
                    'race_instance_uid' => 586515,
                    'race_datetime' => '2013-09-28 17:05:00',
                    'race_type_code' => 'B',
                    'race_outcome_position' => 2,
                    'race_outcome_form_char' => '2',
                ],
            ],

            //Models\Season:128 ->getLastNumberSeasons()
            '2081aae2a03647d5db2460c09ae7c122' => [
                0 => [
                    'season_start_date' => '2020-04-26 00:00:00',
                ],
                1 => [
                    'season_start_date' => '2019-04-28 00:00:00',
                ],
                2 => [
                    'season_start_date' => '2018-04-29 00:00:00',
                ],
                3 => [
                    'season_start_date' => '2017-04-30 00:00:00',
                ],
                4 => [
                    'season_start_date' => '2016-04-24 00:00:00',
                ],
            ],

            //Models\Bo\RaceCards\Runners:660 ->getDaysSinceLastRun()
            '25a0322dab2fcc43938441131663a08a' =>[
                0 => [
                    'horse_uid' => 829759,
                    'race_type_code' => 'ptp',
                    'days_since_run' => 130,
                ],
                1 => [
                    'horse_uid' => 829759,
                    'race_type_code' => 'jumps',
                    'days_since_run' => 0,
                ],
                2 => [
                    'horse_uid' => 863603,
                    'race_type_code' => 'ptp',
                    'days_since_run' => 81,
                ],
                3 => [
                    'horse_uid' => 863603,
                    'race_type_code' => 'jumps',
                    'days_since_run' => 0,
                ],
            ],

            //Models\Bo\RaceCards\RaceInstance:83 ->getRaceInstance()
            'beb59e1910d3c89b96d8423f44b0dd0c' => [
                [
                    'race_id' => 697411,
                    'race_type_code' => 'F',
                    'race_datetime' => '2018-04-19 15:35:00',
                    'race_status_code' => 'R',
                    'distance_yard' => 1760,
                    'race_group_code' => '3',
                    'course_uid' => 38,
                    'rp_abbrev_3' => 'NMK',
                    'country_code' => 'GB',
                    'course_name' => 'NEWMARKET',
                    'course_style_name' => 'Newmarket',
                    'going_type_code' => 'G ',
                    'going_type_desc' => 'Good',
                    'declared_runners' => 10,
                    'no_of_runners' => 10,
                    'rp_tv_text' => 'ITV4',
                ]
            ],
            //Models\Bo\RaceCards\RaceInstance:1469 ->getSelectionsCount()
            '42c349a123247282d72364abd475f525' => [

            ],
            //Models\Bo\RaceCards\RaceInstance:4119 ->getRaceAdditionalData()
            '685d7222c3b9c1f917055ce1fcfed2d1' => [
                [
                    'race_instance_uid' => 777494,
                    'distance_yard' => 4435,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_type_code' => 'C',
                    'race_group_code' => 'H',
                    'country_code' => 'GB ',
                    'min_weight' => 140,
                    'race_status_code' => 'R',
                    'weight_adjustment' => 168,
                    'min_age' => 6,
                    'max_age' => 12,
                    'top_age' => 8,
                    'furlong' => 20.0
                ]
            ],
            //Models\Bo\RaceCards\Runners:835 ->fetchImproverData()
            '2f236676c2da0d4de525b7d0823c6f71' => [
                0 => [
                    'horse_uid' => 829759,
                    'date_diff' => 674,
                    'race_type_code' => 'U',
                    'rp_postmark' => 0,
                ],
                1 => [
                    'horse_uid' => 829759,
                    'date_diff' => 1787,
                    'race_type_code' => 'H',
                    'rp_postmark' => 0,
                ],
                2 => [
                    'horse_uid' => 829759,
                    'date_diff' => 1896,
                    'race_type_code' => 'H',
                    'rp_postmark' => 0,
                ],
                3 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2030,
                    'race_type_code' => 'H',
                    'rp_postmark' => 24,
                ],
                4 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2065,
                    'race_type_code' => 'H',
                    'rp_postmark' => 80,
                ],
                5 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2088,
                    'race_type_code' => 'H',
                    'rp_postmark' => 73,
                ],
                6 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2102,
                    'race_type_code' => 'H',
                    'rp_postmark' => 102,
                ],
                7 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2121,
                    'race_type_code' => 'H',
                    'rp_postmark' => 104,
                ],
                8 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2163,
                    'race_type_code' => 'C',
                    'rp_postmark' => 43,
                ],
                9 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2285,
                    'race_type_code' => 'C',
                    'rp_postmark' => 56,
                ],
                10 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2300,
                    'race_type_code' => 'C',
                    'rp_postmark' => 103,
                ],
                11 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2324,
                    'race_type_code' => 'H',
                    'rp_postmark' => 92,
                ],
                12 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2344,
                    'race_type_code' => 'H',
                    'rp_postmark' => 100,
                ],
                13 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2551,
                    'race_type_code' => 'H',
                    'rp_postmark' => 0,
                ],
                14 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2606,
                    'race_type_code' => 'B',
                    'rp_postmark' => 103,
                ],
                15 => [
                    'horse_uid' => 829759,
                    'date_diff' => 2717,
                    'race_type_code' => 'B',
                    'rp_postmark' => 95,
                ],
                16 => [
                    'horse_uid' => 863603,
                    'date_diff' => 47,
                    'race_type_code' => 'C',
                    'rp_postmark' => 0,
                ],
                17 => [
                    'horse_uid' => 863603,
                    'date_diff' => 1389,
                    'race_type_code' => 'U',
                    'rp_postmark' => 0,
                ],
                18 => [
                    'horse_uid' => 863603,
                    'date_diff' => 1467,
                    'race_type_code' => 'U',
                    'rp_postmark' => 75,
                ],
                19 => [
                    'horse_uid' => 863603,
                    'date_diff' => 1863,
                    'race_type_code' => 'C',
                    'rp_postmark' => null,
                ],
                20 => [
                    'horse_uid' => 863603,
                    'date_diff' => 1880,
                    'race_type_code' => 'C',
                    'rp_postmark' => null,
                ],
                21 => [
                    'horse_uid' => 863603,
                    'date_diff' => 1921,
                    'race_type_code' => 'C',
                    'rp_postmark' => null,
                ],
                22 => [
                    'horse_uid' => 863603,
                    'date_diff' => 2456,
                    'race_type_code' => 'H',
                    'rp_postmark' => 77,
                ],
            ],

            //Models\Bo\RaceCards\Runners:890 ->getGoingPerformance()
            '6731a26fbc826a58d11648b736b624f6' => [
            ],

            //Models\Bo\RaceCards\Runners:920 ->getHorseOwnerGroups()
            '5c201395af081bb69fb1e3ce5236132c' => [],

            //Models\Bo\RaceCards\Runners:529 ->getFirstSeasonSire()
            'c03fe51dd0be932167f1eac4f41fa4c1' => [
            ],

            //provider/DataProvider/Bo/Rpr.php -> getRprStatistics()
            '336dbcc2acdcca57a832145b77069ce6' => [
                0 => [
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_type_code' => 'C',
                    'distance_yard' => 4435,
                    'horse_uid' => 863603,
                    'trainer_uid' => 27232,
                    'final_race_outcome_uid' => 9,
                    'rp_postmark' => 68,
                    'current_official_turf_rating' => null,
                    'current_official_aw_rating' => null,
                    'current_official_rating_hurdle' => null,
                    'current_official_rating_chase' => 89,
                ],
                1 => [
                    'race_instance_uid' => 777494,
                    'race_datetime' => '2021-03-03 13:00:00',
                    'race_type_code' => 'C',
                    'distance_yard' => 4435,
                    'horse_uid' => 829759,
                    'trainer_uid' => 6636,
                    'final_race_outcome_uid' => 63,
                    'rp_postmark' => 0,
                    'current_official_turf_rating' => null,
                    'current_official_aw_rating' => null,
                    'current_official_rating_hurdle' => 86,
                    'current_official_rating_chase' => 75,
                ],
                2 => [
                    'race_instance_uid' => 774410,
                    'race_datetime' => '2021-01-19 15:45:00',
                    'race_type_code' => 'C',
                    'distance_yard' => 5334,
                    'horse_uid' => 863603,
                    'trainer_uid' => 27232,
                    'final_race_outcome_uid' => 63,
                    'rp_postmark' => 0,
                    'current_official_turf_rating' => null,
                    'current_official_aw_rating' => null,
                    'current_official_rating_hurdle' => null,
                    'current_official_rating_chase' => 89,
                ],
            ],

            //models/Bo/RaceCards/RaceInstance.php:3953 -> getHorsesTopspeed()
            'ee806399ae9e0bea632ae80cf7de209a' => [
                [
                    'horse_uid' => 863603,
                    'race_type_code' => 'P',
                    'rp_topspeed' => null,
                ],
                [
                    'horse_uid' => 863603,
                    'race_type_code' => 'C',
                    'rp_topspeed' => 56,
                ],
                [
                    'horse_uid' => 829759,
                    'race_type_code' => 'C',
                    'rp_topspeed' => null,
                ]
            ]
        ];
    }
}
