<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\RaceCards\PostPicks;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * @package Tests\Controllers\Horses\RaceCards\PostPicks
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/racecards/706104/post-picks';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\RaceCards\PostPicks:94 ->getRaceInfo()
            'ec90b1d6a3e8e93cdc2aafb416f5ee99' => [
                [
                    'actual_runners' => 6,
                    'race_group_code' => 'H',
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:37 ->isRaceExists()
            '08b0b4c4ca27871d5a111f5575880c6e' => [
                [
                    'computed' => 1,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:83 ->getRace()
            '81ca1360872f4a5098825a7bc076fbd7' => [
                [
                    'race_instance_uid' => 706104,
                    'race_type_code' => 'F',
                    'race_datetime' => '2018-07-23 19:40:00',
                    'race_status_code' => 'O',
                    'course' => 'WINDSOR',
                    'course_uid' => 93,
                    'country_code' => 'GB ',
                    'distance_yard' => 2519,
                    'going' => 'Good To Firm',
                    'ages_allowed' => '3yo+',
                    'latitude' => 51.49079,
                    'longitude' => -0.637293,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:37 ->isRaceExists()
            '08b0b4c4ca27871d5a111f5575880c6e' => [
                [
                    'computed' => 1,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:169 ->getHorses()
            'c69ba4387105621f721250995741a6a0' => [
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Last Enchantment',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1526597,
                    'start_number' => 3,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 252825,
                    'owner_name' => 'Whitehall, Spiegelberg & Everett',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Nassya',
                    'country_origin_code' => 'GB',
                    'horse_id' => 1642746,
                    'start_number' => 4,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 135158,
                    'owner_name' => 'Abdullah Saeed Al Naboodah',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Point In Time',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1659623,
                    'start_number' => 7,
                    'owner_choice' => 'a',
                    'non_runner' => 'Y',
                    'owner_uid' => 254681,
                    'owner_name' => 'Gaf Racing',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Outlane',
                    'country_origin_code' => 'GB',
                    'horse_id' => 1692219,
                    'start_number' => 2,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 50162,
                    'owner_name' => 'Aston House Stud',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Vanity Vanity',
                    'country_origin_code' => 'USA',
                    'horse_id' => 1776956,
                    'start_number' => 5,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 234299,
                    'owner_name' => 'Chris Van Hoorn Racing',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Life On Earth',
                    'country_origin_code' => 'USA',
                    'horse_id' => 1975676,
                    'start_number' => 1,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 203468,
                    'owner_name' => 'Qatar Racing Limited',
                ],
                [
                    'race_instance_uid' => 706104,
                    'style_name' => 'Vampish',
                    'country_origin_code' => 'GB',
                    'horse_id' => 1996424,
                    'start_number' => 6,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 7281,
                    'owner_name' => 'C M Budgett',
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:228 ->getPostdata()
            '2fdd7e062e4cc7aead59d104df27509c' => [
                [
                    'horse_style_name' => 'Last Enchantment',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => 'a',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aaa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 3,
                    'horse_uid' => 1526597,
                    'rp_tops' => 88,
                    'rp_pm_chars' => 'X',
                    'official_rating' => 75,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 78,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 18920,
                    'top_speed' => 88,
                    'RPR' => 93,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Nassya',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => '?',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 4,
                    'horse_uid' => 1642746,
                    'rp_tops' => 75,
                    'rp_pm_chars' => null,
                    'official_rating' => 73,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 79,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 4336,
                    'top_speed' => 75,
                    'RPR' => 92,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Point In Time',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => 'a',
                    'distance_output' => 'a',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 7,
                    'horse_uid' => 1659623,
                    'rp_tops' => 81,
                    'rp_pm_chars' => null,
                    'official_rating' => 67,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 55,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 13,
                    'top_speed' => 81,
                    'RPR' => 90,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Outlane',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => 'a',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'X',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 2,
                    'horse_uid' => 1692219,
                    'rp_tops' => 45,
                    'rp_pm_chars' => 'X',
                    'official_rating' => 77,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 160,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 401,
                    'top_speed' => 45,
                    'RPR' => 93,
                    'form_points' => -0.5,
                ],
                [
                    'horse_style_name' => 'Vanity Vanity',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => '?',
                    'going_output' => 'a',
                    'distance_output' => '?',
                    'course_output' => 'a',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 5,
                    'horse_uid' => 1776956,
                    'rp_tops' => 80,
                    'rp_pm_chars' => null,
                    'official_rating' => 71,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 69,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 13478,
                    'top_speed' => 80,
                    'RPR' => 90,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Life On Earth',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'aa',
                    'going_output' => 'a',
                    'distance_output' => 'a',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 1,
                    'horse_uid' => 1975676,
                    'rp_tops' => 48,
                    'rp_pm_chars' => 'X',
                    'official_rating' => 78,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 162,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 3415,
                    'top_speed' => 48,
                    'RPR' => 93,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Vampish',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => 'a',
                    'distance_output' => 'a',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 6,
                    'horse_uid' => 1996424,
                    'rp_tops' => 73,
                    'rp_pm_chars' => null,
                    'official_rating' => 71,
                    'draw_output' => '-',
                    'race_instance_uid' => 706104,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 75,
                    'jockey_stable_wins' => 6,
                    'is_first_time' => null,
                    'race_datetime' => '2018-07-23 19:40:00',
                    'course_name' => 'WINDSOR',
                    'trainer_id' => 7968,
                    'top_speed' => 73,
                    'RPR' => 90,
                    'form_points' => 0.75,
                ],
            ],
        ];
    }
}
