<?php

namespace Tests\Stubs\Models;

class Sire extends \Models\Sire
{
    use StubDataGetter;

    protected static $_stubData = [
        'sires' => [
            522845 => [
                'sire_uid' => 522845,
                'avg_flat_win_dist_of_progeny' => 10.4,
                'avg_jump_win_dist_of_progeny' => null,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 0.89,
                'jump_avg_earnings_index' => 0.42
            ],
            107700 => [
                'sire_uid' => 107700,
                'avg_flat_win_dist_of_progeny' => 7.9,
                'avg_jump_win_dist_of_progeny' => null,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 2.28,
                'jump_avg_earnings_index' => 0.9
            ],
            304579 => [
                'sire_uid' => 304579,
                'avg_flat_win_dist_of_progeny' => 9.1,
                'avg_jump_win_dist_of_progeny' => 17.0,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.39,
                'jump_avg_earnings_index' => 0.61
            ],
            300363 => [
                'sire_uid' => 300363,
                'avg_flat_win_dist_of_progeny' => 11.3,
                'avg_jump_win_dist_of_progeny' => 19.6,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 0.92,
                'jump_avg_earnings_index' => 0.98
            ],
            301599 => [
                'sire_uid' => 301599,
                'avg_flat_win_dist_of_progeny' => 8.7,
                'avg_jump_win_dist_of_progeny' => 23.0,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.64,
                'jump_avg_earnings_index' => 2.42
            ],
            9363 => [
                'sire_uid' => 9363,
                'avg_flat_win_dist_of_progeny' => 7.8,
                'avg_jump_win_dist_of_progeny' => 17.1,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.65,
                'jump_avg_earnings_index' => 0.70
            ],
            58836 => [
                'sire_uid' => 58836,
                'avg_flat_win_dist_of_progeny' => 8.5,
                'avg_jump_win_dist_of_progeny' => 17.1,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.76,
                'jump_avg_earnings_index' => 2.15
            ],
            300363 => [
                'sire_uid' => 300363,
                'avg_flat_win_dist_of_progeny' => 11.3,
                'avg_jump_win_dist_of_progeny' => 19.6,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 0.92,
                'jump_avg_earnings_index' => 0.98
            ],
            301813 => [
                'sire_uid' => 301813,
                'avg_flat_win_dist_of_progeny' => 11.3,
                'avg_jump_win_dist_of_progeny' => 18.0,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 0.69,
                'jump_avg_earnings_index' => 0.61
            ],
            302745 => [
                'sire_uid' => 302745,
                'avg_flat_win_dist_of_progeny' => 8.0,
                'avg_jump_win_dist_of_progeny' => 16.6,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.10,
                'jump_avg_earnings_index' => 0.40
            ],
            303554 => [
                'sire_uid' => 303554,
                'avg_flat_win_dist_of_progeny' => 10.1,
                'avg_jump_win_dist_of_progeny' => 20.4,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.61,
                'jump_avg_earnings_index' => 1.56
            ],
            301723 => [
                'sire_uid' => 301723,
                'avg_flat_win_dist_of_progeny' => 8.1,
                'avg_jump_win_dist_of_progeny' => 17.4,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 2.67,
                'jump_avg_earnings_index' => 1.44
            ],
            307193 => [
                'sire_uid' => 307193,
                'avg_flat_win_dist_of_progeny' => 10.7,
                'avg_jump_win_dist_of_progeny' => 17.3,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => null,
                'jump_avg_earnings_index' => 0.17
            ],
            300359 => [
                'sire_uid' => 300359,
                'avg_flat_win_dist_of_progeny' => 11.9,
                'avg_jump_win_dist_of_progeny' => 18.3,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 1.43,
                'jump_avg_earnings_index' => 0.57
            ],
            301976 => [
                'sire_uid' => 301976,
                'avg_flat_win_dist_of_progeny' => 6.4,
                'avg_jump_win_dist_of_progeny' => 16.4,
                'first_season_yn' => 'N',
                'no_of_2yo_offspring_runs' => null,
                'no_of_2yo_offspring_wins' => null,
                'no_of_offspring_flat_runs' => null,
                'no_of_offspring_flat_wins' => null,
                'no_of_offspring_jump_runs' => null,
                'no_of_offspring_jump_wins' => null,
                'no_of_flat_offsprings' => null,
                'no_of_jump_offsprings' => null,
                'timestamp' => null,
                'avg_hurdle_win_dist_of_progeny' => null,
                'avg_chase_win_dist_of_progeny' => null,
                'flat_avg_earnings_index' => 0.92,
                'jump_avg_earnings_index' => 0.08
            ]
        ]
    ];

    /**
     * @param int $horseUid
     * @return array
     */
    public function getBySireUid($sireUid)
    {
        $row = null;

        if (isset(self::getStubData('sires')[$sireUid])) {
            $row = \Phalcon\Mvc\Model\Row\General::createFromArray(self::getStubData('sires')[$sireUid]);
        }

        return $row;
    }
}
