<?php

declare(strict_types=1);

namespace Test\Controllers\Horses\SeasonalStatistics\FirstCrop;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 * @package Tests\Controllers\Horses\SeasonalStatistics\FirstCrop
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/seasonal-statistics/first-crop?surface=turf&distance=0-1210&going=GS&progenyPerformersLimit=1';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Models\Bo\Selectors\Database:65 ->getCurrentSeasonDateBegin()
            'de39c9bec57b3afc8577754189353f85' => [
                [
                    'startDate' => '2018-01-01 00:00:00',
                ],
            ],
            //Models\Bo\Selectors\Database:132 ->getSeasonDateEndByDateBegin()
            'ce9b2bbf2da4bcf30f3829231a27aba3' => [
                [
                    'endDate' => '2018-12-31 23:59:00',
                ],
            ],
            //Models\Bo\SeasonalStatistics\FirstCrop:49 ->getTmpTableSeasonalStats()
            'a3327b7958cfacc22becd4c1aab9b968' => [],
            //Models\Bo\SeasonalStatistics:324 ->createStatsTmpIndex()
            '4725a68b1a00afa05647bed0de5b0775' => [
            ],
            //Models\Bo\Selectors\Database:290 ->getEuroRateByYear()
            '67e8960489bb110e58e67f5ed995994b' => [
                [
                    'exchange_rate' => 1.13,
                ],
            ],
            '63bbaed14412defa2bd3c6a478babc94' => [
                [
                    'exchange_rate' => 1.13,
                ],
            ],
            //Models\Bo\SeasonalStatistics\FirstCrop:114 ->getSeasonalStatistics()
            'bd491f35b5e210baa0e07ebdfb248093' => [
                [
                    'sire_uid' => 805556,
                    'sire' => 'Bungle Inthejungle',
                    'sire_country_origin_code' => 'GB',
                    'weatherbys_uid' => 3129,
                    'rate_euro' => 1.13,
                    'wins' => 4,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 8,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 15525.6,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 15525.6,
                    'net_win_prize_money' => 5902.2,
                    'net_total_prize_money' => 11804.4,
                    'runners' => 2,
                    'winners' => 1,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 821883,
                    'sire' => 'Morpheus',
                    'sire_country_origin_code' => 'GB',
                    'weatherbys_uid' => 3126,
                    'rate_euro' => 1.13,
                    'wins' => 4,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 8,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 15008.08,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 15008.08,
                    'net_win_prize_money' => 5705.46,
                    'net_total_prize_money' => 13575.06,
                    'runners' => 2,
                    'winners' => 1,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 811093,
                    'sire' => 'Olympic Glory',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3138,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 4,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 6160.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 7869.6,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 774595,
                    'sire' => 'Slade Power',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3116,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 4,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 5387.2,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 13771.8,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 815858,
                    'sire' => 'Garswood',
                    'sire_country_origin_code' => 'GB',
                    'weatherbys_uid' => 3136,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 4,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 4620.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 5902.2,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 839221,
                    'sire' => 'No Nay Never',
                    'sire_country_origin_code' => 'USA',
                    'weatherbys_uid' => 3188,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 8,
                    'runs' => 8,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 3809.52,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 19477.26,
                    'runners' => 2,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 829788,
                    'sire' => 'Kuroshio',
                    'sire_country_origin_code' => 'AUS',
                    'weatherbys_uid' => null,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 4,
                    'fourths' => 4,
                    'runs' => 8,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 3386.24,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 11607.66,
                    'runners' => 2,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 832546,
                    'sire' => 'Coach House',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3177,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 4,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 2462.72,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 6295.68,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 805266,
                    'sire' => 'Alhebayeb',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3141,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 4,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 2308.8,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 5902.2,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 789808,
                    'sire' => 'Heeraat',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3112,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 4,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 1250.6,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 6394.05,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 800198,
                    'sire' => 'Battle Of Marengo',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3143,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 9837.0,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 805559,
                    'sire' => 'Gale Force Ten',
                    'sire_country_origin_code' => 'GB',
                    'weatherbys_uid' => 3139,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 8,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 13771.8,
                    'runners' => 2,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 784865,
                    'sire' => 'Gregorian',
                    'sire_country_origin_code' => 'IRE',
                    'weatherbys_uid' => 3113,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 7869.6,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
                [
                    'sire_uid' => 831212,
                    'sire' => 'War Command',
                    'sire_country_origin_code' => 'USA',
                    'weatherbys_uid' => 3214,
                    'rate_euro' => 1.13,
                    'wins' => 0,
                    'seconds' => 0,
                    'thirds' => 0,
                    'fourths' => 0,
                    'runs' => 4,
                    'win_prize_money_euro' => 0.0,
                    'win_prize_money_pound' => 0.0,
                    'total_prize_money_euro' => 0.0,
                    'total_prize_money_pound' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 7869.6,
                    'runners' => 1,
                    'winners' => 0,
                    'stakes_wins' => 0,
                    'stakes_winner' => 0,
                    'stakes_runner' => 0,
                ],
            ],
            //Models\Bo\SeasonalStatistics\Sire:188 ->getProgenyPerformers()
            'cf8af71264003be7772a1c67e07a79c7' => [
                [
                    'sire_uid' => 59210,
                    'horse_uid' => 780979,
                    'horse_style_name' => 'Imperial Legend',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 106018,
                    'dam_sire_style_name' => 'Titus Livius',
                    'dam_sire_country_origin_code' => 'FR',
                    'rp_postmark' => 60,
                ],
                [
                    'sire_uid' => 84442,
                    'horse_uid' => 846288,
                    'horse_style_name' => 'Poyle Vinnie',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 84,
                ],
                [
                    'sire_uid' => 103416,
                    'horse_uid' => 878847,
                    'horse_style_name' => 'Dodgy Bob',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 503875,
                    'dam_sire_style_name' => 'Dansili',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 51,
                ],
                [
                    'sire_uid' => 103416,
                    'horse_uid' => 892038,
                    'horse_style_name' => 'Kingstreet Lady',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 447676,
                    'dam_sire_style_name' => 'Compton Place',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 41,
                ],
                [
                    'sire_uid' => 104011,
                    'horse_uid' => 685784,
                    'horse_style_name' => 'Silvanus',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 72069,
                    'dam_sire_style_name' => 'Brief Truce',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 21,
                ],
                [
                    'sire_uid' => 107700,
                    'horse_uid' => 846055,
                    'horse_style_name' => 'Orion\'s Bow',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 13903,
                    'dam_sire_style_name' => 'Rahy',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 93,
                ],
                [
                    'sire_uid' => 447676,
                    'horse_uid' => 728763,
                    'horse_style_name' => 'Bronze Beau',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 97591,
                    'dam_sire_style_name' => 'Singspiel',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 53,
                ],
                [
                    'sire_uid' => 448003,
                    'horse_uid' => 1427475,
                    'horse_style_name' => 'Areen Faisal',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 301842,
                    'dam_sire_style_name' => 'Petong',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 81,
                ],
                [
                    'sire_uid' => 448003,
                    'horse_uid' => 855555,
                    'horse_style_name' => 'Bahamian Sunrise',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 103932,
                    'dam_sire_style_name' => 'Tagula',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 80,
                ],
                [
                    'sire_uid' => 449518,
                    'horse_uid' => 1026954,
                    'horse_style_name' => 'Storm Over',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 303554,
                    'dam_sire_style_name' => 'Cozzene',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 80,
                ],
                [
                    'sire_uid' => 449518,
                    'horse_uid' => 876958,
                    'horse_style_name' => 'A Momentofmadness',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 103416,
                    'dam_sire_style_name' => 'Royal Applause',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 71,
                ],
                [
                    'sire_uid' => 450077,
                    'horse_uid' => 1164788,
                    'horse_style_name' => 'La Fortuna',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 503875,
                    'dam_sire_style_name' => 'Dansili',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 72,
                ],
                [
                    'sire_uid' => 488572,
                    'horse_uid' => 853826,
                    'horse_style_name' => 'Robbian',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 47214,
                    'dam_sire_style_name' => 'Zilzal',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 49,
                ],
                [
                    'sire_uid' => 506927,
                    'horse_uid' => 836839,
                    'horse_style_name' => 'Shamshon',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 511443,
                    'dam_sire_style_name' => 'Fasliyev',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 75,
                ],
                [
                    'sire_uid' => 527373,
                    'horse_uid' => 989249,
                    'horse_style_name' => 'Edward Lewis',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 303737,
                    'dam_sire_style_name' => 'Green Desert',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 94,
                ],
                [
                    'sire_uid' => 527373,
                    'horse_uid' => 1860129,
                    'horse_style_name' => 'Glory Fighter',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 82,
                ],
                [
                    'sire_uid' => 535308,
                    'horse_uid' => 1406147,
                    'horse_style_name' => 'Primo\'s Comet',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 513207,
                    'dam_sire_style_name' => 'Primo Valentino',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 68,
                ],
                [
                    'sire_uid' => 541314,
                    'horse_uid' => 964921,
                    'horse_style_name' => 'Mr Pocket',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 301663,
                    'dam_sire_style_name' => 'Night Shift',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 78,
                ],
                [
                    'sire_uid' => 541314,
                    'horse_uid' => 1431174,
                    'horse_style_name' => 'Qaaraat',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 70,
                ],
                [
                    'sire_uid' => 543708,
                    'horse_uid' => 1613688,
                    'horse_style_name' => 'Dawn Breaking',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 105212,
                    'dam_sire_style_name' => 'Mark Of Esteem',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 68,
                ],
                [
                    'sire_uid' => 546115,
                    'horse_uid' => 707399,
                    'horse_style_name' => 'Sir Geoffrey',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 448003,
                    'dam_sire_style_name' => 'Bahamian Bounty',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 25,
                ],
                [
                    'sire_uid' => 557318,
                    'horse_uid' => 828045,
                    'horse_style_name' => 'Piazon',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 81687,
                    'dam_sire_style_name' => 'Colonel Collins',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 67,
                ],
                [
                    'sire_uid' => 560048,
                    'horse_uid' => 1384748,
                    'horse_style_name' => 'Choosey',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 546115,
                    'dam_sire_style_name' => 'Captain Rio',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 69,
                ],
                [
                    'sire_uid' => 560389,
                    'horse_uid' => 895850,
                    'horse_style_name' => 'Gracious John',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 500335,
                    'dam_sire_style_name' => 'Lujain',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 105,
                ],
                [
                    'sire_uid' => 562911,
                    'horse_uid' => 758565,
                    'horse_style_name' => 'Move In Time',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 53070,
                    'dam_sire_style_name' => 'Machiavellian',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 88,
                ],
                [
                    'sire_uid' => 562911,
                    'horse_uid' => 735294,
                    'horse_style_name' => 'Hoof It',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 448032,
                    'dam_sire_style_name' => 'Danetime',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 74,
                ],
                [
                    'sire_uid' => 564704,
                    'horse_uid' => 1384759,
                    'horse_style_name' => 'Bengali Boys',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 447676,
                    'dam_sire_style_name' => 'Compton Place',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 93,
                ],
                [
                    'sire_uid' => 565797,
                    'horse_uid' => 1371580,
                    'horse_style_name' => 'Mutabaahy',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 103416,
                    'dam_sire_style_name' => 'Royal Applause',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 566073,
                    'horse_uid' => 799928,
                    'horse_style_name' => 'Pettochside',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 42373,
                    'dam_sire_style_name' => 'Danehill',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 100,
                ],
                [
                    'sire_uid' => 576872,
                    'horse_uid' => 1887396,
                    'horse_style_name' => 'Broken Spear',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 556759,
                    'dam_sire_style_name' => 'Arakan',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 77,
                ],
                [
                    'sire_uid' => 576872,
                    'horse_uid' => 852621,
                    'horse_style_name' => 'Kibaar',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 93262,
                    'dam_sire_style_name' => 'General Monash',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 50,
                ],
                [
                    'sire_uid' => 577888,
                    'horse_uid' => 862151,
                    'horse_style_name' => 'Foolaad',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 97591,
                    'dam_sire_style_name' => 'Singspiel',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 105,
                ],
                [
                    'sire_uid' => 577888,
                    'horse_uid' => 1004629,
                    'horse_style_name' => 'Evergate',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 515221,
                    'dam_sire_style_name' => 'Forestry',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 81,
                ],
                [
                    'sire_uid' => 579845,
                    'horse_uid' => 1478725,
                    'horse_style_name' => 'Bomad',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 596597,
                    'dam_sire_style_name' => 'Rock Hard Ten',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 15,
                ],
                [
                    'sire_uid' => 582877,
                    'horse_uid' => 881136,
                    'horse_style_name' => 'Aleef',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 300625,
                    'dam_sire_style_name' => 'Diesis',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 78,
                ],
                [
                    'sire_uid' => 582877,
                    'horse_uid' => 1384797,
                    'horse_style_name' => 'Seen The Lyte',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 541314,
                    'dam_sire_style_name' => 'Acclamation',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 74,
                ],
                [
                    'sire_uid' => 583738,
                    'horse_uid' => 1870917,
                    'horse_style_name' => 'Vikivaki',
                    'horse_country_origin_code' => 'USA',
                    'dam_sire_uid' => 450965,
                    'dam_sire_style_name' => 'Smart Strike',
                    'dam_sire_country_origin_code' => 'CAN',
                    'rp_postmark' => 80,
                ],
                [
                    'sire_uid' => 584449,
                    'horse_uid' => 1860034,
                    'horse_style_name' => 'Axel Jacklin',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 541314,
                    'dam_sire_style_name' => 'Acclamation',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 49,
                ],
                [
                    'sire_uid' => 589184,
                    'horse_uid' => 1567815,
                    'horse_style_name' => 'Nuns Walk',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 450464,
                    'dam_sire_style_name' => 'Cape Cross',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 66,
                ],
                [
                    'sire_uid' => 600609,
                    'horse_uid' => 1890327,
                    'horse_style_name' => 'Royal',
                    'horse_country_origin_code' => 'USA',
                    'dam_sire_uid' => 49087,
                    'dam_sire_style_name' => 'Royal Academy',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 21,
                ],
                [
                    'sire_uid' => 602298,
                    'horse_uid' => 834610,
                    'horse_style_name' => 'Green Door',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 75049,
                    'dam_sire_style_name' => 'Pips Pride',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 82,
                ],
                [
                    'sire_uid' => 602298,
                    'horse_uid' => 842732,
                    'horse_style_name' => 'Coiste Bodhar',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 55444,
                    'dam_sire_style_name' => 'Linamix',
                    'dam_sire_country_origin_code' => 'FR',
                    'rp_postmark' => 59,
                ],
                [
                    'sire_uid' => 620734,
                    'horse_uid' => 783328,
                    'horse_style_name' => 'Bop It',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 448032,
                    'dam_sire_style_name' => 'Danetime',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 53,
                ],
                [
                    'sire_uid' => 626739,
                    'horse_uid' => 1471870,
                    'horse_style_name' => 'John Kirkup',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 467224,
                    'dam_sire_style_name' => 'Trans Island',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 60,
                ],
                [
                    'sire_uid' => 634177,
                    'horse_uid' => 812395,
                    'horse_style_name' => 'Windforpower',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 540336,
                    'dam_sire_style_name' => 'Dubai Destination',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 62,
                ],
                [
                    'sire_uid' => 637069,
                    'horse_uid' => 886916,
                    'horse_style_name' => 'Orvar',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 87296,
                    'dam_sire_style_name' => 'Grand Lodge',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 102,
                ],
                [
                    'sire_uid' => 637069,
                    'horse_uid' => 1543501,
                    'horse_style_name' => 'Dandy\'s Beano',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 513047,
                    'dam_sire_style_name' => 'Giant\'s Causeway',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 78,
                ],
                [
                    'sire_uid' => 640322,
                    'horse_uid' => 801044,
                    'horse_style_name' => 'Caspian Prince',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 303440,
                    'dam_sire_style_name' => 'Rainbow Quest',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 88,
                ],
                [
                    'sire_uid' => 642105,
                    'horse_uid' => 1894515,
                    'horse_style_name' => 'Kinks',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 544976,
                    'dam_sire_style_name' => 'Rock Of Gibraltar',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 91,
                ],
                [
                    'sire_uid' => 642105,
                    'horse_uid' => 1932436,
                    'horse_style_name' => 'Azor Ahai',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 447676,
                    'dam_sire_style_name' => 'Compton Place',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 52,
                ],
                [
                    'sire_uid' => 647498,
                    'horse_uid' => 1956504,
                    'horse_style_name' => 'Getchagetchagetcha',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 85,
                ],
                [
                    'sire_uid' => 649250,
                    'horse_uid' => 1025038,
                    'horse_style_name' => 'Leo Minor',
                    'horse_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 88,
                ],
                [
                    'sire_uid' => 650324,
                    'horse_uid' => 864613,
                    'horse_style_name' => 'Oriental Splendour',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 527373,
                    'dam_sire_style_name' => 'Kyllachy',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 63,
                ],
                [
                    'sire_uid' => 654568,
                    'horse_uid' => 782390,
                    'horse_style_name' => 'Economic Crisis',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 86585,
                    'dam_sire_style_name' => 'Foxhound',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 73,
                ],
                [
                    'sire_uid' => 655133,
                    'horse_uid' => 1550181,
                    'horse_style_name' => 'Little Boy Blue',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 106018,
                    'dam_sire_style_name' => 'Titus Livius',
                    'dam_sire_country_origin_code' => 'FR',
                    'rp_postmark' => 72,
                ],
                [
                    'sire_uid' => 655133,
                    'horse_uid' => 1434690,
                    'horse_style_name' => 'Snow Excuse',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 473501,
                    'dam_sire_style_name' => 'Diktat',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 40,
                ],
                [
                    'sire_uid' => 657462,
                    'horse_uid' => 1053002,
                    'horse_style_name' => 'Erissimus Maximus',
                    'horse_country_origin_code' => 'FR',
                    'dam_sire_uid' => 450464,
                    'dam_sire_style_name' => 'Cape Cross',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 93,
                ],
                [
                    'sire_uid' => 659772,
                    'horse_uid' => 1518953,
                    'horse_style_name' => 'Forever In Love',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 107700,
                    'dam_sire_style_name' => 'Pivotal',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 71,
                ],
                [
                    'sire_uid' => 659772,
                    'horse_uid' => 1935977,
                    'horse_style_name' => 'Delft Dancer',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 104011,
                    'dam_sire_style_name' => 'Danehill Dancer',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 63,
                ],
                [
                    'sire_uid' => 660383,
                    'horse_uid' => 807293,
                    'horse_style_name' => 'Perfect Words',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 47214,
                    'dam_sire_style_name' => 'Zilzal',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 660521,
                    'horse_uid' => 1001890,
                    'horse_style_name' => 'Rose Berry',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 303737,
                    'dam_sire_style_name' => 'Green Desert',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 81,
                ],
                [
                    'sire_uid' => 662598,
                    'horse_uid' => 1909739,
                    'horse_style_name' => 'Van Beethoven',
                    'horse_country_origin_code' => 'CAN',
                    'dam_sire_uid' => 529542,
                    'dam_sire_style_name' => 'Montbrook',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 79,
                ],
                [
                    'sire_uid' => 671647,
                    'horse_uid' => 863799,
                    'horse_style_name' => 'George Bowen',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 91,
                ],
                [
                    'sire_uid' => 671647,
                    'horse_uid' => 1796200,
                    'horse_style_name' => 'Jackstar',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 659996,
                    'dam_sire_style_name' => 'Duke Of Marmalade',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 89,
                ],
                [
                    'sire_uid' => 671916,
                    'horse_uid' => 837844,
                    'horse_style_name' => 'Go Charlie',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 75899,
                    'dam_sire_style_name' => 'So Factual',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 38,
                ],
                [
                    'sire_uid' => 679491,
                    'horse_uid' => 1052584,
                    'horse_style_name' => 'Henrietta\'s Dream',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 0,
                ],
                [
                    'sire_uid' => 679933,
                    'horse_uid' => 834116,
                    'horse_style_name' => 'One Boy',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 455293,
                    'dam_sire_style_name' => 'Peintre Celebre',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 64,
                ],
                [
                    'sire_uid' => 679954,
                    'horse_uid' => 1417685,
                    'horse_style_name' => 'Brandy Station',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 513038,
                    'dam_sire_style_name' => 'Fath',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 47,
                ],
                [
                    'sire_uid' => 680007,
                    'horse_uid' => 1797699,
                    'horse_style_name' => 'Dave Dexter',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 446691,
                    'dam_sire_style_name' => 'Verglas',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 87,
                ],
                [
                    'sire_uid' => 682732,
                    'horse_uid' => 1564146,
                    'horse_style_name' => 'Lake Volta',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 602045,
                    'dam_sire_style_name' => 'Shamardal',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 98,
                ],
                [
                    'sire_uid' => 685655,
                    'horse_uid' => 1016747,
                    'horse_style_name' => 'Liberatum',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 62150,
                    'dam_sire_style_name' => 'Selkirk',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 59,
                ],
                [
                    'sire_uid' => 692355,
                    'horse_uid' => 862910,
                    'horse_style_name' => 'Son Of Africa',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 506990,
                    'dam_sire_style_name' => 'Sakhee',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 89,
                ],
                [
                    'sire_uid' => 692355,
                    'horse_uid' => 998344,
                    'horse_style_name' => 'Dakota Gold',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 105212,
                    'dam_sire_style_name' => 'Mark Of Esteem',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 87,
                ],
                [
                    'sire_uid' => 701235,
                    'horse_uid' => 1657573,
                    'horse_style_name' => 'Samovar',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 72922,
                    'dam_sire_style_name' => 'Barathea',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 79,
                ],
                [
                    'sire_uid' => 701235,
                    'horse_uid' => 1887399,
                    'horse_style_name' => 'Tizwotitiz',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 566073,
                    'dam_sire_style_name' => 'Refuse To Bend',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 70,
                ],
                [
                    'sire_uid' => 704079,
                    'horse_uid' => 1598299,
                    'horse_style_name' => 'Machree',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 446691,
                    'dam_sire_style_name' => 'Verglas',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 63,
                ],
                [
                    'sire_uid' => 706276,
                    'horse_uid' => 1488098,
                    'horse_style_name' => 'Amazing Grazing',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 572760,
                    'dam_sire_style_name' => 'North Light',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 81,
                ],
                [
                    'sire_uid' => 706276,
                    'horse_uid' => 1576307,
                    'horse_style_name' => 'Carpet Time',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 470699,
                    'dam_sire_style_name' => 'Daggers Drawn',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 63,
                ],
                [
                    'sire_uid' => 712196,
                    'horse_uid' => 1592853,
                    'horse_style_name' => 'Jonboy',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 72,
                ],
                [
                    'sire_uid' => 732354,
                    'horse_uid' => 983078,
                    'horse_style_name' => 'Tomily',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 541314,
                    'dam_sire_style_name' => 'Acclamation',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 77,
                ],
                [
                    'sire_uid' => 733706,
                    'horse_uid' => 890185,
                    'horse_style_name' => 'Just Glamorous',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 448559,
                    'dam_sire_style_name' => 'Air Express',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 89,
                ],
                [
                    'sire_uid' => 733706,
                    'horse_uid' => 1958509,
                    'horse_style_name' => 'One One Seven',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 98576,
                    'dam_sire_style_name' => 'Mr Greeley',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 55,
                ],
                [
                    'sire_uid' => 736110,
                    'horse_uid' => 1576309,
                    'horse_style_name' => 'Showmethedough',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 304439,
                    'dam_sire_style_name' => 'Interrex',
                    'dam_sire_country_origin_code' => 'CAN',
                    'rp_postmark' => 80,
                ],
                [
                    'sire_uid' => 736110,
                    'horse_uid' => 1293766,
                    'horse_style_name' => 'Silver Starlight',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 66756,
                    'dam_sire_style_name' => 'Pursuit Of Love',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 71,
                ],
                [
                    'sire_uid' => 737653,
                    'horse_uid' => 891152,
                    'horse_style_name' => 'Rasheeq',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 503875,
                    'dam_sire_style_name' => 'Dansili',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 82,
                ],
                [
                    'sire_uid' => 737744,
                    'horse_uid' => 1936684,
                    'horse_style_name' => 'Ganton Eagle',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 75847,
                    'dam_sire_style_name' => 'College Chapel',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 20,
                ],
                [
                    'sire_uid' => 738816,
                    'horse_uid' => 1956414,
                    'horse_style_name' => 'Spirit Of Society',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 506927,
                    'dam_sire_style_name' => 'Invincible Spirit',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 32,
                ],
                [
                    'sire_uid' => 739856,
                    'horse_uid' => 964777,
                    'horse_style_name' => 'Super Julius',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 448003,
                    'dam_sire_style_name' => 'Bahamian Bounty',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 87,
                ],
                [
                    'sire_uid' => 740981,
                    'horse_uid' => 897748,
                    'horse_style_name' => 'Blue De Vega',
                    'horse_country_origin_code' => 'GER',
                    'dam_sire_uid' => 503034,
                    'dam_sire_style_name' => 'Montjeu',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 98,
                ],
                [
                    'sire_uid' => 749313,
                    'horse_uid' => 1371668,
                    'horse_style_name' => 'Billy Dylan',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 579845,
                    'dam_sire_style_name' => 'Kheleyf',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 82,
                ],
                [
                    'sire_uid' => 749313,
                    'horse_uid' => 1371859,
                    'horse_style_name' => 'Excellent Times',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 565797,
                    'dam_sire_style_name' => 'Oasis Dream',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 80,
                ],
                [
                    'sire_uid' => 749764,
                    'horse_uid' => 998347,
                    'horse_style_name' => 'Major Jumbo',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 534251,
                    'dam_sire_style_name' => 'Mizzen Mast',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 106,
                ],
                [
                    'sire_uid' => 749764,
                    'horse_uid' => 1462634,
                    'horse_style_name' => 'Savalas',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 653206,
                    'dam_sire_style_name' => 'Sharp Humor',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 99,
                ],
                [
                    'sire_uid' => 753279,
                    'horse_uid' => 1796214,
                    'horse_style_name' => 'Pesci',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 649434,
                    'dam_sire_style_name' => 'Teofilo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 756093,
                    'horse_uid' => 1932435,
                    'horse_style_name' => 'Prince Llyr',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 515706,
                    'dam_sire_style_name' => 'Zaha',
                    'dam_sire_country_origin_code' => 'CAN',
                    'rp_postmark' => 21,
                ],
                [
                    'sire_uid' => 756946,
                    'horse_uid' => 964674,
                    'horse_style_name' => 'Global Applause',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 103416,
                    'dam_sire_style_name' => 'Royal Applause',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 102,
                ],
                [
                    'sire_uid' => 756946,
                    'horse_uid' => 1503432,
                    'horse_style_name' => 'Roundhay Park',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 109112,
                    'dam_sire_style_name' => 'Daylami',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 93,
                ],
                [
                    'sire_uid' => 758138,
                    'horse_uid' => 890107,
                    'horse_style_name' => 'El Astronaute',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 602494,
                    'dam_sire_style_name' => 'Footstepsinthesand',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 102,
                ],
                [
                    'sire_uid' => 760422,
                    'horse_uid' => 964593,
                    'horse_style_name' => 'Arzaak',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 520309,
                    'dam_sire_style_name' => 'Dixie Union',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 62,
                ],
                [
                    'sire_uid' => 760422,
                    'horse_uid' => 974048,
                    'horse_style_name' => 'Celerity',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 467251,
                    'dam_sire_style_name' => 'Shinko Forest',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 35,
                ],
                [
                    'sire_uid' => 761072,
                    'horse_uid' => 1860253,
                    'horse_style_name' => 'I Am A Dreamer',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 92491,
                    'dam_sire_style_name' => 'Mind Games',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 75,
                ],
                [
                    'sire_uid' => 761072,
                    'horse_uid' => 1444122,
                    'horse_style_name' => 'Chatburn',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 657462,
                    'dam_sire_style_name' => 'Holy Roman Emperor',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 774595,
                    'horse_uid' => 1796373,
                    'horse_style_name' => 'Spell',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 578657,
                    'dam_sire_style_name' => 'One Cool Cat',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 79,
                ],
                [
                    'sire_uid' => 775057,
                    'horse_uid' => 1797829,
                    'horse_style_name' => 'Swiss Chime',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 692355,
                    'dam_sire_style_name' => 'Equiano',
                    'dam_sire_country_origin_code' => 'FR',
                    'rp_postmark' => 68,
                ],
                [
                    'sire_uid' => 777155,
                    'horse_uid' => 1860275,
                    'horse_style_name' => 'Treasure Quest',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 654568,
                    'dam_sire_style_name' => 'Excellent Art',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 777155,
                    'horse_uid' => 1514209,
                    'horse_style_name' => 'Two Seas',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 511443,
                    'dam_sire_style_name' => 'Fasliyev',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 50,
                ],
                [
                    'sire_uid' => 779232,
                    'horse_uid' => 1932430,
                    'horse_style_name' => 'Power Seeker',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 103416,
                    'dam_sire_style_name' => 'Royal Applause',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 0,
                ],
                [
                    'sire_uid' => 779353,
                    'horse_uid' => 1870916,
                    'horse_style_name' => 'Tin Hat',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 303737,
                    'dam_sire_style_name' => 'Green Desert',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 81,
                ],
                [
                    'sire_uid' => 779353,
                    'horse_uid' => 1444131,
                    'horse_style_name' => 'Pilkington',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 473501,
                    'dam_sire_style_name' => 'Diktat',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 75,
                ],
                [
                    'sire_uid' => 780033,
                    'horse_uid' => 1441816,
                    'horse_style_name' => 'Shay C',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 577888,
                    'dam_sire_style_name' => 'Exceed And Excel',
                    'dam_sire_country_origin_code' => 'AUS',
                    'rp_postmark' => 41,
                ],
                [
                    'sire_uid' => 781844,
                    'horse_uid' => 1406160,
                    'horse_style_name' => 'Requinto Dawn',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 579845,
                    'dam_sire_style_name' => 'Kheleyf',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 86,
                ],
                [
                    'sire_uid' => 781844,
                    'horse_uid' => 1917659,
                    'horse_style_name' => 'Good Tyne Girl',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 564704,
                    'dam_sire_style_name' => 'Clodovil',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 58,
                ],
                [
                    'sire_uid' => 783335,
                    'horse_uid' => 1371779,
                    'horse_style_name' => 'Angel Force',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 3618,
                    'dam_sire_style_name' => 'Indian Ridge',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 72,
                ],
                [
                    'sire_uid' => 784836,
                    'horse_uid' => 964606,
                    'horse_style_name' => 'Nautical Haven',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 42373,
                    'dam_sire_style_name' => 'Danehill',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 61,
                ],
                [
                    'sire_uid' => 784836,
                    'horse_uid' => 1927310,
                    'horse_style_name' => 'Look Out Louis',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 551806,
                    'dam_sire_style_name' => 'Act One',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 52,
                ],
                [
                    'sire_uid' => 784865,
                    'horse_uid' => 1922319,
                    'horse_style_name' => 'Aloysius Lilius',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 602045,
                    'dam_sire_style_name' => 'Shamardal',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 50,
                ],
                [
                    'sire_uid' => 786762,
                    'horse_uid' => 1031287,
                    'horse_style_name' => 'Dragstone Rock',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 544976,
                    'dam_sire_style_name' => 'Rock Of Gibraltar',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 79,
                ],
                [
                    'sire_uid' => 789808,
                    'horse_uid' => 1897245,
                    'horse_style_name' => 'Majestic Appeal',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 473501,
                    'dam_sire_style_name' => 'Diktat',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 60,
                ],
                [
                    'sire_uid' => 800166,
                    'horse_uid' => 1293891,
                    'horse_style_name' => 'Sir Hector',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 79045,
                    'dam_sire_style_name' => 'Kingmambo',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 71,
                ],
                [
                    'sire_uid' => 800166,
                    'horse_uid' => 976878,
                    'horse_style_name' => 'Lucata',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 42373,
                    'dam_sire_style_name' => 'Danehill',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 10,
                ],
                [
                    'sire_uid' => 800198,
                    'horse_uid' => 1932437,
                    'horse_style_name' => 'Pinaclouddown',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 516624,
                    'dam_sire_style_name' => 'King\'s Best',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 22,
                ],
                [
                    'sire_uid' => 805266,
                    'horse_uid' => 1870906,
                    'horse_style_name' => 'Five Amarones',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 590219,
                    'dam_sire_style_name' => 'Motivator',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 69,
                ],
                [
                    'sire_uid' => 805556,
                    'horse_uid' => 1860325,
                    'horse_style_name' => 'Carey Street',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 589733,
                    'dam_sire_style_name' => 'Hurricane Run',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 78,
                ],
                [
                    'sire_uid' => 805556,
                    'horse_uid' => 1927313,
                    'horse_style_name' => 'Bungle Billy',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 303729,
                    'dam_sire_style_name' => 'Nordance',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 0,
                ],
                [
                    'sire_uid' => 805559,
                    'horse_uid' => 1936683,
                    'horse_style_name' => 'Arriba De Toda',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 579845,
                    'dam_sire_style_name' => 'Kheleyf',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 32,
                ],
                [
                    'sire_uid' => 805559,
                    'horse_uid' => 1927311,
                    'horse_style_name' => 'Hurricane Five',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 682732,
                    'dam_sire_style_name' => 'Raven\'s Pass',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 0,
                ],
                [
                    'sire_uid' => 811093,
                    'horse_uid' => 1894516,
                    'horse_style_name' => 'Ynys Mon',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 538051,
                    'dam_sire_style_name' => 'Falbrav',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 83,
                ],
                [
                    'sire_uid' => 814257,
                    'horse_uid' => 1485774,
                    'horse_style_name' => 'Rickyroadboy',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 446205,
                    'dam_sire_style_name' => 'Superior Premium',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 61,
                ],
                [
                    'sire_uid' => 815858,
                    'horse_uid' => 1887397,
                    'horse_style_name' => 'Bengali Spirit',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 540336,
                    'dam_sire_style_name' => 'Dubai Destination',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 74,
                ],
                [
                    'sire_uid' => 821883,
                    'horse_uid' => 1954882,
                    'horse_style_name' => 'James Watt',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 547614,
                    'dam_sire_style_name' => 'Johannesburg',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 77,
                ],
                [
                    'sire_uid' => 821883,
                    'horse_uid' => 1953109,
                    'horse_style_name' => 'Blazing Dreams',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 53070,
                    'dam_sire_style_name' => 'Machiavellian',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 38,
                ],
                [
                    'sire_uid' => 829788,
                    'horse_uid' => 1953164,
                    'horse_style_name' => 'Kapono',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 92036,
                    'dam_sire_style_name' => 'Carnegie',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 62,
                ],
                [
                    'sire_uid' => 829788,
                    'horse_uid' => 1870951,
                    'horse_style_name' => 'Big Ace',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 528206,
                    'dam_sire_style_name' => 'Medicean',
                    'dam_sire_country_origin_code' => 'GB',
                    'rp_postmark' => 61,
                ],
                [
                    'sire_uid' => 831212,
                    'horse_uid' => 1953165,
                    'horse_style_name' => 'Juniors Fantasy',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 649434,
                    'dam_sire_style_name' => 'Teofilo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 0,
                ],
                [
                    'sire_uid' => 832546,
                    'horse_uid' => 1958508,
                    'horse_style_name' => 'Coach Trip',
                    'horse_country_origin_code' => 'GB',
                    'dam_sire_uid' => 470699,
                    'dam_sire_style_name' => 'Daggers Drawn',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 59,
                ],
                [
                    'sire_uid' => 839221,
                    'horse_uid' => 1909737,
                    'horse_style_name' => 'The Irish Rover',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 104011,
                    'dam_sire_style_name' => 'Danehill Dancer',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 87,
                ],
                [
                    'sire_uid' => 839221,
                    'horse_uid' => 1870915,
                    'horse_style_name' => 'Nayslayer',
                    'horse_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 304579,
                    'dam_sire_style_name' => 'Gulch',
                    'dam_sire_country_origin_code' => 'USA',
                    'rp_postmark' => 60,
                ],
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '2b2126e11c021309d74901315a87f051' => [
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            'eb50c6d371a291dfb376d7346ce310e6' => [],
            'e03b10673a484a9fb90442c15bf74170' => [],
            'c8767c5cb230e3ef39ddbb7447c0e268' => [],
        ];
    }

    /**
     * @return array
     */
    public function getReplacement(): array
    {
        return [
            'seasonStartDate' => '2018-01-01 00:00:00',
            'seasonEndDate' => '2018-12-31 23:59:00',
        ];
    }
}
