/*
Generated by SQLBrowser 2014_05 1202 on 19 Nov 2014
*/

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 1, NULL, 'CHK_MEDIAN', 18, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 2, NULL, 'CHK_NUM_RACES', 18, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 3, NULL, 'CHK_RSQUARE', NULL, NULL, NULL, 0.15, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 5, NULL, 'CHK_FIELD_HIGH', 5, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 6, NULL, 'CHK_FIELD_STRAIGHT_MAX', 19, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 7, NULL, 'CHK_STRAIGHTS_SLOPE', NULL, NULL, -0.10, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 8, NULL, 'CHK_STRAIGHTS_SLOPE_PLUS', NULL, NULL, 0.10, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 9, NULL, 'CHK_FAIL_SIG_STRAIGHT_RUNNER', 20, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 10, NULL, 'CHK_GOING_FACTOR_A', NULL, NULL, 1.00, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 11, NULL, 'CHK_GOING_FACTOR_B', NULL, NULL, 1.25, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 12, NULL, 'CHK_GOING_FACTOR_C', NULL, NULL, 1.33, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 13, NULL, 'CHK_GOING_FACTOR_D', NULL, NULL, 1.66, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 14, NULL, 'CHK_STRENGTH_LOW_TEXT', NULL, NULL, NULL, NULL, 'LOW'
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 15, NULL, 'CHK_STRENGTH_HIGH_TEXT', NULL, NULL, NULL, NULL, 'HIGH'
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 16, NULL, 'CHK_SUM_NO_SIG_TXT', NULL, NULL, NULL, NULL, 'NO SIGNIFICANT ADVANTAGE'
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 17, NULL, 'CHK_SUM_INS_TXT', NULL, NULL, NULL, NULL, 'INSUFFICIENT DATA'
)


insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 18, NULL, 'CHK_BIAS_STRENGTH_SLIGHT', NULL, NULL, NULL, 1.49, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 19, NULL, 'CHK_BIAS_STRENGTH_MIN', NULL, NULL, NULL, 0.5, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 20, NULL, 'CHK_NUM_RACES_DISTANCE', 3080, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 21, NULL, 'CHK_NUM_RACES_LONGRUNNERS', 1, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 22, NULL, 'CHK_NUM_RACES_LONGDRAWS', 8, NULL, NULL, NULL, NULL
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 23, NULL, 'CHK_TXT_SLIGHT', NULL, NULL, NULL, NULL, 'SLIGHT'
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 24, NULL, 'CHK_TXT_STRONG', NULL, NULL, NULL, NULL, 'STRONG'
)

insert da_config(
 config_uid, course_uid, config_desc, config_int, config_char1, config_dec62, config_dec63, config_varchar255
) values (
 25, NULL, 'CHK_TXT_NONE', NULL, NULL, NULL, NULL, 'NONE'
)

go


/*
Generated by SQLBrowser 2014_05 1202 on 24 Nov 2014
*/
insert da_flip_data(
 course_uid, distance_yards
) values (
 5, 2882
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 7, 2189
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 7, 2616
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 12, 1116
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 12, 1336
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 12, 1556
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 12, 1774
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 16, 3520
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 19, 1100
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 19, 1320
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 19, 1540
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 21, 2420
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 21, 2640
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 21, 3520
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 23, 1100
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 23, 1320
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 31, 2526
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 37, 1100
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 37, 1320
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 37, 1540
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 37, 1760
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 40, 1113
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 40, 1335
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 80, 2640
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 93, 2207
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 93, 2555
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 107, 1189
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 394, 1100
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 513, 1572
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 1212, 1100
)

insert da_flip_data(
 course_uid, distance_yards
) values (
 1212, 1320
)

go


/*
Generated by SQLBrowser 2014_05 1202 on 24 Nov 2014
*/
insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 3, 1980, 2000
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 5, 2200, 2246
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 8, 2626, 2527
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 13, 1210, 1338
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 13, 2499, 2275
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 13, 3171, 2949
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 15, 1240, 1100
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 15, 1430, 1320
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 30, 1769, 1820
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 47, 2420, 2200
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 49, 1980, 1760
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 85, 1210, 1320
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 107, 3080, 3057
)

insert da_course_distance_override(
 course_uid, distance_yards, distance_yard_to_use
) values (
 107, 3608, 3498
)

go
