<?php

namespace Tests\Stubs\Models\Bo\OwnerProfile;

use Tests\Stubs\Models\Statistics as Model;
use Tests\Stubs\Models\StubDataGetter;

class Statistics extends Model
{
    use StubDataGetter;

    private static $data;

    /**
     * @return mixed
     */
    public function getStatistics(\Api\Input\Request\HorsesRequest $request, \Models\Selectors $selectors)
    {
        if (empty(self::$data)) {
            $this->init();
        }

        return self::$data[self::getRequestKey($request)];
    }

    private function init()
    {
        self::$data =
            [
                '2012_2012_GB_flat_trainer_turf_11279' => [
                    "OVERALL" => (Object)[
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 18734,
                            "group_name" => "Harry Dunlop",
                            "rides" => 3,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -3,
                            "total_prize" => 1876,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 13955,
                            "group_name" => "Jamie Osborne",
                            "rides" => 3,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 2,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -3,
                            "total_prize" => 1756,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 7221,
                            "group_name" => "Brian Meehan",
                            "rides" => 4,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 1,
                            "race_placed" => 2,
                            "percent" => 0,
                            "stakes" => -4,
                            "total_prize" => 1972.7,
                        ]
                    ],
                    "3YO" => [
                        (Object)[
                            "category" => "3YO",
                            "group_id" => 13955,
                            "group_name" => "Jamie Osborne",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 673.75,
                        ],
                        (Object)[
                            "category" => "3YO",
                            "group_id" => 18734,
                            "group_name" => "Harry Dunlop",
                            "rides" => 3,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -3,
                            "total_prize" => 1876,
                        ]
                    ],
                    "2YO" => [
                        (Object)[
                            "category" => "2YO",
                            "group_id" => 13955,
                            "group_name" => "Jamie Osborne",
                            "rides" => 2,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 2,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -2,
                            "total_prize" => 1082.25,
                        ],
                        (Object)[
                            "category" => "2YO",
                            "group_id" => 7221,
                            "group_name" => "Brian Meehan",
                            "rides" => 4,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 1,
                            "race_placed" => 2,
                            "percent" => 0,
                            "stakes" => -4,
                            "total_prize" => 1972.7,
                        ]
                    ]
                ],
                '2014_2015_IRE_jumps_month__11279' => [
                    "OVERALL" => [
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "November 2014",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 50,
                            "stakes" => 1.75,
                            "total_prize" => 13035,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "December 2014",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 50,
                            "stakes" => -0.27,
                            "total_prize" => 15290,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "January 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "April 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "May 2015",
                            "rides" => 3,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 33,
                            "stakes" => -0.38,
                            "total_prize" => 8590,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "June 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 2400,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "July 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 4275,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "September 2015",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 50,
                            "stakes" => 0.1,
                            "total_prize" => 23680,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "November 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 1440,
                        ]
                    ],
                    "CHASE" => [
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => null,
                            "group_name" => "May 2015",
                            "rides" => 1,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 100,
                            "stakes" => 1.63,
                            "total_prize" => 7590,
                        ],
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => null,
                            "group_name" => "June 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 2400,
                        ],
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => null,
                            "group_name" => "July 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 4275,
                        ],
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => null,
                            "group_name" => "September 2015",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 50,
                            "stakes" => 0.1,
                            "total_prize" => 23680,
                        ]
                    ],
                    "HURDLE" => [
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => null,
                            "group_name" => "November 2014",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 50,
                            "stakes" => 1.75,
                            "total_prize" => 13035,
                        ],
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => null,
                            "group_name" => "December 2014",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 50,
                            "stakes" => -0.27,
                            "total_prize" => 15290,
                        ],
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => null,
                            "group_name" => "January 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => null,
                            "group_name" => "May 2015",
                            "rides" => 2,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -2,
                            "total_prize" => 1000,
                        ]
                    ],
                    "NHF" => [
                        (Object)[
                            "category" => "NHF",
                            "group_id" => null,
                            "group_name" => "April 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "NHF",
                            "group_id" => null,
                            "group_name" => "November 2015",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 1440,
                        ]
                    ]
                ],
                '2011_2012_IRE_jumps_horse__11279' => [
                    "OVERALL" => [
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 803559,
                            "group_name" => "Operating",
                            "rides" => 6,
                            "wins" => 2,
                            "place_2nd_number" => 2,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 1,
                            "race_placed" => 5,
                            "percent" => 33,
                            "stakes" => -1.68,
                            "total_prize" => 19730,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 830217,
                            "group_name" => "Beat That",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 834415,
                            "group_name" => "Rock The World",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 1440,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 795325,
                            "group_name" => "Soliwery",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 766800,
                            "group_name" => "Mystic Desir",
                            "rides" => 9,
                            "wins" => 0,
                            "place_2nd_number" => 2,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 2,
                            "percent" => 0,
                            "stakes" => -9,
                            "total_prize" => 3600,
                        ]
                    ],
                    "NHF" => [
                        (Object)[
                            "category" => "NHF",
                            "group_id" => 803559,
                            "group_name" => "Operating",
                            "rides" => 1,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 100,
                            "stakes" => 0.57,
                            "total_prize" => 5520,
                        ],
                        (Object)[
                            "category" => "NHF",
                            "group_id" => 830217,
                            "group_name" => "Beat That",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "NHF",
                            "group_id" => 834415,
                            "group_name" => "Rock The World",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 1,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 1440,
                        ]
                    ],
                    "HURDLE" => [
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => 803559,
                            "group_name" => "Operating",
                            "rides" => 5,
                            "wins" => 1,
                            "place_2nd_number" => 2,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 1,
                            "race_placed" => 4,
                            "percent" => 20,
                            "stakes" => -2.25,
                            "total_prize" => 14210,
                        ],
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => 795325,
                            "group_name" => "Soliwery",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => 766800,
                            "group_name" => "Mystic Desir",
                            "rides" => 9,
                            "wins" => 0,
                            "place_2nd_number" => 2,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 2,
                            "percent" => 0,
                            "stakes" => -9,
                            "total_prize" => 3600,
                        ]
                    ]
                ],
                '2014_2014_GB_flat_distance_aw_11279' => [
                    "OVERALL" => [
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "1651-2090",
                            "rides" => 8,
                            "wins" => 2,
                            "place_2nd_number" => 3,
                            "place_3rd_number" => 2,
                            "place_4th_number" => 0,
                            "race_placed" => 6,
                            "percent" => 25,
                            "stakes" => -0.75,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "2091-2530",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => null,
                            "group_name" => "2531-2970",
                            "rides" => 3,
                            "wins" => 2,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 67,
                            "stakes" => 7.5,
                            "total_prize" => 0,
                        ]
                    ],
                    "2YO" => [
                        (Object)[
                            "category" => "2YO",
                            "group_id" => null,
                            "group_name" => "1651-2090",
                            "rides" => 4,
                            "wins" => 1,
                            "place_2nd_number" => 1,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 25,
                            "stakes" => -0.5,
                            "total_prize" => 0,
                        ]
                    ],
                    "3YO" => [
                        (Object)[
                            "category" => "3YO",
                            "group_id" => null,
                            "group_name" => "1651-2090",
                            "rides" => 4,
                            "wins" => 1,
                            "place_2nd_number" => 2,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 4,
                            "percent" => 25,
                            "stakes" => -0.25,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "3YO",
                            "group_id" => null,
                            "group_name" => "2091-2530",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 1,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "3YO",
                            "group_id" => null,
                            "group_name" => "2531-2970",
                            "rides" => 3,
                            "wins" => 2,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 67,
                            "stakes" => 7.5,
                            "total_prize" => 0,
                        ]
                    ]
                ],
                '50036' => [
                    "OVERALL" => (Object)[
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 39,
                            "group_name" => "Newton Abbot",
                            "rides" => 3,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 2,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 33,
                            "stakes" => -0.5,
                            "total_prize" => 1400,
                        ],
                        (Object)[
                            "category" => "OVERALL",
                            "group_id" => 67,
                            "group_name" => "Stratford",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 1972,
                        ]
                    ],
                    "CHASE" => (Object)[
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => 39,
                            "group_name" => "Newton Abbot",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 0,
                        ],
                        (Object)[
                            "category" => "CHASE",
                            "group_id" => 67,
                            "group_name" => "Stratford",
                            "rides" => 1,
                            "wins" => 0,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 0,
                            "place_4th_number" => 0,
                            "race_placed" => 0,
                            "percent" => 0,
                            "stakes" => -1,
                            "total_prize" => 3600,
                        ]
                    ],
                    "HURDLE" => (Object)[
                        (Object)[
                            "category" => "HURDLE",
                            "group_id" => 39,
                            "group_name" => "Newton Abbot",
                            "rides" => 2,
                            "wins" => 1,
                            "place_2nd_number" => 0,
                            "place_3rd_number" => 1,
                            "place_4th_number" => 0,
                            "race_placed" => 2,
                            "percent" => 50,
                            "stakes" => 0.5,
                            "total_prize" => 26300,
                        ]
                    ]
                ],
            ];
    }
}
