<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Native\Cards\Predictor\Race;

use UnitTestsComponents\ApiRouteTest\Xml as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\Native\Cards\Predictor\Race
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/native/cards/705883/predictor';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\Predictor\RaceInstance:37 ->isRaceExists()
            'c7bd6cc1b542d7bc2228d3336ad08889' => [
                [
                    'computed' => 1,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:83 ->getRace()
            '95398eadca67f1d79f1dec0f9c1c4b8a' => [
                [
                    'race_instance_uid' => 705883,
                    'race_type_code' => 'F',
                    'race_datetime' => '2018-06-26 17:45:00',
                    'race_status_code' => 'O',
                    'course' => 'BALLINROBE',
                    'course_uid' => 175,
                    'country_code' => 'IRE',
                    'distance_yard' => 2150,
                    'going' => 'Good',
                    'ages_allowed' => '3yo',
                    'latitude' => 53.638379,
                    'longitude' => -9.244995,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:37 ->isRaceExists()
            'c7bd6cc1b542d7bc2228d3336ad08889' => [
                [
                    'computed' => 1,
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:169 ->getHorses()
            '02c49a3705c42347bf558f9ad97f60fd' => [
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Descendant',
                    'country_origin_code' => 'GB',
                    'horse_id' => 1451540,
                    'start_number' => 1,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 250256,
                    'owner_name' => 'The Descendant Partnership',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Sea The Spray',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1589397,
                    'start_number' => 6,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 91203,
                    'owner_name' => 'David Armstrong',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Eadbhard',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1605435,
                    'start_number' => 2,
                    'owner_choice' => 'c',
                    'non_runner' => null,
                    'owner_uid' => 112149,
                    'owner_name' => 'John M Keogh',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Magical Link',
                    'country_origin_code' => 'USA',
                    'horse_id' => 1605438,
                    'start_number' => 5,
                    'owner_choice' => 'c',
                    'non_runner' => 'Y',
                    'owner_uid' => 59635,
                    'owner_name' => 'Laurence O\'Kane',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Time Queen',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1622120,
                    'start_number' => 4,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 212930,
                    'owner_name' => 'Mrs N K Griffin & T Brosnan',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Viscount Wilson',
                    'country_origin_code' => 'GB',
                    'horse_id' => 1633902,
                    'start_number' => 3,
                    'owner_choice' => 'a',
                    'non_runner' => null,
                    'owner_uid' => 176032,
                    'owner_name' => 'David Spratt',
                ],
                [
                    'race_instance_uid' => 705883,
                    'style_name' => 'Maricruz',
                    'country_origin_code' => 'IRE',
                    'horse_id' => 1659601,
                    'start_number' => 7,
                    'owner_choice' => 'f',
                    'non_runner' => null,
                    'owner_uid' => 197655,
                    'owner_name' => 'Rockview Racing Club',
                ],
            ],
            //Api\DataProvider\Bo\Predictor\RaceInstance:228 ->getPostdata()
            'b21933b04e5c62cde842a70240d0684a' => [
                [
                    'horse_style_name' => 'Descendant',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'X',
                    'going_output' => 'a',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'aa',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 1,
                    'horse_uid' => 1451540,
                    'rp_tops' => 53,
                    'rp_pm_chars' => null,
                    'official_rating' => 65,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 53,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => null,
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 15240,
                    'top_speed' => 53,
                    'RPR' => 78,
                    'form_points' => 1.5,
                ],
                [
                    'horse_style_name' => 'Sea The Spray',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => '?',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'X',
                    'recent_form_output' => '?',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 6,
                    'horse_uid' => 1589397,
                    'rp_tops' => null,
                    'rp_pm_chars' => null,
                    'official_rating' => 0,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 12,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => null,
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 10588,
                    'top_speed' => null,
                    'RPR' => 46,
                    'form_points' => 0.0,
                ],
                [
                    'horse_style_name' => 'Eadbhard',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'X',
                    'going_output' => 'a',
                    'distance_output' => 'a',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'aa',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 2,
                    'horse_uid' => 1605435,
                    'rp_tops' => 60,
                    'rp_pm_chars' => null,
                    'official_rating' => 61,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 14,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => 'N',
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 20679,
                    'top_speed' => 60,
                    'RPR' => 77,
                    'form_points' => 1.5,
                ],
                [
                    'horse_style_name' => 'Magical Link',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => '?',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'X',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 5,
                    'horse_uid' => 1605438,
                    'rp_tops' => 19,
                    'rp_pm_chars' => null,
                    'official_rating' => 60,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 68,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => null,
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 17308,
                    'top_speed' => 19,
                    'RPR' => 79,
                    'form_points' => -0.5,
                ],
                [
                    'horse_style_name' => 'Time Queen',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => '-',
                    'going_output' => '?',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'a',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 4,
                    'horse_uid' => 1622120,
                    'rp_tops' => 54,
                    'rp_pm_chars' => null,
                    'official_rating' => 0,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 38,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => null,
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 4858,
                    'top_speed' => 54,
                    'RPR' => 80,
                    'form_points' => 0.75,
                ],
                [
                    'horse_style_name' => 'Viscount Wilson',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'aa',
                    'going_output' => '?',
                    'distance_output' => 'a',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'aa',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 3,
                    'horse_uid' => 1633902,
                    'rp_tops' => 74,
                    'rp_pm_chars' => 'X',
                    'official_rating' => 68,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 117,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => 'N',
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 8567,
                    'top_speed' => 74,
                    'RPR' => 83,
                    'form_points' => 1.5,
                ],
                [
                    'horse_style_name' => 'Maricruz',
                    'trainer_record_output' => '-',
                    'trainer_form_output' => 'a',
                    'going_output' => 'a',
                    'distance_output' => '?',
                    'course_output' => '?',
                    'ability_output' => 'aa',
                    'recent_form_output' => 'aa',
                    'group_race' => ' ',
                    'saddle_cloth_no' => 7,
                    'horse_uid' => 1659601,
                    'rp_tops' => 54,
                    'rp_pm_chars' => null,
                    'official_rating' => 63,
                    'draw_output' => '-',
                    'race_instance_uid' => 705883,
                    'jockey_no_wins_flag' => ' ',
                    'first_time_blinkers' => ' ',
                    'jockey_wins' => 18,
                    'jockey_stable_wins' => 1,
                    'is_first_time' => 'N',
                    'race_datetime' => '2018-06-26 17:45:00',
                    'course_name' => 'BALLINROBE',
                    'trainer_id' => 14751,
                    'top_speed' => 54,
                    'RPR' => 82,
                    'form_points' => 1.5,
                ],
            ],
        ];
    }
}
