<?php
/**
 * Created by PhpStorm.
 * User: Stanislav_Kosatkin
 * Date: 8/9/2016
 * Time: 6:11 PM
 */

namespace Tests\Stubs\DataProvider\Bo\Bloodstock\SalesStatistics;

use Api\Input\Request\Horses\Bloodstock\SalesStatistics as Request;

class Buyers extends \Api\DataProvider\Bo\Bloodstock\SalesStatistics\Buyers
{
    use \Tests\Stubs\Models\StubDataGetter;

    public function getBuyers(Request\Buyers $request)
    {
        $key = self::getRequestKey($request);
        $results = [
            '5_2016-05-01_2016-05-09' => [
                0 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  7 2016 12:00AM',
                        'buyer_detail' => 'Abdulatif Hussain Al-Emadi',
                        'search_buyer_detail' => 'ABDULATIFHUSSAINALEMADI',
                        'price' => 16000,
                        'lot_no' => 347,
                        'lot_letter' => null,
                        'horse_uid' => 896680,
                        'horse_name' => 'GOLD TRADE',
                        'horse_style_name' => 'Gold Trade',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'G',
                        'horse_age' => 3,
                        'dam_uid' => 640743,
                        'dam_name' => 'TRADING PLACES',
                        'dam_style_name' => 'Trading Places',
                        'sire_uid' => 682732,
                        'sire_name' => 'RAVEN\'S PASS',
                        'sire_style_name' => 'Raven\'s Pass',
                        'sire_of_dam_uid' => 503875,
                        'sire_of_dam_name' => 'DANSILI',
                        'sire_of_dam_style_name' => 'Dansili',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                1 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  7 2016 12:00AM',
                        'buyer_detail' => 'Abdulatif Hussain Al-Emadi',
                        'search_buyer_detail' => 'ABDULATIFHUSSAINALEMADI',
                        'price' => 27000,
                        'lot_no' => 454,
                        'lot_letter' => null,
                        'horse_uid' => 886872,
                        'horse_name' => 'ADHAM',
                        'horse_style_name' => 'Adham',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'C',
                        'horse_age' => 3,
                        'dam_uid' => 579850,
                        'dam_name' => 'LEOPARD CREEK',
                        'dam_style_name' => 'Leopard Creek',
                        'sire_uid' => 761072,
                        'sire_name' => 'DREAM AHEAD',
                        'sire_style_name' => 'Dream Ahead',
                        'sire_of_dam_uid' => 40598,
                        'sire_of_dam_name' => 'WELDNAAS',
                        'sire_of_dam_style_name' => 'Weldnaas',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                2 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  8 2016 12:00AM',
                        'buyer_detail' => 'Abdullah AAFM Al-Ajmi',
                        'search_buyer_detail' => 'ABDULLAHAAFMALAJMI',
                        'price' => 35000,
                        'lot_no' => 841,
                        'lot_letter' => 'A',
                        'horse_uid' => 871509,
                        'horse_name' => 'CLOUD SEVEN',
                        'horse_style_name' => 'Cloud Seven',
                        'horse_first_colour_code' => 'BR',
                        'horse_sex' => 'G',
                        'horse_age' => 4,
                        'dam_uid' => 711668,
                        'dam_name' => 'REGRETTE RIEN',
                        'dam_style_name' => 'Regrette Rien',
                        'sire_uid' => 670119,
                        'sire_name' => 'NEW APPROACH',
                        'sire_style_name' => 'New Approach',
                        'sire_of_dam_uid' => 107577,
                        'sire_of_dam_name' => 'UNBRIDLED\'S SONG',
                        'sire_of_dam_style_name' => 'Unbridled\'s Song',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                3 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  6 2016 12:00AM',
                        'buyer_detail' => 'Abdullah Meeshrf',
                        'search_buyer_detail' => 'ABDULLAHMEESHRF',
                        'price' => 30000,
                        'lot_no' => 182,
                        'lot_letter' => null,
                        'horse_uid' => 893491,
                        'horse_name' => 'SPENNITHORNE',
                        'horse_style_name' => 'Spennithorne',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'dam_uid' => 551243,
                        'dam_name' => 'TWO MARKS',
                        'dam_style_name' => 'Two Marks',
                        'sire_uid' => 602045,
                        'sire_name' => 'SHAMARDAL',
                        'sire_style_name' => 'Shamardal',
                        'sire_of_dam_uid' => 303747,
                        'sire_of_dam_name' => 'WOODMAN',
                        'sire_of_dam_style_name' => 'Woodman',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                4 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  6 2016 12:00AM',
                        'buyer_detail' => 'WITHDRAWN',
                        'search_buyer_detail' => 'ABDULLAHMESHRIFALKAHTHANI',
                        'price' => 15000,
                        'lot_no' => 297,
                        'lot_letter' => null,
                        'horse_uid' => 860969,
                        'horse_name' => 'UNYIELDING',
                        'horse_style_name' => 'Unyielding',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'G',
                        'horse_age' => 4,
                        'dam_uid' => 536683,
                        'dam_name' => 'VICTORIA CROSS',
                        'dam_style_name' => 'Victoria Cross',
                        'sire_uid' => 565797,
                        'sire_name' => 'OASIS DREAM',
                        'sire_style_name' => 'Oasis Dream',
                        'sire_of_dam_uid' => 105212,
                        'sire_of_dam_name' => 'MARK OF ESTEEM',
                        'sire_of_dam_style_name' => 'Mark Of Esteem',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                5 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  8 2016 12:00AM',
                        'buyer_detail' => 'WITHDRAWN',
                        'search_buyer_detail' => 'ABDULLAHMESHRIFALKAHTHANI',
                        'price' => 52000,
                        'lot_no' => 713,
                        'lot_letter' => null,
                        'horse_uid' => 865030,
                        'horse_name' => 'SALIERIS MASS',
                        'horse_style_name' => 'Salieris Mass',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'G',
                        'horse_age' => 4,
                        'dam_uid' => 658746,
                        'dam_name' => 'SUNLEY GIFT',
                        'dam_style_name' => 'Sunley Gift',
                        'sire_uid' => 660604,
                        'sire_name' => 'MOUNT NELSON',
                        'sire_style_name' => 'Mount Nelson',
                        'sire_of_dam_uid' => 9363,
                        'sire_of_dam_name' => 'CADEAUX GENEREUX',
                        'sire_of_dam_style_name' => 'Cadeaux Genereux',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                6 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  7 2016 12:00AM',
                        'buyer_detail' => 'WITHDRAWN',
                        'search_buyer_detail' => 'ABDULLAHMESHRIFALKAHTHANI',
                        'price' => 72000,
                        'lot_no' => 408,
                        'lot_letter' => null,
                        'horse_uid' => 859640,
                        'horse_name' => 'BURNT SUGAR',
                        'horse_style_name' => 'Burnt Sugar',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'C',
                        'horse_age' => 4,
                        'dam_uid' => 634157,
                        'dam_name' => 'LADY LIVIUS',
                        'dam_style_name' => 'Lady Livius',
                        'sire_uid' => 740981,
                        'sire_name' => 'LOPE DE VEGA',
                        'sire_style_name' => 'Lope De Vega',
                        'sire_of_dam_uid' => 106018,
                        'sire_of_dam_name' => 'TITUS LIVIUS',
                        'sire_of_dam_style_name' => 'Titus Livius',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                7 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  7 2016 12:00AM',
                        'buyer_detail' => 'A C Elliott, Agent',
                        'search_buyer_detail' => 'ACELLIOTT',
                        'price' => 72000,
                        'lot_no' => 390,
                        'lot_letter' => null,
                        'horse_uid' => 895105,
                        'horse_name' => 'SUMMER COLLECTION',
                        'horse_style_name' => 'Summer Collection',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'dam_uid' => 718036,
                        'dam_name' => 'TOWARDS',
                        'dam_style_name' => 'Towards',
                        'sire_uid' => 649434,
                        'sire_name' => 'TEOFILO',
                        'sire_style_name' => 'Teofilo',
                        'sire_of_dam_uid' => 528538,
                        'sire_of_dam_name' => 'FUSAICHI PEGASUS',
                        'sire_of_dam_style_name' => 'Fusaichi Pegasus',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                8 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  8 2016 12:00AM',
                        'buyer_detail' => 'Adam Potts',
                        'search_buyer_detail' => 'ADAMPOTTS',
                        'price' => 3000,
                        'lot_no' => 721,
                        'lot_letter' => null,
                        'horse_uid' => 897275,
                        'horse_name' => 'LILLY VEGA',
                        'horse_style_name' => 'Lilly Vega',
                        'horse_first_colour_code' => 'CH',
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'dam_uid' => 760398,
                        'dam_name' => 'SALPIGLOSSIS',
                        'dam_style_name' => 'Salpiglossis',
                        'sire_uid' => 740981,
                        'sire_name' => 'LOPE DE VEGA',
                        'sire_style_name' => 'Lope De Vega',
                        'sire_of_dam_uid' => 84824,
                        'sire_of_dam_name' => 'MONSUN',
                        'sire_of_dam_style_name' => 'Monsun',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
                9 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sale_date' => 'Jul  6 2016 12:00AM',
                        'buyer_detail' => 'Adam West',
                        'search_buyer_detail' => 'ADAMWEST',
                        'price' => 3200,
                        'lot_no' => 316,
                        'lot_letter' => null,
                        'horse_uid' => 974063,
                        'horse_name' => 'DOC SPORTELLO',
                        'horse_style_name' => 'Doc Sportello',
                        'horse_first_colour_code' => 'B',
                        'horse_sex' => 'G',
                        'horse_age' => 4,
                        'dam_uid' => 464075,
                        'dam_name' => 'QUEEN OF SILK',
                        'dam_style_name' => 'Queen Of Silk',
                        'sire_uid' => 579854,
                        'sire_name' => 'MAJESTIC MISSILE',
                        'sire_style_name' => 'Majestic Missile',
                        'sire_of_dam_uid' => 72069,
                        'sire_of_dam_name' => 'BRIEF TRUCE',
                        'sire_of_dam_style_name' => 'Brief Truce',
                        'cur_code' => 'GBG',
                        'currency_code' => 'GNS',
                        'exchange_rate' => 0.95238,
                    ]
                ),
            ],
            '1_2016-05-01_2016-05-09' => []
         ];

        return $results[$key];
    }
}
