<?php
/**
 * Created by PhpStorm.
 * User: Stanislav_Kosatkin
 * Date: 8/11/2016
 * Time: 5:16 PM
 */

namespace Tests\Stubs\DataProvider\Bo\Bloodstock\SalesStatistics;

use Api\Input\Request\Horses\Bloodstock\SalesStatistics as Request;

class Vendors extends \Api\DataProvider\Bo\Bloodstock\SalesStatistics\Vendors
{
    public function getVendors(Request\Vendors $request)
    {
        return [
            0 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Lee Woolams',
                    'search_buyer_detail' => 'LEEWOOLAMS',
                    'seller_name' => 'From Acorn Stud, Ireland',
                    'search_seller_name' => 'ACORNSTUD',
                    'price' => 2000,
                    'lot_no' => 44,
                    'lot_letter' => null,
                    'horse_uid' => 688534,
                    'horse_name' => 'IDONEA',
                    'horse_style_name' => 'Idonea',
                    'horse_first_colour_code' => 'CH',
                    'horse_sex' => 'M',
                    'horse_age' => 11,
                    'dam_uid' => 688526,
                    'dam_name' => 'IVASTAR',
                    'dam_style_name' => 'Ivastar',
                    'sire_uid' => 90597,
                    'sire_name' => 'SWAIN',
                    'sire_style_name' => 'Swain',
                    'sire_of_dam_uid' => 7365,
                    'sire_of_dam_name' => 'ALWASMI',
                    'sire_of_dam_style_name' => 'Alwasmi',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            1 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Not Sold',
                    'search_buyer_detail' => 'NOTSOLD',
                    'seller_name' => 'Oak Hill Stud from Acorn Stud, Ireland',
                    'search_seller_name' => 'ACORNSTUD',
                    'price' => 7800,
                    'lot_no' => 45,
                    'lot_letter' => null,
                    'horse_uid' => 887560,
                    'horse_name' => 'RIDE A RAINBOW',
                    'horse_style_name' => 'Ride A Rainbow',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 9,
                    'dam_uid' => 583914,
                    'dam_name' => 'CELTIC HEROINE',
                    'dam_style_name' => 'Celtic Heroine',
                    'sire_uid' => 303440,
                    'sire_name' => 'RAINBOW QUEST',
                    'sire_style_name' => 'Rainbow Quest',
                    'sire_of_dam_uid' => 76009,
                    'sire_of_dam_name' => 'HERNANDO',
                    'sire_of_dam_style_name' => 'Hernando',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            2 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Emerald Bloodstock',
                    'search_buyer_detail' => 'EMERALDBLOODSTOCK',
                    'seller_name' => 'From Aislabie Stud',
                    'search_seller_name' => 'AISLABIESTUD',
                    'price' => 12000,
                    'lot_no' => 33,
                    'lot_letter' => 'b',
                    'horse_uid' => 602951,
                    'horse_name' => 'PLAY BOUZOUKI',
                    'horse_style_name' => 'Play Bouzouki',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 15,
                    'dam_uid' => 447161,
                    'dam_name' => 'BALALAIKA',
                    'dam_style_name' => 'Balalaika',
                    'sire_uid' => 96463,
                    'sire_name' => 'HALLING',
                    'sire_style_name' => 'Halling',
                    'sire_of_dam_uid' => 463975,
                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                    'sire_of_dam_style_name' => 'Sadler\'s Wells',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            3 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Kaloni OE',
                    'search_buyer_detail' => 'KALONIOE',
                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                    'price' => 1000,
                    'lot_no' => 870,
                    'lot_letter' => null,
                    'horse_uid' => 877152,
                    'horse_name' => 'ACE REBEL',
                    'horse_style_name' => 'Ace Rebel',
                    'horse_first_colour_code' => 'CH',
                    'horse_sex' => 'C',
                    'horse_age' => 3,
                    'dam_uid' => 643008,
                    'dam_name' => 'QUADROPHENIA',
                    'dam_style_name' => 'Quadrophenia',
                    'sire_uid' => 448003,
                    'sire_name' => 'BAHAMIAN BOUNTY',
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_of_dam_uid' => 75847,
                    'sire_of_dam_name' => 'COLLEGE CHAPEL',
                    'sire_of_dam_style_name' => 'College Chapel',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            4 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Compas Equine',
                    'search_buyer_detail' => 'COMPASEQUINE',
                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                    'price' => 6500,
                    'lot_no' => 869,
                    'lot_letter' => null,
                    'horse_uid' => 877157,
                    'horse_name' => 'REBEL RAISER',
                    'horse_style_name' => 'Rebel Raiser',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'G',
                    'horse_age' => 3,
                    'dam_uid' => 486917,
                    'dam_name' => 'TRUMP STREET',
                    'dam_style_name' => 'Trump Street',
                    'sire_uid' => 579845,
                    'sire_name' => 'KHELEYF',
                    'sire_style_name' => 'Kheleyf',
                    'sire_of_dam_uid' => 84334,
                    'sire_of_dam_name' => 'FIRST TRUMP',
                    'sire_of_dam_style_name' => 'First Trump',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            5 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Vendor',
                    'search_buyer_detail' => 'VENDOR',
                    'seller_name' => 'Apple Tree Stud',
                    'search_seller_name' => 'APPLETREESTUD',
                    'price' => 40000,
                    'lot_no' => 93,
                    'lot_letter' => null,
                    'horse_uid' => null,
                    'horse_name' => 'EMPRESS ROCK',
                    'horse_style_name' => null,
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => null,
                    'dam_name' => 'ROMAN EMPRESS',
                    'dam_style_name' => null,
                    'sire_uid' => null,
                    'sire_name' => 'FASTNET ROCK',
                    'sire_style_name' => null,
                    'sire_of_dam_uid' => null,
                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                    'sire_of_dam_style_name' => null,
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            6 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Vendor',
                    'search_buyer_detail' => 'VENDOR',
                    'seller_name' => 'From Aston Mullins Stud',
                    'search_seller_name' => 'ASTONMULLINSSTUD',
                    'price' => 11000,
                    'lot_no' => 85,
                    'lot_letter' => null,
                    'horse_uid' => 724355,
                    'horse_name' => 'CAPTAIN\'S PARADISE',
                    'horse_style_name' => 'Captain\'s Paradise',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 9,
                    'dam_uid' => 60540,
                    'dam_name' => 'MINNIE HABIT',
                    'dam_style_name' => 'Minnie Habit',
                    'sire_uid' => 544976,
                    'sire_name' => 'ROCK OF GIBRALTAR',
                    'sire_style_name' => 'Rock Of Gibraltar',
                    'sire_of_dam_uid' => 301021,
                    'sire_of_dam_name' => 'HABITAT',
                    'sire_of_dam_style_name' => 'Habitat',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            7 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Not Sold',
                    'search_buyer_detail' => 'NOTSOLD',
                    'seller_name' => 'Mr G. Wilding from Athnid Stud',
                    'search_seller_name' => 'ATHNIDSTUD',
                    'price' => 19000,
                    'lot_no' => 26,
                    'lot_letter' => null,
                    'horse_uid' => 960387,
                    'horse_name' => 'PROPHETESS',
                    'horse_style_name' => 'Prophetess',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => 532087,
                    'dam_name' => 'BIBLE BOX',
                    'dam_style_name' => 'Bible Box',
                    'sire_uid' => 692355,
                    'sire_name' => 'EQUIANO',
                    'sire_style_name' => 'Equiano',
                    'sire_of_dam_uid' => 79943,
                    'sire_of_dam_name' => 'BIN AJWAAD',
                    'sire_of_dam_style_name' => 'Bin Ajwaad',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            8 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Philip Burns',
                    'search_buyer_detail' => 'PHILIPBURNS',
                    'seller_name' => 'Shiremark Barn Stables Ltd. from Attwater Racing Ltd.',
                    'search_seller_name' => 'ATTWATERRACINGLTD',
                    'price' => 7000,
                    'lot_no' => 746,
                    'lot_letter' => null,
                    'horse_uid' => 868839,
                    'horse_name' => 'EL TREN',
                    'horse_style_name' => 'El Tren',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'G',
                    'horse_age' => 5,
                    'dam_uid' => 868840,
                    'dam_name' => 'DHAMMA',
                    'dam_style_name' => 'Dhamma',
                    'sire_uid' => 104011,
                    'sire_name' => 'DANEHILL DANCER',
                    'sire_style_name' => 'Danehill Dancer',
                    'sire_of_dam_uid' => 304912,
                    'sire_of_dam_name' => 'BROAD BRUSH',
                    'sire_of_dam_style_name' => 'Broad Brush',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            9 => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Withdrawn',
                    'search_buyer_detail' => 'WITHDRAWN',
                    'seller_name' => 'From Baroda & Colbinstown Studs, Ireland',
                    'search_seller_name' => 'BARODACOLBINSTOWNSTUDS',
                    'price' => null,
                    'lot_no' => 19,
                    'lot_letter' => null,
                    'horse_uid' => 893718,
                    'horse_name' => 'CASSIS SUNSET',
                    'horse_style_name' => 'Cassis Sunset',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => 684107,
                    'dam_name' => 'SONIC NIGHT',
                    'dam_style_name' => 'Sonic Night',
                    'sire_uid' => 757547,
                    'sire_name' => 'RODERIC O\'CONNOR',
                    'sire_style_name' => 'Roderic O\'Connor',
                    'sire_of_dam_uid' => 301663,
                    'sire_of_dam_name' => 'NIGHT SHIFT',
                    'sire_of_dam_style_name' => 'Night Shift',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
        ];
    }
}
