<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Profile\Jockey\Horses;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\Profile\Jockey\Horses
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/profile/jockey/81166/horses/2014/GB/flat/aw';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Models\Bo\JockeyProfile\RaceInstance:393 ->getHorses()
            '8430c001ead77bf1027bd9360efd72c8' => [
                [
                    'races_number' => 5,
                    'place_1st_number' => 2,
                    'win_prize' => 17466.3,
                    'total_prize' => 21927.62,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 17466.3,
                    'net_total_prize_money' => 21927.62,
                    'stake' => 12.5,
                    'rpr' => 92,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 738474,
                    'horse_style_name' => 'The Lock Master',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 5,
                    'place_1st_number' => 1,
                    'win_prize' => 2587.6,
                    'total_prize' => 18877.2,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2587.6,
                    'net_total_prize_money' => 18877.2,
                    'stake' => -2.25,
                    'rpr' => 86,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 803859,
                    'horse_style_name' => 'Maggie Pink',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 2,
                    'win_prize' => 10350.4,
                    'total_prize' => 14566.9,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 10350.4,
                    'net_total_prize_money' => 14566.9,
                    'stake' => 16.0,
                    'rpr' => 94,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 795497,
                    'horse_style_name' => 'Villa Royale',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 7,
                    'place_1st_number' => 3,
                    'win_prize' => 9056.6,
                    'total_prize' => 11108.4,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 9056.6,
                    'net_total_prize_money' => 11108.4,
                    'stake' => 10.0,
                    'rpr' => 79,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 728594,
                    'horse_style_name' => 'Khajaaly',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 6,
                    'place_1st_number' => 2,
                    'win_prize' => 5822.1,
                    'total_prize' => 7782.1,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 5822.1,
                    'net_total_prize_money' => 7782.1,
                    'stake' => -0.375,
                    'rpr' => 81,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 787293,
                    'horse_style_name' => 'Mr Red Clubs',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 9,
                    'place_1st_number' => 2,
                    'win_prize' => 4528.3,
                    'total_prize' => 6693.25,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 4528.3,
                    'net_total_prize_money' => 6693.25,
                    'stake' => -5.217,
                    'rpr' => 70,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 783442,
                    'horse_style_name' => 'Arabian Flight',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 6,
                    'place_1st_number' => 2,
                    'win_prize' => 5314.4,
                    'total_prize' => 6232.03,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 5314.4,
                    'net_total_prize_money' => 6232.03,
                    'stake' => 8.5,
                    'rpr' => 80,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 833315,
                    'horse_style_name' => 'Guishan',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 1,
                    'win_prize' => 5175.2,
                    'total_prize' => 6072.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 5175.2,
                    'net_total_prize_money' => 6072.0,
                    'stake' => 1.25,
                    'rpr' => 95,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 773285,
                    'horse_style_name' => 'Shelford',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 5545.4,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 5545.4,
                    'stake' => -2.0,
                    'rpr' => 104,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 768102,
                    'horse_style_name' => 'Bancnuanaheireann',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 4851.75,
                    'total_prize' => 4851.75,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 4851.75,
                    'net_total_prize_money' => 4851.75,
                    'stake' => 3.5,
                    'rpr' => 75,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 839747,
                    'horse_style_name' => 'Bognor',
                    'country_origin_code' => 'USA',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 4690.02,
                    'total_prize' => 4690.02,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 4690.02,
                    'net_total_prize_money' => 4690.02,
                    'stake' => 1.5,
                    'rpr' => 95,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 813697,
                    'horse_style_name' => 'Pearl Nation',
                    'country_origin_code' => 'USA',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 1,
                    'win_prize' => 1940.7,
                    'total_prize' => 4377.75,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 1940.7,
                    'net_total_prize_money' => 4377.75,
                    'stake' => -0.25,
                    'rpr' => 71,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 820576,
                    'horse_style_name' => 'Queen Of Skies',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 1,
                    'win_prize' => 2587.6,
                    'total_prize' => 4271.1,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2587.6,
                    'net_total_prize_money' => 4271.1,
                    'stake' => 0.5,
                    'rpr' => 86,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 303550,
                    'horse_style_name' => 'Staff Sergeant',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 1,
                    'win_prize' => 3396.22,
                    'total_prize' => 3781.02,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 3396.22,
                    'net_total_prize_money' => 3781.02,
                    'stake' => 0.5,
                    'rpr' => 71,
                    'trainer_uid' => 13,
                    'trainer_style_name' => 'Mark Usher',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 857953,
                    'horse_style_name' => 'Spindle',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 3464.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 3464.0,
                    'stake' => -2.0,
                    'rpr' => 84,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 802922,
                    'horse_style_name' => 'Dewala',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 1,
                    'win_prize' => 2587.6,
                    'total_prize' => 2866.58,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2587.6,
                    'net_total_prize_money' => 2866.58,
                    'stake' => 3.5,
                    'rpr' => 61,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 827945,
                    'horse_style_name' => 'Hell Hath No Fury',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 2749.32,
                    'total_prize' => 2749.32,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2749.32,
                    'net_total_prize_money' => 2749.32,
                    'stake' => 2.25,
                    'rpr' => 84,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 760696,
                    'horse_style_name' => 'Jacobs Son',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 1,
                    'win_prize' => 1940.7,
                    'total_prize' => 2710.7,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 1940.7,
                    'net_total_prize_money' => 2710.7,
                    'stake' => 0.25,
                    'rpr' => 62,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 802751,
                    'horse_style_name' => 'Adili',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 1,
                    'win_prize' => 2264.15,
                    'total_prize' => 2600.85,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2264.15,
                    'net_total_prize_money' => 2600.85,
                    'stake' => 4.0,
                    'rpr' => 57,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 416145,
                    'horse_style_name' => 'Hidden Asset',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 1,
                    'win_prize' => 2385.95,
                    'total_prize' => 2385.95,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 2385.95,
                    'net_total_prize_money' => 2385.95,
                    'stake' => -0.25,
                    'rpr' => 73,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 827738,
                    'horse_style_name' => 'Ivy Port',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 4,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 2165.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 2165.5,
                    'stake' => -4.0,
                    'rpr' => 73,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 827488,
                    'horse_style_name' => 'Carlanda',
                    'country_origin_code' => 'FR',
                ],
                [
                    'races_number' => 7,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1972.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1972.5,
                    'stake' => -7.0,
                    'rpr' => 60,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 817811,
                    'horse_style_name' => 'Laughing Rock',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 6,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1955.15,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1955.15,
                    'stake' => -6.0,
                    'rpr' => 74,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 734966,
                    'horse_style_name' => 'Tartan Trip',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 1940.7,
                    'total_prize' => 1940.7,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 1940.7,
                    'net_total_prize_money' => 1940.7,
                    'stake' => 3.0,
                    'rpr' => 67,
                    'trainer_uid' => 13955,
                    'trainer_style_name' => 'Jamie Osborne',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 831473,
                    'horse_style_name' => 'Ain\'t No Surprise',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 1,
                    'win_prize' => 1940.7,
                    'total_prize' => 1940.7,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 1940.7,
                    'net_total_prize_money' => 1940.7,
                    'stake' => 1.75,
                    'rpr' => 71,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 823005,
                    'horse_style_name' => 'Katie Gale',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1888.73,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1888.73,
                    'stake' => -2.0,
                    'rpr' => 88,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 723196,
                    'horse_style_name' => 'Honoured',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1443.75,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1443.75,
                    'stake' => -1.0,
                    'rpr' => 81,
                    'trainer_uid' => 542,
                    'trainer_style_name' => 'David Barron',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 845234,
                    'horse_style_name' => 'Art Obsession',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1155.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1155.0,
                    'stake' => -3.0,
                    'rpr' => 53,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 801687,
                    'horse_style_name' => 'Dear Ben',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 1084.45,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 1084.45,
                    'stake' => -1.0,
                    'rpr' => 93,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 829122,
                    'horse_style_name' => 'The Great Gabrial',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 962.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 962.5,
                    'stake' => -1.0,
                    'rpr' => 71,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 784587,
                    'horse_style_name' => 'Favorite Girl',
                    'country_origin_code' => 'GER',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 962.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 962.5,
                    'stake' => -1.0,
                    'rpr' => 63,
                    'trainer_uid' => 3846,
                    'trainer_style_name' => 'David Evans',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 838253,
                    'horse_style_name' => 'Khee Society',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 962.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 962.5,
                    'stake' => -2.0,
                    'rpr' => 78,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 780853,
                    'horse_style_name' => 'Thorpe Bay',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 914.37,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 914.37,
                    'stake' => -3.0,
                    'rpr' => 80,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 689380,
                    'horse_style_name' => 'Tyfos',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 866.25,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 866.25,
                    'stake' => -1.0,
                    'rpr' => 75,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 818708,
                    'horse_style_name' => 'No Win No Fee',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 805.2,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 805.2,
                    'stake' => -1.0,
                    'rpr' => 73,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 811579,
                    'horse_style_name' => 'Shirley\'s Pride',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 770.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 770.0,
                    'stake' => -1.0,
                    'rpr' => 56,
                    'trainer_uid' => 3846,
                    'trainer_style_name' => 'David Evans',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 852486,
                    'horse_style_name' => 'Needs The Run',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 770.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 770.0,
                    'stake' => -1.0,
                    'rpr' => 69,
                    'trainer_uid' => 7968,
                    'trainer_style_name' => 'Philip McBride',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 847465,
                    'horse_style_name' => 'Old Town Boy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 721.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 721.5,
                    'stake' => -1.0,
                    'rpr' => 73,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 841526,
                    'horse_style_name' => 'Heska',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 704.55,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 704.55,
                    'stake' => -2.0,
                    'rpr' => 56,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 671891,
                    'horse_style_name' => 'Huzzah',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 697.45,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 697.45,
                    'stake' => -2.0,
                    'rpr' => 77,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 745007,
                    'horse_style_name' => 'Tappanappa',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 673.4,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 673.4,
                    'stake' => -2.0,
                    'rpr' => 52,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 844048,
                    'horse_style_name' => 'Nellies Quest',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 607.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 607.5,
                    'stake' => -1.0,
                    'rpr' => 95,
                    'trainer_uid' => 272,
                    'trainer_style_name' => 'Derek Haydn Jones',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 721466,
                    'horse_style_name' => 'Tinshu',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 577.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 577.5,
                    'stake' => -1.0,
                    'rpr' => 53,
                    'trainer_uid' => 9599,
                    'trainer_style_name' => 'S Donohoe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 825007,
                    'horse_style_name' => 'Calling You',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 402.8,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 402.8,
                    'stake' => -3.0,
                    'rpr' => 58,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 433977,
                    'horse_style_name' => 'Scamperdale',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 384.8,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 384.8,
                    'stake' => -1.0,
                    'rpr' => 73,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 791117,
                    'horse_style_name' => 'Goldstorm',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 384.8,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 384.8,
                    'stake' => -3.0,
                    'rpr' => 56,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 710469,
                    'horse_style_name' => 'Piccolo Express',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 352.45,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 352.45,
                    'stake' => -1.0,
                    'rpr' => 59,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 786739,
                    'horse_style_name' => 'Bitaphon',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 336.7,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 336.7,
                    'stake' => -1.0,
                    'rpr' => 43,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 809351,
                    'horse_style_name' => 'Lucy Bee',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 288.6,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 288.6,
                    'stake' => -2.0,
                    'rpr' => 63,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 736452,
                    'horse_style_name' => 'George Benjamin',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 288.6,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 288.6,
                    'stake' => -1.0,
                    'rpr' => 49,
                    'trainer_uid' => 7968,
                    'trainer_style_name' => 'Philip McBride',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 858689,
                    'horse_style_name' => 'Sky Steps',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 288.6,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 288.6,
                    'stake' => -1.0,
                    'rpr' => 53,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 851987,
                    'horse_style_name' => 'Sleet',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 282.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 282.0,
                    'stake' => -1.0,
                    'rpr' => 71,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 759218,
                    'horse_style_name' => 'Super Say',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 240.5,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 240.5,
                    'stake' => -3.0,
                    'rpr' => 31,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 832991,
                    'horse_style_name' => 'Luv U Honey',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 204.43,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 204.43,
                    'stake' => -1.0,
                    'rpr' => 74,
                    'trainer_uid' => 3415,
                    'trainer_style_name' => 'William Haggas',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 864693,
                    'horse_style_name' => 'Willow Creek',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 192.4,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 192.4,
                    'stake' => -1.0,
                    'rpr' => 43,
                    'trainer_uid' => 18622,
                    'trainer_style_name' => 'Alan McCabe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 846475,
                    'horse_style_name' => 'Molly Ahoy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 168.35,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 168.35,
                    'stake' => -2.0,
                    'rpr' => 61,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 788278,
                    'horse_style_name' => 'Hot Sugar',
                    'country_origin_code' => 'USA',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 144.3,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 144.3,
                    'stake' => -1.0,
                    'rpr' => 61,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 770931,
                    'horse_style_name' => 'Consistant',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 50,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 850305,
                    'horse_style_name' => 'Acton Gold',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 42,
                    'trainer_uid' => 8147,
                    'trainer_style_name' => 'David Nicholls',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 741596,
                    'horse_style_name' => 'Addictive Dream',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 48,
                    'trainer_uid' => 20005,
                    'trainer_style_name' => 'George Baker',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 754852,
                    'horse_style_name' => 'Ancient Greece',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -3.0,
                    'rpr' => 63,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 787750,
                    'horse_style_name' => 'Angel Cake',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 58,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 817434,
                    'horse_style_name' => 'Be Royale',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 21,
                    'trainer_uid' => 13,
                    'trainer_style_name' => 'Mark Usher',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 860259,
                    'horse_style_name' => 'Blue Burmese',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 40,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 842311,
                    'horse_style_name' => 'Bonnie Fairy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 57,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 842013,
                    'horse_style_name' => 'Buy Out Boy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 850199,
                    'horse_style_name' => 'Echologic',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 15660,
                    'trainer_style_name' => 'Richard Guest',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 838201,
                    'horse_style_name' => 'Eddiemaurice',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 39,
                    'trainer_uid' => 865,
                    'trainer_style_name' => 'Nigel Tinkler',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 834113,
                    'horse_style_name' => 'Elualla',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 9599,
                    'trainer_style_name' => 'S Donohoe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 843008,
                    'horse_style_name' => 'Erwhons Gift',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 69,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 752999,
                    'horse_style_name' => 'Expose',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 16,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 778984,
                    'horse_style_name' => 'Falcon\'s Reign',
                    'country_origin_code' => 'FR',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 25,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 821410,
                    'horse_style_name' => 'First Sargeant',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 12057,
                    'trainer_style_name' => 'Robert Cowell',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 840917,
                    'horse_style_name' => 'Hot Amber',
                    'country_origin_code' => 'USA',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 43,
                    'trainer_uid' => 3846,
                    'trainer_style_name' => 'David Evans',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 858327,
                    'horse_style_name' => 'Is She Any Good',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 56,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 828248,
                    'horse_style_name' => 'Jimmy Sewell',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 34,
                    'trainer_uid' => 18622,
                    'trainer_style_name' => 'Alan McCabe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 418375,
                    'horse_style_name' => 'Kai',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 42,
                    'trainer_uid' => 7108,
                    'trainer_style_name' => 'Brian Baugh',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 820314,
                    'horse_style_name' => 'Lexi\'s Beauty',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 3,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -3.0,
                    'rpr' => 63,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 788883,
                    'horse_style_name' => 'Lieutenant Dan',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 10,
                    'trainer_uid' => 3846,
                    'trainer_style_name' => 'David Evans',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 832980,
                    'horse_style_name' => 'Limegrove',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 24,
                    'trainer_uid' => 15660,
                    'trainer_style_name' => 'Richard Guest',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 788252,
                    'horse_style_name' => 'Lord Buffhead',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => null,
                    'trainer_uid' => 16133,
                    'trainer_style_name' => 'Alan Phillips',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 814576,
                    'horse_style_name' => 'My Stroppy Poppy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 39,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 855114,
                    'horse_style_name' => 'Navajo Dream',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 3846,
                    'trainer_style_name' => 'David Evans',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 841317,
                    'horse_style_name' => 'Ormer',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 10,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 797210,
                    'horse_style_name' => 'Our Ivor',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 70,
                    'trainer_uid' => 12600,
                    'trainer_style_name' => 'Brett Johnson',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 800492,
                    'horse_style_name' => 'Persepolis',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 26,
                    'trainer_uid' => 542,
                    'trainer_style_name' => 'David Barron',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 810655,
                    'horse_style_name' => 'Ptolemy',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 57,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 723529,
                    'horse_style_name' => 'Rasselas',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 2873,
                    'trainer_style_name' => 'Charles Smith',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 853826,
                    'horse_style_name' => 'Robbian',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 20,
                    'trainer_uid' => 13,
                    'trainer_style_name' => 'Mark Usher',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 858868,
                    'horse_style_name' => 'Sarah Catherine',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 850363,
                    'horse_style_name' => 'Silent Sam',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 50,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 817053,
                    'horse_style_name' => 'Sioux Chieftain',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 58,
                    'trainer_uid' => 552,
                    'trainer_style_name' => 'John Balding',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 805573,
                    'horse_style_name' => 'Sutton Sid',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 8,
                    'trainer_uid' => 865,
                    'trainer_style_name' => 'Nigel Tinkler',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 842578,
                    'horse_style_name' => 'Thomas Blossom',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 66,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 785084,
                    'horse_style_name' => 'Tidal\'s Baby',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 26,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 859437,
                    'horse_style_name' => 'Tobouggan Run',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 2,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -2.0,
                    'rpr' => 38,
                    'trainer_uid' => 10363,
                    'trainer_style_name' => 'Michael Appleby',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 762885,
                    'horse_style_name' => 'Tony Hollis',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 18622,
                    'trainer_style_name' => 'Alan McCabe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 813924,
                    'horse_style_name' => 'Una Bella Cosa',
                    'country_origin_code' => 'GB',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 0,
                    'trainer_uid' => 18622,
                    'trainer_style_name' => 'Alan McCabe',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 838195,
                    'horse_style_name' => 'Volodina',
                    'country_origin_code' => 'IRE',
                ],
                [
                    'races_number' => 1,
                    'place_1st_number' => 0,
                    'win_prize' => 0.0,
                    'total_prize' => 0.0,
                    'euro_win_prize' => 0.0,
                    'euro_total_prize' => 0.0,
                    'net_win_prize_money' => 0.0,
                    'net_total_prize_money' => 0.0,
                    'stake' => -1.0,
                    'rpr' => 30,
                    'trainer_uid' => 306,
                    'trainer_style_name' => 'Nigel Twiston-Davies',
                    'trainer_ptp_type_code' => 'N',
                    'horse_uid' => 734448,
                    'horse_style_name' => 'White Diamond',
                    'country_origin_code' => 'GB',
                ],
            ],

        ];
    }
}
