<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\OwnerGroups\Entries\OwnerGroupByDateRange;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\OwnerGroups\Entries\OwnerGroupByDateRange
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/owner-groups/5/entries?startDate=2021-02-12&endDate=2021-02-12';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\OwnerGroups\Entries:165 ->getData()
            'b189aae2b65cc2627afa2b8f6d27040f' => [
                0 => [
                    'race_instance_uid' => 775860,
                    'race_instance_title' => 'Racing Welfare Novice Stakes',
                    'race_datetime' => '2021-02-12 17:45:00',
                    'distance_yard' => 2200,
                    'race_status_code' => '4',
                    'local_meeting_race_datetime' => '2021-02-12 17:45:00',
                    'hours_difference' => 0,
                    'race_type_code' => 'X',
                    'race_surface' => 'Polytrack',
                    'race_class' => '5',
                    'course_uid' => 1083,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/DubaiRacing/HLS/DubaiRacing.m3u8',
                    'course_name' => 'Chelmsford (A.W)',
                    'diffusion_course_name' => 'CHELMSFORD (A.W)',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'GB',
                    'horse_uid' => 3161496,
                    'horse_name' => 'Symbolic Power',
                    'horse_country_origin_code' => 'GB',
                    'sire_uid' => 840020,
                    'sire_name' => 'Kingman',
                    'sire_country' => 'GB',
                    'dam_uid' => 847665,
                    'dam_name' => 'Grace And Favour',
                    'dam_country' => 'GB',
                    'trainer_uid' => 28338,
                    'trainer_name' => 'Charlie Appleby',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 49845,
                    'owner_name' => 'Godolphin',
                    'jockey_uid' => NULL,
                    'jockey_name' => NULL,
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                1 => [
                    'race_instance_uid' => 775860,
                    'race_instance_title' => 'Racing Welfare Novice Stakes',
                    'race_datetime' => '2021-02-12 17:45:00',
                    'distance_yard' => 2200,
                    'race_status_code' => '4',
                    'local_meeting_race_datetime' => '2021-02-12 17:45:00',
                    'hours_difference' => 0,
                    'race_type_code' => 'X',
                    'race_surface' => 'Polytrack',
                    'race_class' => '5',
                    'course_uid' => 1083,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/DubaiRacing/HLS/DubaiRacing.m3u8',
                    'course_name' => 'Chelmsford (A.W)',
                    'diffusion_course_name' => 'CHELMSFORD (A.W)',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'GB',
                    'horse_uid' => 3161496,
                    'horse_name' => 'Symbolic Power',
                    'horse_country_origin_code' => 'GB',
                    'sire_uid' => 840020,
                    'sire_name' => 'Kingman',
                    'sire_country' => 'GB',
                    'dam_uid' => 847665,
                    'dam_name' => 'Grace And Favour',
                    'dam_country' => 'GB',
                    'trainer_uid' => 28338,
                    'trainer_name' => 'Charlie Appleby',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 49845,
                    'owner_name' => 'Godolphin',
                    'jockey_uid' => NULL,
                    'jockey_name' => NULL,
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                2 => [
                    'race_instance_uid' => 775860,
                    'race_instance_title' => 'Racing Welfare Novice Stakes',
                    'race_datetime' => '2021-02-12 17:45:00',
                    'distance_yard' => 2200,
                    'race_status_code' => '4',
                    'local_meeting_race_datetime' => '2021-02-12 17:45:00',
                    'hours_difference' => 0,
                    'race_type_code' => 'X',
                    'race_surface' => 'Polytrack',
                    'race_class' => '5',
                    'course_uid' => 1083,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/DubaiRacing/HLS/DubaiRacing.m3u8',
                    'course_name' => 'Chelmsford (A.W)',
                    'diffusion_course_name' => 'CHELMSFORD (A.W)',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'GB',
                    'horse_uid' => 3171299,
                    'horse_name' => 'Royal Touch',
                    'horse_country_origin_code' => 'GB',
                    'sire_uid' => 589690,
                    'sire_name' => 'Dubawi',
                    'sire_country' => 'IRE',
                    'dam_uid' => 607272,
                    'dam_name' => 'Gonbarda',
                    'dam_country' => 'GER',
                    'trainer_uid' => 28338,
                    'trainer_name' => 'Charlie Appleby',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 49845,
                    'owner_name' => 'Godolphin',
                    'jockey_uid' => NULL,
                    'jockey_name' => NULL,
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                3 => [
                    'race_instance_uid' => 775860,
                    'race_instance_title' => 'Racing Welfare Novice Stakes',
                    'race_datetime' => '2021-02-12 17:45:00',
                    'distance_yard' => 2200,
                    'race_status_code' => '4',
                    'local_meeting_race_datetime' => '2021-02-12 17:45:00',
                    'hours_difference' => 0,
                    'race_type_code' => 'X',
                    'race_surface' => 'Polytrack',
                    'race_class' => '5',
                    'course_uid' => 1083,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/DubaiRacing/HLS/DubaiRacing.m3u8',
                    'course_name' => 'Chelmsford (A.W)',
                    'diffusion_course_name' => 'CHELMSFORD (A.W)',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'GB',
                    'horse_uid' => 3171299,
                    'horse_name' => 'Royal Touch',
                    'horse_country_origin_code' => 'GB',
                    'sire_uid' => 589690,
                    'sire_name' => 'Dubawi',
                    'sire_country' => 'IRE',
                    'dam_uid' => 607272,
                    'dam_name' => 'Gonbarda',
                    'dam_country' => 'GER',
                    'trainer_uid' => 28338,
                    'trainer_name' => 'Charlie Appleby',
                    'trainer_country_code' => 'GB',
                    'trainer_country_desc' => 'Great Britain',
                    'owner_uid' => 49845,
                    'owner_name' => 'Godolphin',
                    'jockey_uid' => NULL,
                    'jockey_name' => NULL,
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                4 => [
                    'race_instance_uid' => 778033,
                    'race_instance_title' => 'Maiden Special Weight (Maiden) (3yo) (Main Track) (Dirt)',
                    'race_datetime' => '2021-02-12 20:18:00',
                    'distance_yard' => 1540,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:18:00',
                    'hours_difference' => -5,
                    'race_type_code' => 'X',
                    'race_surface' => 'Dirt',
                    'race_class' => NULL,
                    'course_uid' => 724,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Tampa Bay Downs',
                    'diffusion_course_name' => 'TAMPA BAY DOWNS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3404042,
                    'horse_name' => 'Well Told',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 518730,
                    'sire_name' => 'More Than Ready',
                    'sire_country' => 'USA',
                    'dam_uid' => 839910,
                    'dam_name' => 'Spellbind',
                    'dam_country' => 'GB',
                    'trainer_uid' => 14480,
                    'trainer_name' => 'Eoin Harty',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 85983,
                    'jockey_name' => 'Alonso Quinonez',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                5 => [
                    'race_instance_uid' => 778033,
                    'race_instance_title' => 'Maiden Special Weight (Maiden) (3yo) (Main Track) (Dirt)',
                    'race_datetime' => '2021-02-12 20:18:00',
                    'distance_yard' => 1540,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:18:00',
                    'hours_difference' => -5,
                    'race_type_code' => 'X',
                    'race_surface' => 'Dirt',
                    'race_class' => NULL,
                    'course_uid' => 724,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Tampa Bay Downs',
                    'diffusion_course_name' => 'TAMPA BAY DOWNS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3404042,
                    'horse_name' => 'Well Told',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 518730,
                    'sire_name' => 'More Than Ready',
                    'sire_country' => 'USA',
                    'dam_uid' => 839910,
                    'dam_name' => 'Spellbind',
                    'dam_country' => 'GB',
                    'trainer_uid' => 14480,
                    'trainer_name' => 'Eoin Harty',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 85983,
                    'jockey_name' => 'Alonso Quinonez',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                6 => [
                    'race_instance_uid' => 777988,
                    'race_instance_title' => 'Allowance Optional Claiming Race (3yo) (Turf)',
                    'race_datetime' => '2021-02-12 21:25:00',
                    'distance_yard' => 1210,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:25:00',
                    'hours_difference' => -6,
                    'race_type_code' => 'F',
                    'race_surface' => 'Turf',
                    'race_class' => NULL,
                    'course_uid' => 742,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Fair Grounds',
                    'diffusion_course_name' => 'FAIR GROUNDS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3189639,
                    'horse_name' => 'Inner Ghost',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 584459,
                    'sire_name' => 'Ghostzapper',
                    'sire_country' => 'USA',
                    'dam_uid' => 889396,
                    'dam_name' => 'Dreamup',
                    'dam_country' => 'USA',
                    'trainer_uid' => 8863,
                    'trainer_name' => 'Michael Stidham',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 92805,
                    'jockey_name' => 'Brian Joseph Hernandez Jr',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                7 => [
                    'race_instance_uid' => 777988,
                    'race_instance_title' => 'Allowance Optional Claiming Race (3yo) (Turf)',
                    'race_datetime' => '2021-02-12 21:25:00',
                    'distance_yard' => 1210,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:25:00',
                    'hours_difference' => -6,
                    'race_type_code' => 'F',
                    'race_surface' => 'Turf',
                    'race_class' => NULL,
                    'course_uid' => 742,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Fair Grounds',
                    'diffusion_course_name' => 'FAIR GROUNDS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3189639,
                    'horse_name' => 'Inner Ghost',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 584459,
                    'sire_name' => 'Ghostzapper',
                    'sire_country' => 'USA',
                    'dam_uid' => 889396,
                    'dam_name' => 'Dreamup',
                    'dam_country' => 'USA',
                    'trainer_uid' => 8863,
                    'trainer_name' => 'Michael Stidham',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 92805,
                    'jockey_name' => 'Brian Joseph Hernandez Jr',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                8 => [
                    'race_instance_uid' => 777989,
                    'race_instance_title' => 'Maiden Special Weight (3yo Fillies) (Main Track) (Dirt)',
                    'race_datetime' => '2021-02-12 21:54:00',
                    'distance_yard' => 1870,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:54:00',
                    'hours_difference' => -6,
                    'race_type_code' => 'X',
                    'race_surface' => 'Dirt',
                    'race_class' => NULL,
                    'course_uid' => 742,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Fair Grounds',
                    'diffusion_course_name' => 'FAIR GROUNDS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3225175,
                    'horse_name' => 'Dottie',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 657574,
                    'sire_name' => 'Bernardini',
                    'sire_country' => 'USA',
                    'dam_uid' => 877267,
                    'dam_name' => 'Sweet Swingin',
                    'dam_country' => 'USA',
                    'trainer_uid' => 26181,
                    'trainer_name' => 'Brendan P Walsh',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 83381,
                    'jockey_name' => 'Florent Geroux',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
                9 => [
                    'race_instance_uid' => 777989,
                    'race_instance_title' => 'Maiden Special Weight (3yo Fillies) (Main Track) (Dirt)',
                    'race_datetime' => '2021-02-12 21:54:00',
                    'distance_yard' => 1870,
                    'race_status_code' => 'O',
                    'local_meeting_race_datetime' => '2021-02-12 15:54:00',
                    'hours_difference' => -6,
                    'race_type_code' => 'X',
                    'race_surface' => 'Dirt',
                    'race_class' => NULL,
                    'course_uid' => 742,
                    'CMS_element_contents' => 'http://94.56.35.252/live/localdisk/Yas/HLS/Yas.m3u8',
                    'course_name' => 'Fair Grounds',
                    'diffusion_course_name' => 'FAIR GROUNDS',
                    'race_group_code' => '0',
                    'race_group_desc' => 'Unknown',
                    'country_code' => 'USA',
                    'horse_uid' => 3225175,
                    'horse_name' => 'Dottie',
                    'horse_country_origin_code' => 'USA',
                    'sire_uid' => 657574,
                    'sire_name' => 'Bernardini',
                    'sire_country' => 'USA',
                    'dam_uid' => 877267,
                    'dam_name' => 'Sweet Swingin',
                    'dam_country' => 'USA',
                    'trainer_uid' => 26181,
                    'trainer_name' => 'Brendan P Walsh',
                    'trainer_country_code' => 'USA',
                    'trainer_country_desc' => 'U.S.A',
                    'owner_uid' => 97229,
                    'owner_name' => 'Godolphin Racing LLC',
                    'jockey_uid' => 83381,
                    'jockey_name' => 'Florent Geroux',
                    'forecast_odds_desc' => NULL,
                    'non_runner' => 'N',
                    'black_type' => 'N',
                    'owner_group_id' => 5,
                ],
            ],

            //Api\DataProvider\Bo\OwnerGroups\OwnerGroupsProvider:92 ->getBlackTypeRunners()
            '6962b3ed7d4b23acc1143cc1ec497554' => []
        ];
    }
}
