<?php

use Api\Input\Request\Horses\Bloodstock\SalesStatistics as Request;
use \Phalcon\Mvc\Model\Row\General;

return [
    [
        new Request\Vendors([5, '2016-07-06', '2016-07-08']),
        [
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Lee Woolams',
                    'search_buyer_detail' => 'LEEWOOLAMS',
                    'seller_name' => 'From Acorn Stud, Ireland',
                    'search_seller_name' => 'ACORNSTUD',
                    'price' => 2000,
                    'lot_no' => 44,
                    'lot_letter' => null,
                    'horse_uid' => 688534,
                    'horse_name' => 'IDONEA',
                    'horse_style_name' => 'Idonea',
                    'horse_first_colour_code' => 'CH',
                    'horse_sex' => 'M',
                    'horse_age' => 11,
                    'dam_uid' => 688526,
                    'dam_name' => 'IVASTAR',
                    'dam_style_name' => 'Ivastar',
                    'sire_uid' => 90597,
                    'sire_name' => 'SWAIN',
                    'sire_style_name' => 'Swain',
                    'sire_of_dam_uid' => 7365,
                    'sire_of_dam_name' => 'ALWASMI',
                    'sire_of_dam_style_name' => 'Alwasmi',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Not Sold',
                    'search_buyer_detail' => 'NOTSOLD',
                    'seller_name' => 'Oak Hill Stud from Acorn Stud, Ireland',
                    'search_seller_name' => 'ACORNSTUD',
                    'price' => 7800,
                    'lot_no' => 45,
                    'lot_letter' => null,
                    'horse_uid' => 887560,
                    'horse_name' => 'RIDE A RAINBOW',
                    'horse_style_name' => 'Ride A Rainbow',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 9,
                    'dam_uid' => 583914,
                    'dam_name' => 'CELTIC HEROINE',
                    'dam_style_name' => 'Celtic Heroine',
                    'sire_uid' => 303440,
                    'sire_name' => 'RAINBOW QUEST',
                    'sire_style_name' => 'Rainbow Quest',
                    'sire_of_dam_uid' => 76009,
                    'sire_of_dam_name' => 'HERNANDO',
                    'sire_of_dam_style_name' => 'Hernando',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Emerald Bloodstock',
                    'search_buyer_detail' => 'EMERALDBLOODSTOCK',
                    'seller_name' => 'From Aislabie Stud',
                    'search_seller_name' => 'AISLABIESTUD',
                    'price' => 12000,
                    'lot_no' => 33,
                    'lot_letter' => 'b',
                    'horse_uid' => 602951,
                    'horse_name' => 'PLAY BOUZOUKI',
                    'horse_style_name' => 'Play Bouzouki',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 15,
                    'dam_uid' => 447161,
                    'dam_name' => 'BALALAIKA',
                    'dam_style_name' => 'Balalaika',
                    'sire_uid' => 96463,
                    'sire_name' => 'HALLING',
                    'sire_style_name' => 'Halling',
                    'sire_of_dam_uid' => 463975,
                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                    'sire_of_dam_style_name' => 'Sadler\'s Wells',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Kaloni OE',
                    'search_buyer_detail' => 'KALONIOE',
                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                    'price' => 1000,
                    'lot_no' => 870,
                    'lot_letter' => null,
                    'horse_uid' => 877152,
                    'horse_name' => 'ACE REBEL',
                    'horse_style_name' => 'Ace Rebel',
                    'horse_first_colour_code' => 'CH',
                    'horse_sex' => 'C',
                    'horse_age' => 3,
                    'dam_uid' => 643008,
                    'dam_name' => 'QUADROPHENIA',
                    'dam_style_name' => 'Quadrophenia',
                    'sire_uid' => 448003,
                    'sire_name' => 'BAHAMIAN BOUNTY',
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_of_dam_uid' => 75847,
                    'sire_of_dam_name' => 'COLLEGE CHAPEL',
                    'sire_of_dam_style_name' => 'College Chapel',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Compas Equine',
                    'search_buyer_detail' => 'COMPASEQUINE',
                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                    'price' => 6500,
                    'lot_no' => 869,
                    'lot_letter' => null,
                    'horse_uid' => 877157,
                    'horse_name' => 'REBEL RAISER',
                    'horse_style_name' => 'Rebel Raiser',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'G',
                    'horse_age' => 3,
                    'dam_uid' => 486917,
                    'dam_name' => 'TRUMP STREET',
                    'dam_style_name' => 'Trump Street',
                    'sire_uid' => 579845,
                    'sire_name' => 'KHELEYF',
                    'sire_style_name' => 'Kheleyf',
                    'sire_of_dam_uid' => 84334,
                    'sire_of_dam_name' => 'FIRST TRUMP',
                    'sire_of_dam_style_name' => 'First Trump',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Vendor',
                    'search_buyer_detail' => 'VENDOR',
                    'seller_name' => 'Apple Tree Stud',
                    'search_seller_name' => 'APPLETREESTUD',
                    'price' => 40000,
                    'lot_no' => 93,
                    'lot_letter' => null,
                    'horse_uid' => null,
                    'horse_name' => 'EMPRESS ROCK',
                    'horse_style_name' => null,
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => null,
                    'dam_name' => 'ROMAN EMPRESS',
                    'dam_style_name' => null,
                    'sire_uid' => null,
                    'sire_name' => 'FASTNET ROCK',
                    'sire_style_name' => null,
                    'sire_of_dam_uid' => null,
                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                    'sire_of_dam_style_name' => null,
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Vendor',
                    'search_buyer_detail' => 'VENDOR',
                    'seller_name' => 'From Aston Mullins Stud',
                    'search_seller_name' => 'ASTONMULLINSSTUD',
                    'price' => 11000,
                    'lot_no' => 85,
                    'lot_letter' => null,
                    'horse_uid' => 724355,
                    'horse_name' => 'CAPTAIN\'S PARADISE',
                    'horse_style_name' => 'Captain\'s Paradise',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'M',
                    'horse_age' => 9,
                    'dam_uid' => 60540,
                    'dam_name' => 'MINNIE HABIT',
                    'dam_style_name' => 'Minnie Habit',
                    'sire_uid' => 544976,
                    'sire_name' => 'ROCK OF GIBRALTAR',
                    'sire_style_name' => 'Rock Of Gibraltar',
                    'sire_of_dam_uid' => 301021,
                    'sire_of_dam_name' => 'HABITAT',
                    'sire_of_dam_style_name' => 'Habitat',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Not Sold',
                    'search_buyer_detail' => 'NOTSOLD',
                    'seller_name' => 'Mr G. Wilding from Athnid Stud',
                    'search_seller_name' => 'ATHNIDSTUD',
                    'price' => 19000,
                    'lot_no' => 26,
                    'lot_letter' => null,
                    'horse_uid' => 960387,
                    'horse_name' => 'PROPHETESS',
                    'horse_style_name' => 'Prophetess',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => 532087,
                    'dam_name' => 'BIBLE BOX',
                    'dam_style_name' => 'Bible Box',
                    'sire_uid' => 692355,
                    'sire_name' => 'EQUIANO',
                    'sire_style_name' => 'Equiano',
                    'sire_of_dam_uid' => 79943,
                    'sire_of_dam_name' => 'BIN AJWAAD',
                    'sire_of_dam_style_name' => 'Bin Ajwaad',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  8 2016 12:00AM',
                    'buyer_detail' => 'Philip Burns',
                    'search_buyer_detail' => 'PHILIPBURNS',
                    'seller_name' => 'Shiremark Barn Stables Ltd. from Attwater Racing Ltd.',
                    'search_seller_name' => 'ATTWATERRACINGLTD',
                    'price' => 7000,
                    'lot_no' => 746,
                    'lot_letter' => null,
                    'horse_uid' => 868839,
                    'horse_name' => 'EL TREN',
                    'horse_style_name' => 'El Tren',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'G',
                    'horse_age' => 5,
                    'dam_uid' => 868840,
                    'dam_name' => 'DHAMMA',
                    'dam_style_name' => 'Dhamma',
                    'sire_uid' => 104011,
                    'sire_name' => 'DANEHILL DANCER',
                    'sire_style_name' => 'Danehill Dancer',
                    'sire_of_dam_uid' => 304912,
                    'sire_of_dam_name' => 'BROAD BRUSH',
                    'sire_of_dam_style_name' => 'Broad Brush',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
            General::createFromArray(
                [
                    'sale_date' => 'Jul  6 2016 12:00AM',
                    'buyer_detail' => 'Withdrawn',
                    'search_buyer_detail' => 'WITHDRAWN',
                    'seller_name' => 'From Baroda & Colbinstown Studs, Ireland',
                    'search_seller_name' => 'BARODACOLBINSTOWNSTUDS',
                    'price' => null,
                    'lot_no' => 19,
                    'lot_letter' => null,
                    'horse_uid' => 893718,
                    'horse_name' => 'CASSIS SUNSET',
                    'horse_style_name' => 'Cassis Sunset',
                    'horse_first_colour_code' => 'B',
                    'horse_sex' => 'F',
                    'horse_age' => 3,
                    'dam_uid' => 684107,
                    'dam_name' => 'SONIC NIGHT',
                    'dam_style_name' => 'Sonic Night',
                    'sire_uid' => 757547,
                    'sire_name' => 'RODERIC O\'CONNOR',
                    'sire_style_name' => 'Roderic O\'Connor',
                    'sire_of_dam_uid' => 301663,
                    'sire_of_dam_name' => 'NIGHT SHIFT',
                    'sire_of_dam_style_name' => 'Night Shift',
                    'cur_code' => 'GBG',
                    'currency_code' => 'GNS',
                    'exchange_rate' => 0.95238,
                ]
            ),
        ],
        (Object)[
            'overall' => General::createFromArray(
                [
                    'seller_name' => null,
                    'search_seller_name' => null,
                    'median' => 6500,
                    'price_average' => 5700,
                    'price_max' => 12000,
                    'price_min' => 1000,
                    'price_total' => 28500,
                    'price_count' => 5,
                    'price_top' => 0,
                    'prices' => [
                        0 => 2000,
                        1 => 12000,
                        2 => 1000,
                        3 => 6500,
                        4 => 7000,
                    ],
                    'sales_count' => 5,
                    'sold' => false,
                    'offered_count' => 9,
                    'buyers_count' => 10,
                    'withdraws_count' => 1,
                    'total_count' => 10,
                    'cur_code' => null,
                    'entities' => [
                    ],
                ]
            ),
            'vendors' => [
                General::createFromArray(
                    [
                        'seller_name' => 'From Aislabie Stud',
                        'search_seller_name' => 'AISLABIESTUD',
                        'median' => 12000,
                        'price_average' => 12000,
                        'price_max' => 12000,
                        'price_min' => 12000,
                        'price_total' => 12000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            0 => 12000,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 33,
                                    'lot_letter' => 'b',
                                    'horse_uid' => 602951,
                                    'horse_style_name' => 'Play Bouzouki',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'M',
                                    'horse_age' => 15,
                                    'sire_uid' => 96463,
                                    'sire_style_name' => 'Halling',
                                    'dam_uid' => 447161,
                                    'dam_style_name' => 'Balalaika',
                                    'sire_of_dam_uid' => 463975,
                                    'sire_of_dam_style_name' => 'Sadler\'s Wells',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 12000,
                                    'price_min' => 12000,
                                    'price_total' => 12000,
                                    'price_count' => 1,
                                    'price_top' => 0,
                                    'prices' => [
                                        0 => 12000,
                                    ],
                                    'sales_count' => 1,
                                    'sold' => true,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'From Aislabie Stud',
                                    'search_seller_name' => 'AISLABIESTUD',
                                    'price' => 12000,
                                    'horse_name' => 'PLAY BOUZOUKI',
                                    'sire_name' => 'HALLING',
                                    'dam_name' => 'BALALAIKA',
                                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 12000,
                        'horse_sex' => 'M',
                        'horse_age' => 15,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 33,
                        'lot_letter' => 'b',
                        'horse_uid' => 602951,
                        'horse_name' => 'PLAY BOUZOUKI',
                        'horse_style_name' => 'Play Bouzouki',
                        'sire_uid' => 96463,
                        'sire_name' => 'HALLING',
                        'sire_style_name' => 'Halling',
                        'dam_uid' => 447161,
                        'dam_name' => 'BALALAIKA',
                        'dam_style_name' => 'Balalaika',
                        'sire_of_dam_uid' => 463975,
                        'sire_of_dam_name' => 'SADLER\'S WELLS',
                        'sire_of_dam_style_name' => 'Sadler\'s Wells',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                        'search_seller_name' => 'ALBERTHOUSESTABLES',
                        'median' => 3750,
                        'price_average' => 3750,
                        'price_max' => 6500,
                        'price_min' => 1000,
                        'price_total' => 7500,
                        'price_count' => 2,
                        'price_top' => 0,
                        'prices' => [
                            0 => 1000,
                            1 => 6500,
                        ],
                        'sales_count' => 2,
                        'sold' => true,
                        'offered_count' => 2,
                        'buyers_count' => 2,
                        'withdraws_count' => 0,
                        'total_count' => 2,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 869,
                                    'lot_letter' => null,
                                    'horse_uid' => 877157,
                                    'horse_style_name' => 'Rebel Raiser',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'G',
                                    'horse_age' => 3,
                                    'sire_uid' => 579845,
                                    'sire_style_name' => 'Kheleyf',
                                    'dam_uid' => 486917,
                                    'dam_style_name' => 'Trump Street',
                                    'sire_of_dam_uid' => 84334,
                                    'sire_of_dam_style_name' => 'First Trump',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 6500,
                                    'price_min' => 6500,
                                    'price_total' => 6500,
                                    'price_count' => 1,
                                    'price_top' => 0,
                                    'prices' => [
                                        0 => 6500,
                                    ],
                                    'sales_count' => 1,
                                    'sold' => true,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                                    'price' => 6500,
                                    'horse_name' => 'REBEL RAISER',
                                    'sire_name' => 'KHELEYF',
                                    'dam_name' => 'TRUMP STREET',
                                    'sire_of_dam_name' => 'FIRST TRUMP',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                            1 => General::createFromArray(
                                [
                                    'lot_no' => 870,
                                    'lot_letter' => null,
                                    'horse_uid' => 877152,
                                    'horse_style_name' => 'Ace Rebel',
                                    'horse_first_colour_code' => 'CH',
                                    'horse_sex' => 'C',
                                    'horse_age' => 3,
                                    'sire_uid' => 448003,
                                    'sire_style_name' => 'Bahamian Bounty',
                                    'dam_uid' => 643008,
                                    'dam_style_name' => 'Quadrophenia',
                                    'sire_of_dam_uid' => 75847,
                                    'sire_of_dam_style_name' => 'College Chapel',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 1000,
                                    'price_min' => 1000,
                                    'price_total' => 1000,
                                    'price_count' => 1,
                                    'price_top' => 0,
                                    'prices' => [
                                        0 => 1000,
                                    ],
                                    'sales_count' => 1,
                                    'sold' => true,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'a Partnership from Albert House Stables (R. Spencer)',
                                    'search_seller_name' => 'ALBERTHOUSESTABLES',
                                    'price' => 1000,
                                    'horse_name' => 'ACE REBEL',
                                    'sire_name' => 'BAHAMIAN BOUNTY',
                                    'dam_name' => 'QUADROPHENIA',
                                    'sire_of_dam_name' => 'COLLEGE CHAPEL',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 6500,
                        'horse_sex' => 'G',
                        'horse_age' => 3,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 869,
                        'lot_letter' => null,
                        'horse_uid' => 877157,
                        'horse_name' => 'REBEL RAISER',
                        'horse_style_name' => 'Rebel Raiser',
                        'sire_uid' => 579845,
                        'sire_name' => 'KHELEYF',
                        'sire_style_name' => 'Kheleyf',
                        'dam_uid' => 486917,
                        'dam_name' => 'TRUMP STREET',
                        'dam_style_name' => 'Trump Street',
                        'sire_of_dam_uid' => 84334,
                        'sire_of_dam_name' => 'FIRST TRUMP',
                        'sire_of_dam_style_name' => 'First Trump',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'Shiremark Barn Stables Ltd. from Attwater Racing Ltd.',
                        'search_seller_name' => 'ATTWATERRACINGLTD',
                        'median' => 7000,
                        'price_average' => 7000,
                        'price_max' => 7000,
                        'price_min' => 7000,
                        'price_total' => 7000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            0 => 7000,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 746,
                                    'lot_letter' => null,
                                    'horse_uid' => 868839,
                                    'horse_style_name' => 'El Tren',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'G',
                                    'horse_age' => 5,
                                    'sire_uid' => 104011,
                                    'sire_style_name' => 'Danehill Dancer',
                                    'dam_uid' => 868840,
                                    'dam_style_name' => 'Dhamma',
                                    'sire_of_dam_uid' => 304912,
                                    'sire_of_dam_style_name' => 'Broad Brush',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 7000,
                                    'price_min' => 7000,
                                    'price_total' => 7000,
                                    'price_count' => 1,
                                    'price_top' => 0,
                                    'prices' => [
                                        0 => 7000,
                                    ],
                                    'sales_count' => 1,
                                    'sold' => true,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'Shiremark Barn Stables Ltd. from Attwater Racing Ltd.',
                                    'search_seller_name' => 'ATTWATERRACINGLTD',
                                    'price' => 7000,
                                    'horse_name' => 'EL TREN',
                                    'sire_name' => 'DANEHILL DANCER',
                                    'dam_name' => 'DHAMMA',
                                    'sire_of_dam_name' => 'BROAD BRUSH',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 7000,
                        'horse_sex' => 'G',
                        'horse_age' => 5,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 746,
                        'lot_letter' => null,
                        'horse_uid' => 868839,
                        'horse_name' => 'EL TREN',
                        'horse_style_name' => 'El Tren',
                        'sire_uid' => 104011,
                        'sire_name' => 'DANEHILL DANCER',
                        'sire_style_name' => 'Danehill Dancer',
                        'dam_uid' => 868840,
                        'dam_name' => 'DHAMMA',
                        'dam_style_name' => 'Dhamma',
                        'sire_of_dam_uid' => 304912,
                        'sire_of_dam_name' => 'BROAD BRUSH',
                        'sire_of_dam_style_name' => 'Broad Brush',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'Oak Hill Stud from Acorn Stud, Ireland',
                        'search_seller_name' => 'ACORNSTUD',
                        'median' => 2000,
                        'price_average' => 2000,
                        'price_max' => 2000,
                        'price_min' => 2000,
                        'price_total' => 2000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            0 => 2000,
                        ],
                        'sales_count' => 1,
                        'sold' => false,
                        'offered_count' => 2,
                        'buyers_count' => 2,
                        'withdraws_count' => 0,
                        'total_count' => 2,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 44,
                                    'lot_letter' => null,
                                    'horse_uid' => 688534,
                                    'horse_style_name' => 'Idonea',
                                    'horse_first_colour_code' => 'CH',
                                    'horse_sex' => 'M',
                                    'horse_age' => 11,
                                    'sire_uid' => 90597,
                                    'sire_style_name' => 'Swain',
                                    'dam_uid' => 688526,
                                    'dam_style_name' => 'Ivastar',
                                    'sire_of_dam_uid' => 7365,
                                    'sire_of_dam_style_name' => 'Alwasmi',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 2000,
                                    'price_min' => 2000,
                                    'price_total' => 2000,
                                    'price_count' => 1,
                                    'price_top' => 0,
                                    'prices' => [
                                        0 => 2000,
                                    ],
                                    'sales_count' => 1,
                                    'sold' => true,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'From Acorn Stud, Ireland',
                                    'search_seller_name' => 'ACORNSTUD',
                                    'price' => 2000,
                                    'horse_name' => 'IDONEA',
                                    'sire_name' => 'SWAIN',
                                    'dam_name' => 'IVASTAR',
                                    'sire_of_dam_name' => 'ALWASMI',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                            1 => General::createFromArray(
                                [
                                    'lot_no' => 45,
                                    'lot_letter' => null,
                                    'horse_uid' => 887560,
                                    'horse_style_name' => 'Ride A Rainbow',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'M',
                                    'horse_age' => 9,
                                    'sire_uid' => 303440,
                                    'sire_style_name' => 'Rainbow Quest',
                                    'dam_uid' => 583914,
                                    'dam_style_name' => 'Celtic Heroine',
                                    'sire_of_dam_uid' => 76009,
                                    'sire_of_dam_style_name' => 'Hernando',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 0,
                                    'price_min' => 600000000,
                                    'price_total' => 0,
                                    'price_count' => 0,
                                    'price_top' => 0,
                                    'prices' => [
                                    ],
                                    'sales_count' => 0,
                                    'sold' => false,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'Oak Hill Stud from Acorn Stud, Ireland',
                                    'search_seller_name' => 'ACORNSTUD',
                                    'price' => 7800,
                                    'horse_name' => 'RIDE A RAINBOW',
                                    'sire_name' => 'RAINBOW QUEST',
                                    'dam_name' => 'CELTIC HEROINE',
                                    'sire_of_dam_name' => 'HERNANDO',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 7800,
                        'horse_sex' => 'M',
                        'horse_age' => 9,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 45,
                        'lot_letter' => null,
                        'horse_uid' => 887560,
                        'horse_name' => 'RIDE A RAINBOW',
                        'horse_style_name' => 'Ride A Rainbow',
                        'sire_uid' => 303440,
                        'sire_name' => 'RAINBOW QUEST',
                        'sire_style_name' => 'Rainbow Quest',
                        'dam_uid' => 583914,
                        'dam_name' => 'CELTIC HEROINE',
                        'dam_style_name' => 'Celtic Heroine',
                        'sire_of_dam_uid' => 76009,
                        'sire_of_dam_name' => 'HERNANDO',
                        'sire_of_dam_style_name' => 'Hernando',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'Apple Tree Stud',
                        'search_seller_name' => 'APPLETREESTUD',
                        'median' => null,
                        'price_average' => null,
                        'price_max' => null,
                        'price_min' => null,
                        'price_total' => 0,
                        'price_count' => 0,
                        'price_top' => 0,
                        'prices' => [
                        ],
                        'sales_count' => 0,
                        'sold' => false,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 93,
                                    'lot_letter' => null,
                                    'horse_uid' => null,
                                    'horse_style_name' => null,
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'F',
                                    'horse_age' => 3,
                                    'sire_uid' => null,
                                    'sire_style_name' => null,
                                    'dam_uid' => null,
                                    'dam_style_name' => null,
                                    'sire_of_dam_uid' => null,
                                    'sire_of_dam_style_name' => null,
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 0,
                                    'price_min' => 600000000,
                                    'price_total' => 0,
                                    'price_count' => 0,
                                    'price_top' => 0,
                                    'prices' => [
                                    ],
                                    'sales_count' => 0,
                                    'sold' => false,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'Apple Tree Stud',
                                    'search_seller_name' => 'APPLETREESTUD',
                                    'price' => 40000,
                                    'horse_name' => 'EMPRESS ROCK',
                                    'sire_name' => 'FASTNET ROCK',
                                    'dam_name' => 'ROMAN EMPRESS',
                                    'sire_of_dam_name' => 'SADLER\'S WELLS',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 40000,
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 93,
                        'lot_letter' => null,
                        'horse_uid' => null,
                        'horse_name' => 'EMPRESS ROCK',
                        'horse_style_name' => null,
                        'sire_uid' => null,
                        'sire_name' => 'FASTNET ROCK',
                        'sire_style_name' => null,
                        'dam_uid' => null,
                        'dam_name' => 'ROMAN EMPRESS',
                        'dam_style_name' => null,
                        'sire_of_dam_uid' => null,
                        'sire_of_dam_name' => 'SADLER\'S WELLS',
                        'sire_of_dam_style_name' => null,
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'From Aston Mullins Stud',
                        'search_seller_name' => 'ASTONMULLINSSTUD',
                        'median' => null,
                        'price_average' => null,
                        'price_max' => null,
                        'price_min' => null,
                        'price_total' => 0,
                        'price_count' => 0,
                        'price_top' => 0,
                        'prices' => [
                        ],
                        'sales_count' => 0,
                        'sold' => false,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 85,
                                    'lot_letter' => null,
                                    'horse_uid' => 724355,
                                    'horse_style_name' => 'Captain\'s Paradise',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'M',
                                    'horse_age' => 9,
                                    'sire_uid' => 544976,
                                    'sire_style_name' => 'Rock Of Gibraltar',
                                    'dam_uid' => 60540,
                                    'dam_style_name' => 'Minnie Habit',
                                    'sire_of_dam_uid' => 301021,
                                    'sire_of_dam_style_name' => 'Habitat',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 0,
                                    'price_min' => 600000000,
                                    'price_total' => 0,
                                    'price_count' => 0,
                                    'price_top' => 0,
                                    'prices' => [
                                    ],
                                    'sales_count' => 0,
                                    'sold' => false,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'From Aston Mullins Stud',
                                    'search_seller_name' => 'ASTONMULLINSSTUD',
                                    'price' => 11000,
                                    'horse_name' => 'CAPTAIN\'S PARADISE',
                                    'sire_name' => 'ROCK OF GIBRALTAR',
                                    'dam_name' => 'MINNIE HABIT',
                                    'sire_of_dam_name' => 'HABITAT',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 11000,
                        'horse_sex' => 'M',
                        'horse_age' => 9,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 85,
                        'lot_letter' => null,
                        'horse_uid' => 724355,
                        'horse_name' => 'CAPTAIN\'S PARADISE',
                        'horse_style_name' => 'Captain\'s Paradise',
                        'sire_uid' => 544976,
                        'sire_name' => 'ROCK OF GIBRALTAR',
                        'sire_style_name' => 'Rock Of Gibraltar',
                        'dam_uid' => 60540,
                        'dam_name' => 'MINNIE HABIT',
                        'dam_style_name' => 'Minnie Habit',
                        'sire_of_dam_uid' => 301021,
                        'sire_of_dam_name' => 'HABITAT',
                        'sire_of_dam_style_name' => 'Habitat',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'Mr G. Wilding from Athnid Stud',
                        'search_seller_name' => 'ATHNIDSTUD',
                        'median' => null,
                        'price_average' => null,
                        'price_max' => null,
                        'price_min' => null,
                        'price_total' => 0,
                        'price_count' => 0,
                        'price_top' => 0,
                        'prices' => [
                        ],
                        'sales_count' => 0,
                        'sold' => false,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 26,
                                    'lot_letter' => null,
                                    'horse_uid' => 960387,
                                    'horse_style_name' => 'Prophetess',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'F',
                                    'horse_age' => 3,
                                    'sire_uid' => 692355,
                                    'sire_style_name' => 'Equiano',
                                    'dam_uid' => 532087,
                                    'dam_style_name' => 'Bible Box',
                                    'sire_of_dam_uid' => 79943,
                                    'sire_of_dam_style_name' => 'Bin Ajwaad',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 0,
                                    'price_min' => 600000000,
                                    'price_total' => 0,
                                    'price_count' => 0,
                                    'price_top' => 0,
                                    'prices' => [
                                    ],
                                    'sales_count' => 0,
                                    'sold' => false,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 0,
                                    'total_count' => 1,
                                    'seller_name' => 'Mr G. Wilding from Athnid Stud',
                                    'search_seller_name' => 'ATHNIDSTUD',
                                    'price' => 19000,
                                    'horse_name' => 'PROPHETESS',
                                    'sire_name' => 'EQUIANO',
                                    'dam_name' => 'BIBLE BOX',
                                    'sire_of_dam_name' => 'BIN AJWAAD',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => 19000,
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 26,
                        'lot_letter' => null,
                        'horse_uid' => 960387,
                        'horse_name' => 'PROPHETESS',
                        'horse_style_name' => 'Prophetess',
                        'sire_uid' => 692355,
                        'sire_name' => 'EQUIANO',
                        'sire_style_name' => 'Equiano',
                        'dam_uid' => 532087,
                        'dam_name' => 'BIBLE BOX',
                        'dam_style_name' => 'Bible Box',
                        'sire_of_dam_uid' => 79943,
                        'sire_of_dam_name' => 'BIN AJWAAD',
                        'sire_of_dam_style_name' => 'Bin Ajwaad',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
                General::createFromArray(
                    [
                        'seller_name' => 'From Baroda & Colbinstown Studs, Ireland',
                        'search_seller_name' => 'BARODACOLBINSTOWNSTUDS',
                        'median' => null,
                        'price_average' => null,
                        'price_max' => null,
                        'price_min' => null,
                        'price_total' => 0,
                        'price_count' => 0,
                        'price_top' => 0,
                        'prices' => [
                        ],
                        'sales_count' => 0,
                        'sold' => false,
                        'offered_count' => 0,
                        'buyers_count' => 1,
                        'withdraws_count' => 1,
                        'total_count' => 1,
                        'cur_code' => 'GBG',
                        'entities' => [
                            General::createFromArray(
                                [
                                    'lot_no' => 19,
                                    'lot_letter' => null,
                                    'horse_uid' => 893718,
                                    'horse_style_name' => 'Cassis Sunset',
                                    'horse_first_colour_code' => 'B',
                                    'horse_sex' => 'F',
                                    'horse_age' => 3,
                                    'sire_uid' => 757547,
                                    'sire_style_name' => 'Roderic O\'Connor',
                                    'dam_uid' => 684107,
                                    'dam_style_name' => 'Sonic Night',
                                    'sire_of_dam_uid' => 301663,
                                    'sire_of_dam_style_name' => 'Night Shift',
                                    'median' => 0,
                                    'price_average' => 0,
                                    'price_max' => 0,
                                    'price_min' => 600000000,
                                    'price_total' => 0,
                                    'price_count' => 0,
                                    'price_top' => 0,
                                    'prices' => [
                                    ],
                                    'sales_count' => 0,
                                    'sold' => false,
                                    'offered_count' => 0,
                                    'buyers_count' => 1,
                                    'withdraws_count' => 1,
                                    'total_count' => 1,
                                    'seller_name' => 'From Baroda & Colbinstown Studs, Ireland',
                                    'search_seller_name' => 'BARODACOLBINSTOWNSTUDS',
                                    'price' => null,
                                    'horse_name' => 'CASSIS SUNSET',
                                    'sire_name' => 'RODERIC O\'CONNOR',
                                    'dam_name' => 'SONIC NIGHT',
                                    'sire_of_dam_name' => 'NIGHT SHIFT',
                                    'exchange_rate' => 0.95238,
                                    'currency_code' => 'GNS',
                                    'cur_code' => 'GBG',
                                ]
                            ),
                        ],
                        'price' => null,
                        'horse_sex' => 'F',
                        'horse_age' => 3,
                        'horse_first_colour_code' => 'B',
                        'lot_no' => 19,
                        'lot_letter' => null,
                        'horse_uid' => 893718,
                        'horse_name' => 'CASSIS SUNSET',
                        'horse_style_name' => 'Cassis Sunset',
                        'sire_uid' => 757547,
                        'sire_name' => 'RODERIC O\'CONNOR',
                        'sire_style_name' => 'Roderic O\'Connor',
                        'dam_uid' => 684107,
                        'dam_name' => 'SONIC NIGHT',
                        'dam_style_name' => 'Sonic Night',
                        'sire_of_dam_uid' => 301663,
                        'sire_of_dam_name' => 'NIGHT SHIFT',
                        'sire_of_dam_style_name' => 'Night Shift',
                        'exchange_rate' => 0.95238,
                        'currency_code' => 'GNS',
                    ]
                ),
            ],
        ]
    ]
];
