<?php

use Api\Input\Request\Horses\Bloodstock\SalesStatistics\Sires as Request;

return [
    [
        new Request([5, '2016-07-08', '2016-07-08'], []),
        [
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ACCLAMATION',
                    'sire_uid' => 541314,
                    'sire_style_name' => 'Acclamation',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => null,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ACCLAMATION',
                    'sire_uid' => 541314,
                    'sire_style_name' => 'Acclamation',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => null,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ACCLAMATION',
                    'sire_uid' => 541314,
                    'sire_style_name' => 'Acclamation',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Isabell Kreger',
                    'price' => 2500,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ALFRED NOBEL',
                    'sire_uid' => 731600,
                    'sire_style_name' => 'Alfred Nobel',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Karl Burke',
                    'price' => 21000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ALFRED NOBEL',
                    'sire_uid' => 731600,
                    'sire_style_name' => 'Alfred Nobel',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Nicholas Caullery',
                    'price' => 9000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ALHAARTH',
                    'sire_uid' => 99826,
                    'sire_style_name' => 'Alhaarth',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Kenneth Slack',
                    'price' => 4000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'APPROVE',
                    'sire_uid' => 758138,
                    'sire_style_name' => 'Approve',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => null,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ARCANO',
                    'sire_uid' => 733706,
                    'sire_style_name' => 'Arcano',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Hazzaa Alzamay',
                    'price' => 1500,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ARCANO',
                    'sire_uid' => 733706,
                    'sire_style_name' => 'Arcano',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => null,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ARCHIPENKO',
                    'sire_uid' => 660521,
                    'sire_style_name' => 'Archipenko',
                    'sire_country_origin_code' => 'USA',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Michael Blanshard Racing',
                    'price' => 8000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'ARCHIPENKO',
                    'sire_uid' => 660521,
                    'sire_style_name' => 'Archipenko',
                    'sire_country_origin_code' => 'USA',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => null,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'AZAMOUR',
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Oliver St Lawrence Bloodstock',
                    'price' => 6000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'AZAMOUR',
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'BBA Ireland',
                    'price' => 9000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'AZAMOUR',
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Charlie Mann',
                    'price' => 8000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'AZAMOUR',
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Derek Shaw Racing',
                    'price' => 22000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'BAHAMIAN BOUNTY',
                    'sire_uid' => 448003,
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Kaloni OE',
                    'price' => 1000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'BAHAMIAN BOUNTY',
                    'sire_uid' => 448003,
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Jim Culloty',
                    'price' => 4000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'BAHAMIAN BOUNTY',
                    'sire_uid' => 448003,
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Mark Johnston Racing',
                    'price' => 14000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'BATED BREATH',
                    'sire_uid' => 739856,
                    'sire_style_name' => 'Bated Breath',
                    'sire_country_origin_code' => 'GB',
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Tim Lane',
                    'price' => 65000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
            \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sale_year' => 2016,
                    'sire_name' => 'BERNSTEIN',
                    'sire_uid' => 511841,
                    'sire_style_name' => 'Bernstein',
                    'sire_country_origin_code' => 'USA',
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Colm Sharkey,Agent',
                    'price' => 6500,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                ]
            ),
        ],
        [
            'overall' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                [
                    'sire_uid' => null,
                    'sire_name' => null,
                    'sire_style_name' => null,
                    'median' => 8000,
                    'price_average' => 12100,
                    'price_max' => 65000,
                    'price_min' => 1000,
                    'price_total' => 181500,
                    'price_count' => 15,
                    'price_top' => 0,
                    'prices' => [
                        2500,
                        21000,
                        9000,
                        4000,
                        1500,
                        8000,
                        6000,
                        9000,
                        8000,
                        22000,
                        1000,
                        4000,
                        14000,
                        65000,
                        6500,
                    ],
                    'sales_count' => 15,
                    'sold' => true,
                    'offered_count' => 15,
                    'buyers_count' => 20,
                    'withdraws_count' => 5,
                    'total_count' => 20,
                    'cur_code' => null,
                    'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                        [
                            'median' => 8000,
                            'price_average' => 9777.78,
                            'price_max' => 22000,
                            'price_min' => 1000,
                            'price_total' => 88000,
                            'price_count' => 9,
                            'price_top' => 0,
                            'prices' => [
                                2500,
                                21000,
                                9000,
                                8000,
                                22000,
                                1000,
                                4000,
                                14000,
                                6500,
                            ],
                            'sales_count' => 9,
                            'sold' => true,
                            'offered_count' => 9,
                            'buyers_count' => 14,
                            'withdraws_count' => 5,
                            'total_count' => 14,
                            'sale_year' => "overall",
                        ]
                    ),
                    'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                        [
                            'median' => 7000,
                            'price_average' => 15583.33,
                            'price_max' => 65000,
                            'price_min' => 1500,
                            'price_total' => 93500,
                            'price_count' => 6,
                            'price_top' => 0,
                            'prices' => [
                                4000,
                                1500,
                                8000,
                                6000,
                                9000,
                                65000,
                            ],
                            'sales_count' => 6,
                            'sold' => true,
                            'offered_count' => 6,
                            'buyers_count' => 6,
                            'withdraws_count' => 0,
                            'total_count' => 6,
                            'sale_year' => "overall",
                        ]
                    ),
                    'sale_year' => "overall",
                ]
            ),
            'sires' => [
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 541314,
                        'sire_name' => "ACCLAMATION",
                        'sire_style_name' => "Acclamation",
                        'median' => 2500,
                        'price_average' => 2500,
                        'price_max' => 2500,
                        'price_min' => 2500,
                        'price_total' => 2500,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            2500,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 3,
                        'withdraws_count' => 2,
                        'total_count' => 3,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 2500,
                                'price_average' => 2500,
                                'price_max' => 2500,
                                'price_min' => 2500,
                                'price_total' => 2500,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    2500,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 3,
                                'withdraws_count' => 2,
                                'total_count' => 3,
                                'sire_uid' => 541314,
                                'sire_name' => "ACCLAMATION",
                                'sire_style_name' => "Acclamation",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Isabell Kreger",
                                'price' => 2500,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => null,
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Isabell Kreger",
                        'price' => 2500,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 731600,
                        'sire_name' => "ALFRED NOBEL",
                        'sire_style_name' => "Alfred Nobel",
                        'median' => 15000,
                        'price_average' => 15000,
                        'price_max' => 21000,
                        'price_min' => 9000,
                        'price_total' => 30000,
                        'price_count' => 2,
                        'price_top' => 0,
                        'prices' => [
                            21000,
                            9000,
                        ],
                        'sales_count' => 2,
                        'sold' => true,
                        'offered_count' => 2,
                        'buyers_count' => 2,
                        'withdraws_count' => 0,
                        'total_count' => 2,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 15000,
                                'price_average' => 15000,
                                'price_max' => 21000,
                                'price_min' => 9000,
                                'price_total' => 30000,
                                'price_count' => 2,
                                'price_top' => 0,
                                'prices' => [
                                    21000,
                                    9000,
                                ],
                                'sales_count' => 2,
                                'sold' => true,
                                'offered_count' => 2,
                                'buyers_count' => 2,
                                'withdraws_count' => 0,
                                'total_count' => 2,
                                'sire_uid' => 731600,
                                'sire_name' => "ALFRED NOBEL",
                                'sire_style_name' => "Alfred Nobel",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Nicholas Caullery",
                                'price' => 9000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => null,
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Nicholas Caullery",
                        'price' => 9000,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 99826,
                        'sire_name' => "ALHAARTH",
                        'sire_style_name' => "Alhaarth",
                        'median' => 4000,
                        'price_average' => 4000,
                        'price_max' => 4000,
                        'price_min' => 4000,
                        'price_total' => 4000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            4000,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => "GBG",
                        'colts' => null,
                        'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 4000,
                                'price_average' => 4000,
                                'price_max' => 4000,
                                'price_min' => 4000,
                                'price_total' => 4000,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    '0' => 4000,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 1,
                                'withdraws_count' => 0,
                                'total_count' => 1,
                                'sire_uid' => 99826,
                                'sire_name' => "ALHAARTH",
                                'sire_style_name' => "Alhaarth",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "F",
                                'buyer_detail' => "Kenneth Slack",
                                'price' => 4000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'sale_year' => 2016,
                        'horse_sex_flag' => "F",
                        'buyer_detail' => "Kenneth Slack",
                        'price' => 4000,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 758138,
                        'sire_name' => "APPROVE",
                        'sire_style_name' => "Approve",
                        'median' => null,
                        'price_average' => null,
                        'price_max' => null,
                        'price_min' => null,
                        'price_total' => 0,
                        'price_count' => 0,
                        'price_top' => 0,
                        'prices' => [],
                        'sales_count' => 0,
                        'sold' => false,
                        'offered_count' => 0,
                        'buyers_count' => 1,
                        'withdraws_count' => 1,
                        'total_count' => 1,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => null,
                                'price_average' => null,
                                'price_max' => null,
                                'price_min' => null,
                                'price_total' => 0,
                                'price_count' => 0,
                                'price_top' => 0,
                                'prices' => [],
                                'sales_count' => 0,
                                'sold' => false,
                                'offered_count' => 0,
                                'buyers_count' => 1,
                                'withdraws_count' => 1,
                                'total_count' => 1,
                                'sire_uid' => 758138,
                                'sire_name' => "APPROVE",
                                'sire_style_name' => "Approve",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Withdrawn",
                                'price' => null,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => null,
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Withdrawn",
                        'price' => null,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 733706,
                        'sire_name' => "ARCANO",
                        'sire_style_name' => "Arcano",
                        'median' => 1500,
                        'price_average' => 1500,
                        'price_max' => 1500,
                        'price_min' => 1500,
                        'price_total' => 1500,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            1500,
                        ],
                        'sales_count' => 1,
                        'sold' => false,
                        'offered_count' => 1,
                        'buyers_count' => 2,
                        'withdraws_count' => 1,
                        'total_count' => 2,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => null,
                                'price_average' => null,
                                'price_max' => null,
                                'price_min' => null,
                                'price_total' => 0,
                                'price_count' => 0,
                                'price_top' => 0,
                                'prices' => [],
                                'sales_count' => 0,
                                'sold' => false,
                                'offered_count' => 0,
                                'buyers_count' => 1,
                                'withdraws_count' => 1,
                                'total_count' => 1,
                                'sire_uid' => 733706,
                                'sire_name' => "ARCANO",
                                'sire_style_name' => "Arcano",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Withdrawn",
                                'price' => null,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 1500,
                                'price_average' => 1500,
                                'price_max' => 1500,
                                'price_min' => 1500,
                                'price_total' => 1500,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    1500,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 1,
                                'withdraws_count' => 0,
                                'total_count' => 1,
                                'sire_uid' => 733706,
                                'sire_name' => "ARCANO",
                                'sire_style_name' => "Arcano",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "F",
                                'buyer_detail' => "Hazzaa Alzamay",
                                'price' => 1500,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Withdrawn",
                        'price' => null,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 660521,
                        'sire_name' => "ARCHIPENKO",
                        'sire_style_name' => "Archipenko",
                        'median' => 8000,
                        'price_average' => 8000,
                        'price_max' => 8000,
                        'price_min' => 8000,
                        'price_total' => 8000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            8000,
                        ],
                        'sales_count' => 1,
                        'sold' => false,
                        'offered_count' => 1,
                        'buyers_count' => 2,
                        'withdraws_count' => 1,
                        'total_count' => 2,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => null,
                                'price_average' => null,
                                'price_max' => null,
                                'price_min' => null,
                                'price_total' => 0,
                                'price_count' => 0,
                                'price_top' => 0,
                                'prices' => [],
                                'sales_count' => 0,
                                'sold' => false,
                                'offered_count' => 0,
                                'buyers_count' => 1,
                                'withdraws_count' => 1,
                                'total_count' => 1,
                                'sire_uid' => 660521,
                                'sire_name' => "ARCHIPENKO",
                                'sire_style_name' => "Archipenko",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Withdrawn",
                                'price' => null,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 8000,
                                'price_average' => 8000,
                                'price_max' => 8000,
                                'price_min' => 8000,
                                'price_total' => 8000,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    8000,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 1,
                                'withdraws_count' => 0,
                                'total_count' => 1,
                                'sire_uid' => 660521,
                                'sire_name' => "ARCHIPENKO",
                                'sire_style_name' => "Archipenko",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "F",
                                'buyer_detail' => "Michael Blanshard Racing",
                                'price' => 8000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Withdrawn",
                        'price' => null,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 584911,
                        'sire_name' => "AZAMOUR",
                        'sire_style_name' => "Azamour",
                        'median' => 8500,
                        'price_average' => 11250,
                        'price_max' => 22000,
                        'price_min' => 6000,
                        'price_total' => 45000,
                        'price_count' => 4,
                        'price_top' => 0,
                        'prices' => [
                            6000,
                            9000,
                            8000,
                            22000,
                        ],
                        'sales_count' => 4,
                        'sold' => true,
                        'offered_count' => 4,
                        'buyers_count' => 4,
                        'withdraws_count' => 0,
                        'total_count' => 4,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 15000,
                                'price_average' => 15000,
                                'price_max' => 22000,
                                'price_min' => 8000,
                                'price_total' => 30000,
                                'price_count' => 2,
                                'price_top' => 0,
                                'prices' => [
                                    8000,
                                    22000,
                                ],
                                'sales_count' => 2,
                                'sold' => true,
                                'offered_count' => 2,
                                'buyers_count' => 2,
                                'withdraws_count' => 0,
                                'total_count' => 2,
                                'sire_uid' => 584911,
                                'sire_name' => "AZAMOUR",
                                'sire_style_name' => "Azamour",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Derek Shaw Racing",
                                'price' => 22000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 7500,
                                'price_average' => 7500,
                                'price_max' => 9000,
                                'price_min' => 6000,
                                'price_total' => 15000,
                                'price_count' => 2,
                                'price_top' => 0,
                                'prices' => [
                                    6000,
                                    9000,
                                ],
                                'sales_count' => 2,
                                'sold' => true,
                                'offered_count' => 2,
                                'buyers_count' => 2,
                                'withdraws_count' => 0,
                                'total_count' => 2,
                                'sire_uid' => 584911,
                                'sire_name' => "AZAMOUR",
                                'sire_style_name' => "Azamour",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "F",
                                'buyer_detail' => "BBA Ireland",
                                'price' => 9000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Derek Shaw Racing",
                        'price' => 22000,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 448003,
                        'sire_name' => "BAHAMIAN BOUNTY",
                        'sire_style_name' => "Bahamian Bounty",
                        'median' => 4000,
                        'price_average' => 6333.33,
                        'price_max' => 14000,
                        'price_min' => 1000,
                        'price_total' => 19000,
                        'price_count' => 3,
                        'price_top' => 0,
                        'prices' => [
                            1000,
                            4000,
                            14000,
                        ],
                        'sales_count' => 3,
                        'sold' => true,
                        'offered_count' => 3,
                        'buyers_count' => 3,
                        'withdraws_count' => 0,
                        'total_count' => 3,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 4000,
                                'price_average' => 6333.33,
                                'price_max' => 14000,
                                'price_min' => 1000,
                                'price_total' => 19000,
                                'price_count' => 3,
                                'price_top' => 0,
                                'prices' => [
                                    1000,
                                    4000,
                                    14000,
                                ],
                                'sales_count' => 3,
                                'sold' => true,
                                'offered_count' => 3,
                                'buyers_count' => 3,
                                'withdraws_count' => 0,
                                'total_count' => 3,
                                'sire_uid' => 448003,
                                'sire_name' => "BAHAMIAN BOUNTY",
                                'sire_style_name' => "Bahamian Bounty",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Mark Johnston Racing",
                                'price' => 14000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => null,
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Mark Johnston Racing",
                        'price' => 14000,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 739856,
                        'sire_name' => "BATED BREATH",
                        'sire_style_name' => "Bated Breath",
                        'median' => 65000,
                        'price_average' => 65000,
                        'price_max' => 65000,
                        'price_min' => 65000,
                        'price_total' => 65000,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            65000,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => "GBG",
                        'colts' => null,
                        'fillies' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 65000,
                                'price_average' => 65000,
                                'price_max' => 65000,
                                'price_min' => 65000,
                                'price_total' => 65000,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    65000,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 1,
                                'withdraws_count' => 0,
                                'total_count' => 1,
                                'sire_uid' => 739856,
                                'sire_name' => "BATED BREATH",
                                'sire_style_name' => "Bated Breath",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "F",
                                'buyer_detail' => "Tim Lane",
                                'price' => 65000,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'sale_year' => 2016,
                        'horse_sex_flag' => "F",
                        'buyer_detail' => "Tim Lane",
                        'price' => 65000,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
                \Phalcon\Mvc\Model\Row\General::createFromArray(
                    [
                        'sire_uid' => 511841,
                        'sire_name' => "BERNSTEIN",
                        'sire_style_name' => "Bernstein",
                        'median' => 6500,
                        'price_average' => 6500,
                        'price_max' => 6500,
                        'price_min' => 6500,
                        'price_total' => 6500,
                        'price_count' => 1,
                        'price_top' => 0,
                        'prices' => [
                            6500,
                        ],
                        'sales_count' => 1,
                        'sold' => true,
                        'offered_count' => 1,
                        'buyers_count' => 1,
                        'withdraws_count' => 0,
                        'total_count' => 1,
                        'cur_code' => "GBG",
                        'colts' => \Phalcon\Mvc\Model\Row\General::createFromArray(
                            [
                                'median' => 6500,
                                'price_average' => 6500,
                                'price_max' => 6500,
                                'price_min' => 6500,
                                'price_total' => 6500,
                                'price_count' => 1,
                                'price_top' => 0,
                                'prices' => [
                                    6500,
                                ],
                                'sales_count' => 1,
                                'sold' => true,
                                'offered_count' => 1,
                                'buyers_count' => 1,
                                'withdraws_count' => 0,
                                'total_count' => 1,
                                'sire_uid' => 511841,
                                'sire_name' => "BERNSTEIN",
                                'sire_style_name' => "Bernstein",
                                'sale_year' => 2016,
                                'horse_sex_flag' => "M",
                                'buyer_detail' => "Colm Sharkey,Agent",
                                'price' => 6500,
                                'exchange_rate' => 0.95238,
                                'currency_code' => "GNS",
                                'cur_code' => "GBG",
                            ]
                        ),
                        'fillies' => null,
                        'sale_year' => 2016,
                        'horse_sex_flag' => "M",
                        'buyer_detail' => "Colm Sharkey,Agent",
                        'price' => 6500,
                        'exchange_rate' => 0.95238,
                        'currency_code' => "GNS",
                    ]
                ),
            ]
        ]
    ]
];
