<?php

use Api\Input\Request\Horses\Bloodstock\Sales as Request;
use \Phalcon\Mvc\Model\Row\General;

return [
    [
        new Request\SalesResults([], [
            'dateFrom' => '2017-12-10',
            'dateTo' => '2017-12-12',
            'buyer' => 'Withdrawn',
            'vendor' => 'Euro',
            'sire' => 'Arc',
        ]),
        [
            0 => General::createFromArray([
                'horse_uid' => 1536543,
                'horse_name' => 'SHADOW SEEKER',
                'horse_style_name' => 'Shadow Seeker',
                'dam_date_of_birth' => 'Feb 17 2007 12:00AM',
                'dam_style_name' => 'New Atalanta',
                'sire_style_name' => 'Arcano',
                'sire_of_dam_style_name' => 'Xaar',
                'horse_country_origin_code' => 'IRE',
                'horse_first_colour_code' => 'B',
                'horse_sex' => 'F',
                'horse_age' => 2,
                'sire_uid' => 733706,
                'sire_name' => 'ARCANO',
                'sire_country_origin_code' => 'IRE',
                'dam_uid' => 744512,
                'dam_name' => 'NEW ATALANTA',
                'dam_country_origin_code' => 'IRE',
                'sire_of_dam_uid' => 469953,
                'sire_of_dam_name' => 'XAAR',
                'sire_of_dam_ctry_org_code' => 'GB',
                'venue_desc' => 'TATTS IRE (ASCOT)',
                'venue_uid' => 49,
                'sale_name' => 'Tattersalls Ireland Ascot December Sale 2017',
                'sale_date' => 'Dec 11 2017 12:00AM',
                'seller_name' => 'A Partnership from Charnwood Stables (P. D\'Arcy)',
                'catalogue_pedigree_pdf_url' => 'http://www.tattersalls.com/cat/ADE/2017/26.pdf',
                'lot_no' => 26,
                'lot_letter' => ' ',
                'price' => null,
                'lot_price' => null,
                'currency' => 'GBP',
                'buyer_detail' => 'Withdrawn',
                'yob' => 2015,
                'sirecam_video_html' => null,
                'entered' => 'Y',
                'entered_races' => [
                    0 => General::createFromArray([
                        'horse_uid' => 1536543,
                        'race_instance_uid' => 689902,
                    ]),
                ],
            ]),
            1 => General::createFromArray([
                'horse_uid' => 686374,
                'horse_name' => 'CALL ME KITTY',
                'horse_style_name' => 'Call Me Kitty',
                'dam_date_of_birth' => 'Jan  1 1995 12:00AM',
                'dam_style_name' => 'Fifty Niner',
                'sire_style_name' => 'Marchand De Sable',
                'sire_of_dam_style_name' => 'Fijar Tango',
                'horse_country_origin_code' => 'FR',
                'horse_first_colour_code' => 'B',
                'horse_sex' => 'F',
                'horse_age' => 12,
                'sire_uid' => 79104,
                'sire_name' => 'MARCHAND DE SABLE',
                'sire_country_origin_code' => 'USA',
                'dam_uid' => 471552,
                'dam_name' => 'FIFTY NINER',
                'dam_country_origin_code' => 'FR',
                'sire_of_dam_uid' => 41809,
                'sire_of_dam_name' => 'FIJAR TANGO',
                'sire_of_dam_ctry_org_code' => 'FR',
                'venue_desc' => 'ARQANA',
                'venue_uid' => 36,
                'sale_name' => 'Arqana December Breeding Stock Sale 2017',
                'sale_date' => 'Dec 11 2017 12:00AM',
                'seller_name' => 'From Petit Tellier',
                'catalogue_pedigree_pdf_url' => 'http://www.arqana.com/upload/pedigrees/vente229/fra/781.pdf',
                'lot_no' => 781,
                'lot_letter' => ' ',
                'price' => 3000,
                'lot_price' => '2564.102564102564102',
                'currency' => 'EUR',
                'buyer_detail' => 'COLE Daniel',
                'yob' => 2005,
                'sirecam_video_html' => null,
                'entered' => 'N',
                'entered_races' => null,
            ]),
            2 => General::createFromArray([
                'horse_uid' => null,
                'horse_name' => null,
                'horse_style_name' => null,
                'dam_date_of_birth' => null,
                'dam_style_name' => null,
                'sire_style_name' => 'Archipenko',
                'sire_of_dam_style_name' => null,
                'horse_country_origin_code' => 'FR',
                'horse_first_colour_code' => 'B',
                'horse_sex' => 'C',
                'horse_age' => 0,
                'sire_uid' => 660521,
                'sire_name' => 'ARCHIPENKO',
                'sire_country_origin_code' => 'USA',
                'dam_uid' => null,
                'dam_name' => 'SOL Y SOMBRA',
                'dam_country_origin_code' => 'GB',
                'sire_of_dam_uid' => null,
                'sire_of_dam_name' => 'HERNANDO',
                'sire_of_dam_ctry_org_code' => 'FR',
                'venue_desc' => 'ARQANA',
                'venue_uid' => 36,
                'sale_name' => 'Arqana December Breeding Stock Sale 2017',
                'sale_date' => 'Dec 11 2017 12:00AM',
                'seller_name' => 'From Etreham',
                'catalogue_pedigree_pdf_url' => 'http://www.arqana.com/upload/pedigrees/vente229/fra/656.pdf',
                'lot_no' => 656,
                'lot_letter' => ' ',
                'price' => 7000,
                'lot_price' => '5982.905982905982905',
                'currency' => 'EUR',
                'buyer_detail' => 'FAL STUD',
                'yob' => 2017,
                'sirecam_video_html' => null,
                'entered' => 'N',
                'entered_races' => null,
            ]),
        ]
    ],
];
