<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Bloodstock\Stallion\DamSireProgenyHorses\General;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;
use \Api\DataProvider\Bo\Bloodstock\Stallion\ProgenyHorses;

/**
 * Class Test
 *
 * @package Tests\Controllers\Horses\Bloodstock\Stallion\DamSireProgenyHorses\General
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/bloodstock/stallion/531769/dam-sire-progeny-horses';
    }

    /**
     * @inheritdoc
     */
    public function tearDown()
    {
        ProgenyHorses::clear();
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenySeason:46 ->getFirstLastProgenyRaceDatetime()
            '209486d31066476871a5858697f9460a' => [
                [
                    'first_race' => '2005-05-27 16:00:00',
                    'last_race' => '2018-05-28 19:30:00',
                ],
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenySeason:73 ->getAppropriateSeasons()
            '14be7d4f33c48efad7e54ceca777ee92' => [
                [
                    'season_start_date' => '2005-01-01 00:00:00',
                    'season_end_date' => '2005-12-31 23:58:00',
                    'season_type_code' => 'F',
                ],
                [
                    'season_start_date' => '2005-04-24 00:00:00',
                    'season_end_date' => '2006-04-29 23:59:00',
                    'season_type_code' => 'J',
                ],
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenySeason:73 ->getAppropriateSeasons()
            'deca67008d7e42c4a75ef57c3e12c3fe' => [
                [
                    'season_start_date' => '2018-01-01 00:00:00',
                    'season_end_date' => '2018-12-31 23:59:00',
                    'season_type_code' => 'F',
                ],
                [
                    'season_start_date' => '2018-04-29 00:00:00',
                    'season_end_date' => '2019-04-27 23:59:00',
                    'season_type_code' => 'I',
                ],
                [
                    'season_start_date' => '2018-04-29 00:00:00',
                    'season_end_date' => '2019-04-27 23:59:00',
                    'season_type_code' => 'J',
                ],
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenySeason:130 ->getDefaultProgenyRaceType()
            'de8616d402c36a2a405e3b51d4a718bb' => [
                [
                    'flat' => 12290,
                    'jumps' => 2745,
                ],
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenyHorses:245 ->getProgenyHorses()
            '9d5314e574675bfaaf17c63e05feb3e2' => [
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\ProgenyHorses:285 ->getProgenyHorses()
            'e226577126a52d5af093ce5c1cf42fdd' => [
                [
                    'horse_uid' => 998306,
                    'style_name' => 'Asaas',
                    'horse_sex_code' => 'G',
                    'horse_age' => 5,
                    'country_origin_code' => 'USA',
                    'runs' => 7,
                    'wins' => 1,
                    'places' => 2,
                    'total_prize_money' => 5994.73,
                    'sire_uid' => 476627,
                    'sire_style_name' => 'Distorted Humor',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 81,
                ],
                [
                    'horse_uid' => 1266451,
                    'style_name' => 'Alpine Peak',
                    'horse_sex_code' => 'C',
                    'horse_age' => 4,
                    'country_origin_code' => 'USA',
                    'runs' => 5,
                    'wins' => 0,
                    'places' => 1,
                    'total_prize_money' => 432.9,
                    'sire_uid' => 534251,
                    'sire_style_name' => 'Mizzen Mast',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 73,
                    'best_or' => 77,
                ],
                [
                    'horse_uid' => 794784,
                    'style_name' => 'Dynamite Dixie',
                    'horse_sex_code' => 'G',
                    'horse_age' => 10,
                    'country_origin_code' => 'IRE',
                    'runs' => 26,
                    'wins' => 1,
                    'places' => 5,
                    'total_prize_money' => 10899.9999,
                    'sire_uid' => 640322,
                    'sire_style_name' => 'Dylan Thomas',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 86,
                ],
                [
                    'horse_uid' => 839109,
                    'style_name' => 'Home School',
                    'horse_sex_code' => 'H',
                    'horse_age' => 8,
                    'country_origin_code' => 'IRE',
                    'runs' => 12,
                    'wins' => 1,
                    'places' => 7,
                    'total_prize_money' => 53851.971,
                    'sire_uid' => 706276,
                    'sire_style_name' => 'Intense Focus',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 104,
                    'best_or' => 104,
                ],
                [
                    'horse_uid' => 1498250,
                    'style_name' => 'Aiseolas',
                    'horse_sex_code' => 'F',
                    'horse_age' => 4,
                    'country_origin_code' => 'IRE',
                    'runs' => 5,
                    'wins' => 1,
                    'places' => 3,
                    'total_prize_money' => 12248.6726,
                    'sire_uid' => 708203,
                    'sire_style_name' => 'Vocalised',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 84,
                    'best_or' => 85,
                ],
                [
                    'horse_uid' => 964697,
                    'style_name' => 'Whosyourhousemate',
                    'horse_sex_code' => 'G',
                    'horse_age' => 5,
                    'country_origin_code' => 'GB',
                    'runs' => 6,
                    'wins' => 2,
                    'places' => 3,
                    'total_prize_money' => 13775.38,
                    'sire_uid' => 448003,
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 82,
                ],
                [
                    'horse_uid' => 790275,
                    'style_name' => 'Sky Khan',
                    'horse_sex_code' => 'G',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 18,
                    'wins' => 2,
                    'places' => 7,
                    'total_prize_money' => 14481.6,
                    'sire_uid' => 450464,
                    'sire_style_name' => 'Cape Cross',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 91,
                    'best_or' => 87,
                ],
                [
                    'horse_uid' => 749737,
                    'style_name' => 'Green Warrior',
                    'horse_sex_code' => 'G',
                    'horse_age' => 11,
                    'country_origin_code' => 'GB',
                    'runs' => 28,
                    'wins' => 1,
                    'places' => 4,
                    'total_prize_money' => 6059.0661,
                    'sire_uid' => 506927,
                    'sire_style_name' => 'Invincible Spirit',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 76,
                    'best_or' => 75,
                ],
                [
                    'horse_uid' => 840753,
                    'style_name' => 'Starlit Cantata',
                    'horse_sex_code' => 'M',
                    'horse_age' => 8,
                    'country_origin_code' => 'GB',
                    'runs' => 33,
                    'wins' => 4,
                    'places' => 13,
                    'total_prize_money' => 29537.69,
                    'sire_uid' => 596219,
                    'sire_style_name' => 'Oratorio',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 81,
                ],
                [
                    'horse_uid' => 871674,
                    'style_name' => 'Merry Dancer',
                    'horse_sex_code' => 'M',
                    'horse_age' => 7,
                    'country_origin_code' => 'IRE',
                    'runs' => 11,
                    'wins' => 2,
                    'places' => 0,
                    'total_prize_money' => 4832.6,
                    'sire_uid' => 659996,
                    'sire_style_name' => 'Duke Of Marmalade',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 65,
                    'best_or' => 61,
                ],
                [
                    'horse_uid' => 822358,
                    'style_name' => 'Fledged',
                    'horse_sex_code' => 'G',
                    'horse_age' => 9,
                    'country_origin_code' => 'GB',
                    'runs' => 11,
                    'wins' => 2,
                    'places' => 2,
                    'total_prize_money' => 13847.1225,
                    'sire_uid' => 503875,
                    'sire_style_name' => 'Dansili',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 102,
                    'best_or' => 98,
                ],
                [
                    'horse_uid' => 1774333,
                    'style_name' => 'Wicket',
                    'horse_sex_code' => 'G',
                    'horse_age' => 5,
                    'country_origin_code' => 'GB',
                    'runs' => 5,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 503875,
                    'sire_style_name' => 'Dansili',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 51,
                    'best_or' => 54,
                ],
                [
                    'horse_uid' => 841829,
                    'style_name' => 'Angelic Air',
                    'horse_sex_code' => 'M',
                    'horse_age' => 8,
                    'country_origin_code' => 'GB',
                    'runs' => 3,
                    'wins' => 1,
                    'places' => 1,
                    'total_prize_money' => 3261.0,
                    'sire_uid' => 565797,
                    'sire_style_name' => 'Oasis Dream',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 85,
                    'best_or' => 85,
                ],
                [
                    'horse_uid' => 897525,
                    'style_name' => 'Intermittent',
                    'horse_sex_code' => 'M',
                    'horse_age' => 6,
                    'country_origin_code' => 'GB',
                    'runs' => 8,
                    'wins' => 1,
                    'places' => 4,
                    'total_prize_money' => 9081.85,
                    'sire_uid' => 597314,
                    'sire_style_name' => 'Cacique',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 81,
                    'best_or' => 79,
                ],
                [
                    'horse_uid' => 840082,
                    'style_name' => 'Warbird',
                    'horse_sex_code' => 'G',
                    'horse_age' => 8,
                    'country_origin_code' => 'GB',
                    'runs' => 18,
                    'wins' => 2,
                    'places' => 2,
                    'total_prize_money' => 23096.08,
                    'sire_uid' => 103416,
                    'sire_style_name' => 'Royal Applause',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 95,
                    'best_or' => 98,
                ],
                [
                    'horse_uid' => 1500660,
                    'style_name' => 'Royal Wave',
                    'horse_sex_code' => 'F',
                    'horse_age' => 4,
                    'country_origin_code' => 'GB',
                    'runs' => 7,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => 600.0,
                    'sire_uid' => 103416,
                    'sire_style_name' => 'Royal Applause',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 40,
                    'best_or' => 50,
                ],
                [
                    'horse_uid' => 864623,
                    'style_name' => 'Solar Flair',
                    'horse_sex_code' => 'G',
                    'horse_age' => 7,
                    'country_origin_code' => 'GB',
                    'runs' => 28,
                    'wins' => 5,
                    'places' => 4,
                    'total_prize_money' => 50051.1,
                    'sire_uid' => 692355,
                    'sire_style_name' => 'Equiano',
                    'sire_country_origin_code' => 'FR',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 108,
                    'best_or' => 104,
                ],
                [
                    'horse_uid' => 1967518,
                    'style_name' => 'New Queen',
                    'horse_sex_code' => 'F',
                    'horse_age' => 3,
                    'country_origin_code' => 'GB',
                    'runs' => 2,
                    'wins' => 0,
                    'places' => 2,
                    'total_prize_money' => 2357.75,
                    'sire_uid' => 842791,
                    'sire_style_name' => 'Charm Spirit',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 77,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 752919,
                    'style_name' => 'Arabian Star',
                    'horse_sex_code' => 'G',
                    'horse_age' => 11,
                    'country_origin_code' => 'IRE',
                    'runs' => 26,
                    'wins' => 5,
                    'places' => 6,
                    'total_prize_money' => 45665.57,
                    'sire_uid' => 303737,
                    'sire_style_name' => 'Green Desert',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 97,
                    'best_or' => 92,
                ],
                [
                    'horse_uid' => 805186,
                    'style_name' => 'Illustrate',
                    'horse_sex_code' => 'H',
                    'horse_age' => 9,
                    'country_origin_code' => 'IRE',
                    'runs' => 5,
                    'wins' => 1,
                    'places' => 1,
                    'total_prize_money' => 7235.7724,
                    'sire_uid' => 565797,
                    'sire_style_name' => 'Oasis Dream',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 89,
                    'best_or' => 95,
                ],
                [
                    'horse_uid' => 405346,
                    'style_name' => 'Caitlin',
                    'horse_sex_code' => 'M',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 4,
                    'wins' => 0,
                    'places' => 1,
                    'total_prize_money' => 1120.16,
                    'sire_uid' => 640322,
                    'sire_style_name' => 'Dylan Thomas',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 73,
                    'best_or' => 70,
                ],
                [
                    'horse_uid' => 853048,
                    'style_name' => 'Hit List',
                    'horse_sex_code' => 'G',
                    'horse_age' => 7,
                    'country_origin_code' => 'IRE',
                    'runs' => 7,
                    'wins' => 2,
                    'places' => 1,
                    'total_prize_money' => 9588.65,
                    'sire_uid' => 752305,
                    'sire_style_name' => 'Makfi',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 76,
                    'best_or' => 71,
                ],
                [
                    'horse_uid' => 848543,
                    'style_name' => 'Ede\'s The Business',
                    'horse_sex_code' => 'M',
                    'horse_age' => 8,
                    'country_origin_code' => 'GB',
                    'runs' => 14,
                    'wins' => 0,
                    'places' => 1,
                    'total_prize_money' => 384.8,
                    'sire_uid' => 96463,
                    'sire_style_name' => 'Halling',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 55,
                    'best_or' => 58,
                ],
                [
                    'horse_uid' => 787682,
                    'style_name' => 'Hadaj',
                    'horse_sex_code' => 'G',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 40,
                    'wins' => 3,
                    'places' => 7,
                    'total_prize_money' => 26249.85,
                    'sire_uid' => 303737,
                    'sire_style_name' => 'Green Desert',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 92,
                    'best_or' => 92,
                ],
                [
                    'horse_uid' => 1512975,
                    'style_name' => 'Epsom Bounty',
                    'horse_sex_code' => 'G',
                    'horse_age' => 4,
                    'country_origin_code' => 'GB',
                    'runs' => 4,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 448003,
                    'sire_style_name' => 'Bahamian Bounty',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 53,
                    'best_or' => 55,
                ],
                [
                    'horse_uid' => 788798,
                    'style_name' => 'Bashama',
                    'horse_sex_code' => 'M',
                    'horse_age' => 11,
                    'country_origin_code' => 'GB',
                    'runs' => 18,
                    'wins' => 0,
                    'places' => 3,
                    'total_prize_money' => 1504.85,
                    'sire_uid' => 540336,
                    'sire_style_name' => 'Dubai Destination',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 58,
                    'best_or' => 61,
                ],
                [
                    'horse_uid' => 863627,
                    'style_name' => 'Epsom Poems',
                    'horse_sex_code' => 'G',
                    'horse_age' => 7,
                    'country_origin_code' => 'GB',
                    'runs' => 6,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => 0.0,
                    'sire_uid' => 576872,
                    'sire_style_name' => 'Pastoral Pursuits',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 52,
                    'best_or' => 56,
                ],
                [
                    'horse_uid' => 1047702,
                    'style_name' => 'Epsom Secret',
                    'horse_sex_code' => 'F',
                    'horse_age' => 5,
                    'country_origin_code' => 'GB',
                    'runs' => 15,
                    'wins' => 1,
                    'places' => 5,
                    'total_prize_money' => 5895.55,
                    'sire_uid' => 661629,
                    'sire_style_name' => 'Sakhee\'s Secret',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 61,
                    'best_or' => 59,
                ],
                [
                    'horse_uid' => 801668,
                    'style_name' => 'Guiletta',
                    'horse_sex_code' => 'M',
                    'horse_age' => 10,
                    'country_origin_code' => 'IRE',
                    'runs' => 8,
                    'wins' => 2,
                    'places' => 0,
                    'total_prize_money' => 4851.75,
                    'sire_uid' => 567732,
                    'sire_style_name' => 'Dalakhani',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 72,
                    'best_or' => 68,
                ],
                [
                    'horse_uid' => 800130,
                    'style_name' => 'Gods Gift',
                    'horse_sex_code' => 'G',
                    'horse_age' => 9,
                    'country_origin_code' => 'IRE',
                    'runs' => 9,
                    'wins' => 0,
                    'places' => 5,
                    'total_prize_money' => 3118.77,
                    'sire_uid' => 567732,
                    'sire_style_name' => 'Dalakhani',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 68,
                    'best_or' => 72,
                ],
                [
                    'horse_uid' => 870368,
                    'style_name' => 'Goodyearforroses',
                    'horse_sex_code' => 'M',
                    'horse_age' => 7,
                    'country_origin_code' => 'IRE',
                    'runs' => 15,
                    'wins' => 5,
                    'places' => 3,
                    'total_prize_money' => 311474.8551,
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 108,
                    'best_or' => 94,
                ],
                [
                    'horse_uid' => 850182,
                    'style_name' => 'God\'s Speed',
                    'horse_sex_code' => 'G',
                    'horse_age' => 8,
                    'country_origin_code' => 'IRE',
                    'runs' => 20,
                    'wins' => 4,
                    'places' => 7,
                    'total_prize_money' => 93988.68,
                    'sire_uid' => 596219,
                    'sire_style_name' => 'Oratorio',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 96,
                    'best_or' => 110,
                ],
                [
                    'horse_uid' => 1019935,
                    'style_name' => 'Going Up',
                    'horse_sex_code' => 'G',
                    'horse_age' => 6,
                    'country_origin_code' => 'IRE',
                    'runs' => 8,
                    'wins' => 1,
                    'places' => 3,
                    'total_prize_money' => 5701.35,
                    'sire_uid' => 659996,
                    'sire_style_name' => 'Duke Of Marmalade',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 85,
                    'best_or' => 85,
                ],
                [
                    'horse_uid' => 775148,
                    'style_name' => 'Flashy Star',
                    'horse_sex_code' => 'M',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 13,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => 336.7,
                    'sire_uid' => 98576,
                    'sire_style_name' => 'Mr Greeley',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 62,
                    'best_or' => 62,
                ],
                [
                    'horse_uid' => 867818,
                    'style_name' => 'Hayed',
                    'horse_sex_code' => 'M',
                    'horse_age' => 7,
                    'country_origin_code' => 'GB',
                    'runs' => 2,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => 0.0,
                    'sire_uid' => 584911,
                    'sire_style_name' => 'Azamour',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 29,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 964634,
                    'style_name' => 'White Mischief',
                    'horse_sex_code' => 'F',
                    'horse_age' => 5,
                    'country_origin_code' => 'IRE',
                    'runs' => 1,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 671647,
                    'sire_style_name' => 'Dark Angel',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 40,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 822087,
                    'style_name' => 'Mount Tiger',
                    'horse_sex_code' => 'H',
                    'horse_age' => 9,
                    'country_origin_code' => 'GB',
                    'runs' => 6,
                    'wins' => 2,
                    'places' => 0,
                    'total_prize_money' => 7445.97,
                    'sire_uid' => 488238,
                    'sire_style_name' => 'Tiger Hill',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 89,
                    'best_or' => 81,
                ],
                [
                    'horse_uid' => 797559,
                    'style_name' => 'Luna Vale',
                    'horse_sex_code' => 'M',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 4,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 540336,
                    'sire_style_name' => 'Dubai Destination',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 27,
                    'best_or' => 46,
                ],
                [
                    'horse_uid' => 860735,
                    'style_name' => 'For Me',
                    'horse_sex_code' => 'G',
                    'horse_age' => 8,
                    'country_origin_code' => 'GER',
                    'runs' => 1,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 572780,
                    'sire_style_name' => 'Shirocco',
                    'sire_country_origin_code' => 'GER',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 69,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 839700,
                    'style_name' => 'Hala Hala',
                    'horse_sex_code' => 'M',
                    'horse_age' => 8,
                    'country_origin_code' => 'IRE',
                    'runs' => 12,
                    'wins' => 2,
                    'places' => 4,
                    'total_prize_money' => 11729.07,
                    'sire_uid' => 506927,
                    'sire_style_name' => 'Invincible Spirit',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 79,
                    'best_or' => 79,
                ],
                [
                    'horse_uid' => 861742,
                    'style_name' => 'Aldayha',
                    'horse_sex_code' => 'M',
                    'horse_age' => 7,
                    'country_origin_code' => 'IRE',
                    'runs' => 7,
                    'wins' => 1,
                    'places' => 2,
                    'total_prize_money' => 4952.85,
                    'sire_uid' => 541314,
                    'sire_style_name' => 'Acclamation',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 91,
                    'best_or' => 87,
                ],
                [
                    'horse_uid' => 1913989,
                    'style_name' => 'Cheer The Title',
                    'horse_sex_code' => 'C',
                    'horse_age' => 4,
                    'country_origin_code' => 'IRE',
                    'runs' => 1,
                    'wins' => 0,
                    'places' => 1,
                    'total_prize_money' => 557.96,
                    'sire_uid' => 541314,
                    'sire_style_name' => 'Acclamation',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 68,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 1011683,
                    'style_name' => 'Spirit Of Paris',
                    'horse_sex_code' => 'M',
                    'horse_age' => 6,
                    'country_origin_code' => 'IRE',
                    'runs' => 9,
                    'wins' => 0,
                    'places' => 2,
                    'total_prize_money' => 1939.3382,
                    'sire_uid' => 565570,
                    'sire_style_name' => 'Big Bad Bob',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 58,
                    'best_or' => 60,
                ],
                [
                    'horse_uid' => 843687,
                    'style_name' => 'Guinnevre',
                    'horse_sex_code' => 'M',
                    'horse_age' => 9,
                    'country_origin_code' => 'IRE',
                    'runs' => 11,
                    'wins' => 1,
                    'places' => 4,
                    'total_prize_money' => 42856.1001,
                    'sire_uid' => 659996,
                    'sire_style_name' => 'Duke Of Marmalade',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 106,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 998338,
                    'style_name' => 'Trick Of The Light',
                    'horse_sex_code' => 'G',
                    'horse_age' => 5,
                    'country_origin_code' => 'IRE',
                    'runs' => 10,
                    'wins' => 2,
                    'places' => 5,
                    'total_prize_money' => 13600.57,
                    'sire_uid' => 786762,
                    'sire_style_name' => 'Dragon Pulse',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 82,
                ],
                [
                    'horse_uid' => 1121467,
                    'style_name' => 'Gorgeous Again',
                    'horse_sex_code' => 'G',
                    'horse_age' => 6,
                    'country_origin_code' => 'AUS',
                    'runs' => 25,
                    'wins' => 4,
                    'places' => 5,
                    'total_prize_money' => 284486.6904,
                    'sire_uid' => 596550,
                    'sire_style_name' => 'Fastnet Rock',
                    'sire_country_origin_code' => 'AUS',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 77,
                    'best_or' => null,
                ],
                [
                    'horse_uid' => 839583,
                    'style_name' => 'Zambeasy',
                    'horse_sex_code' => 'G',
                    'horse_age' => 8,
                    'country_origin_code' => 'GB',
                    'runs' => 36,
                    'wins' => 5,
                    'places' => 10,
                    'total_prize_money' => 24367.39,
                    'sire_uid' => 450077,
                    'sire_style_name' => 'Zamindar',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 90,
                    'best_or' => 84,
                ],
                [
                    'horse_uid' => 800308,
                    'style_name' => 'Rutherglen',
                    'horse_sex_code' => 'G',
                    'horse_age' => 9,
                    'country_origin_code' => 'GB',
                    'runs' => 11,
                    'wins' => 3,
                    'places' => 2,
                    'total_prize_money' => 12254.83,
                    'sire_uid' => 488238,
                    'sire_style_name' => 'Tiger Hill',
                    'sire_country_origin_code' => 'IRE',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 86,
                    'best_or' => 80,
                ],
                [
                    'horse_uid' => 871937,
                    'style_name' => 'Beausant',
                    'horse_sex_code' => 'G',
                    'horse_age' => 7,
                    'country_origin_code' => 'GB',
                    'runs' => 10,
                    'wins' => 2,
                    'places' => 2,
                    'total_prize_money' => 7869.74,
                    'sire_uid' => 535308,
                    'sire_style_name' => 'Orientor',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 81,
                    'best_or' => 74,
                ],
                [
                    'horse_uid' => 789310,
                    'style_name' => 'Shamahan',
                    'horse_sex_code' => 'G',
                    'horse_age' => 10,
                    'country_origin_code' => 'GB',
                    'runs' => 30,
                    'wins' => 2,
                    'places' => 6,
                    'total_prize_money' => 11091.71,
                    'sire_uid' => 602045,
                    'sire_style_name' => 'Shamardal',
                    'sire_country_origin_code' => 'USA',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 83,
                    'best_or' => 79,
                ],
                [
                    'horse_uid' => 896056,
                    'style_name' => 'Annie T',
                    'horse_sex_code' => 'M',
                    'horse_age' => 6,
                    'country_origin_code' => 'GB',
                    'runs' => 4,
                    'wins' => 0,
                    'places' => 0,
                    'total_prize_money' => null,
                    'sire_uid' => 752305,
                    'sire_style_name' => 'Makfi',
                    'sire_country_origin_code' => 'GB',
                    'dam_sire_uid' => 531769,
                    'dam_sire_style_name' => 'Galileo',
                    'dam_sire_country_origin_code' => 'IRE',
                    'rp_postmark' => 42,
                    'best_or' => 45,
                ],
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '70ccb2daf31243f4720f49de5fa7d01f' => [
            ],
        ];
    }
}
