<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\RacecardsResults\PostRaceTest;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;

/**
 * Class Test
 * @package Tests\Controllers\Horses\RacecardsResults\PostRaceTest
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/racecards-results/680588';
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\Results\TmpTable\HorseRaceInstance:118 ->createTmpTable()
            '78663697b0e1e1b495c8a6bb49aed182' => [
            ],
            //Models\Bo\RacecardsResults:37->getRaceStatusCode()
            '16f8659aadd9c437061448477d8268b8' => [
                [
                    'race_status_code' => 'R'
                ]
            ],
            //Models\Bo\RacecardsResults:46->getRaceInfo()
            '043ab34f8ea51a423afb346a401ebb9f' => [
                [
                    'course_uid' => 13,
                    'race_instance_title' => 'Horseradish Hospitality At Southport Flower Show/EBF Stallions Conditions Stakes (Plus 10 Race)',
                    'race_datetime' => '2020-07-18 16:10:00',
                    'race_start_datetime' => '2020-07-18 16:10:00',
                    'local_meeting_race_datetime' => '2020-07-18 16:10:00',
                    'hours_difference' => 5,
                    'race_type_code' => 'F',
                    'race_group_desc' => 'Handicap',
                    'race_group_uid' => 1,
                    'race_group_code' => 'H',
                    'pool_prize_sterling' => 10000,
                    'tote_currency_code' => 'GBP',
                    'no_of_runners' => 10,
                    'distance_yard' => 1337,
                    'rp_omitted_fences' => null,
                    'rp_analysis' => 'some analysis text goes here',
                    'course_name' => 'CHESTER',
                    'course_style_name' => 'York',
                    'course_region' => 'GB & IRE',
                    'country_code' => 'GB',
                    'official_rating_band_desc' => '0-87',
                    'straight_round_jubilee_code' => null,
                    'straight_round_jubilee_desc' => null,
                    'rp_straight_round_jubilee_desc' => null,
                    'going_type_desc' => 'Good To Soft',
                    'going_type_code' => 'GS',
                    'meeting_name' => 'CHESTER',
                    'race_attrib_code' => 'Surface',
                    'race_attrib_desc' => 'Turf',
                    'meeting_date' => '2017-08-06 00:00:00',
                    'going_desc' => 'GOOD TO SOFT (6.6)',
                    'stalls_position' => '1m2f - Outside; Remainder - Inside',
                    'misc_text' => ' ',
                    'weather_cond' => 'overcast, cool',
                    'rails' => ' ',
                    'wind' => 'breezy, across',
                    'meeting_abandoned' => null,
                    'abandoned_reason' => null,
                    'jackpot_text' => 'Not won.',
                    'placepot_text' => '£53.00 to a £1 stake. Pool: £88,115.00 - 1,659.42 winning units.',
                    'quadpot_text' => '£8.50 to a £1 stake. Pool: £6,773.00 - 788.82 winning units.',
                    'no_of_fences' => null,
                    'rp_ages_allowed_desc' => '2yo',
                    'eyecatcher_horse_uid' => null,
                    'eyecatcher_style_name' => null,
                    'eyecatcher_country_code' => null,
                    'eyecatcher_notes' => null,
                    'star_performer_horse_uid' => null,
                    'star_performer_style_name' => null,
                    'star_performer_country_code' => null,
                    'star_performer_notes' => null,
                    'race_comments' => null,
                    'start_flag_yn' => 'N',
                    'race_status_code' => 'R',
                    'race_instance_uid' => 680588,
                    'tote_deadheat_text' => null,
                    'tote_win_money' => 29.3,
                    'tote_place_1_money' => 5.8,
                    'tote_place_2_money' => 2.2,
                    'tote_place_3_money' => 5.2,
                    'tote_place_4_money' => 2.1,
                    'tote_dual_forecast_money' => 13.4,
                    'computer_strght_frcst_money' => 231.21,
                    'tricast_money' => 8238.24,
                    'tote_trio_money' => 6040.4,
                    'trio_text' => 'something about trio text',
                    'rule4_text' => 'something about rule4_text',
                    'rule4_value' => 1234,
                    'selling_details_text' => null,
                    'country_desc' => 'Great Britain',
                    'race_surface' => null,
                    'aw_surface_type' => null,
                    'number_of_fences' => null,
                    'dist_number_of_fences' => null,
                ],
            ],
            //Models\Bo\Results\RaceInstance:819 ->getDividends()
            'db6a53dce9f89740aec4bec47f110f18' => [
                [
                    'course_uid' => 13,
                    'race_instance_uid' => 680588,
                    'race_datetime' => '2017-08-06 15:10:00',
                    'race_type_code' => 'F',
                    'finishing_horses' => 2,
                    'flat_or_jumps' => 'F',
                    'race_double' => 6,
                    'race_win_dist' => 3.75,
                    'dht' => 0,
                    'horses_run' => 8,
                    'non_runners' => 0,
                    'race_sp' => 6.0,
                    'race_sp_count' => 1,
                    'race_favs_pos' => 3,
                    'race_favs_count' => 1,
                ]
            ],
            
            //Models\Bo\Results\RaceInstance:840 ->getDividends()
            '9bad2038c5756471624386190d6e907c' => [
                [
                    'course_uid' => 13,
                    'betting_man' => 'PETER HEAVEN & TURFTV',
                    'analysis_man' => 'GAVIN BEECH',
                    'close_up_man' => 'KEITH McHUGH',
                ],
            ],
            //Models\Bo\Results\RaceAttribLookup:34 ->getRaceClass()
            'ef711cd22fd643560fca9e2145b25f7d' => [
                [
                    'race_attrib_desc' => '3',
                ],
            ],
            //Models\Bo\Results\RaceInstancePrize:44 ->getRacePrizes()
            '347d189ce201cca9b858ef3b2042d82b' => [
                [
                    'prize_sterling' => 7000,
                    'prize_euro' => 7000,
                    'position_no' => 1,
                ],
                [
                    'prize_sterling' => 1500,
                    'prize_euro' => 7000,
                    'position_no' => 2,
                ],
                [
                    'prize_sterling' => 1000,
                    'prize_euro' => 7000,
                    'position_no' => 3,
                ],
                [
                    'prize_sterling' => 500,
                    'prize_euro' => 7000,
                    'position_no' => 4,
                ],
            ],
            //Api\DataProvider\Bo\VideoProviders:31 ->getDetails() DROP TABLE #tmp_race_ids
            'fabddb1710b03508361534ea456ae438' => [
            ],
            //Api\DataProvider\Bo\VideoProviders:31 ->getDetails() SELECT INTO #tmp_race_ids
            '8ebc22af016d42114642ddce44a8aa96' => [
            ],
            //Api\DataProvider\Bo\VideoProviders:31 ->getDetails() Main statement
            '10beaaaa61612758c43257e79f9dda01' => [
                [
                    'race_instance_uid' => 680588,
                    'ptv_video_id' => 1281765,
                    'video_provider' => 'ATR',
                    'stream_url' => null,
                    'complete_race_uid' => 2705304,
                    'complete_race_start' => 321,
                    'complete_race_end' => 487,
                    'finish_race_uid' => 2705305,
                    'finish_race_start' => 357,
                    'finish_race_end' => 447,
                ],
            ],
            //\Bo\RacecardsResults/:83 ->getRaceAttributes()
            'f4b71928d92e70a3079ca452abe35cef' => [
                [
                    'race_attrib_desc' => "3",
                    'race_attrib_code' => 'Class',
                    'race_attrib_uid'  => 85,
                    'race_instance_uid' => 68058801
                ],
                [
                    'race_attrib_desc' => "Mdn",
                    'race_attrib_code' => 'Category',
                    'race_attrib_uid'  => 85,
                    'race_instance_uid' => 68058801
                ],
                [
                    'race_attrib_desc' => "Cheese",
                    'race_attrib_code' => 'Surface',
                    'race_attrib_uid'  => 75,
                    'race_instance_uid' => 6805880
                ]
            ],
            //\Bo\RacecardsResults/:92 ->getStatistic()
            '5ff3f09f605d0417a9a0c3a94a5698d4' => [
                [
                    'race_instance_uid' => 680588,
                    'winners_time_secs' => 86.53,
                    'diff_to_standard_time_sec' => 3.23,
                    'course_uid' => 1079,
                    'no_of_runners' => 1,
                    'average_time_sec' => 83.3,
                    'total_sp' => 50.5,
                    'no_of_runners_calculated' => 1,
                    'odds_value' => 1,
                    'country_code' => 'GB',
                ],
            ],
            //Api\DataProvider\Bo\Results\TmpTable\CourseRaceTime:81 ->createTmpTable()
            '28a823eb253588d3b4f84fbeb8e641e4' => [
            ],
            //Api\DataProvider\Bo\TmpTable ->dropTmpTable()
            'c8767c5cb230e3ef39ddbb7447c0e268' => [
            ],
            //Models\Bo\Results\HorseRace:47 ->fetchResultsByRace()
            'a36c51ede1d03059031b555330a67d8c' => [
                [
                    'horse_uid' => 1540358,
                    'horse_style_name' => 'Quargent',
                    'horse_country_origin_code' => 'USA',
                    'horse_age' => 2,
                    'jockey_style_name' => 'Jamie Spencer',
                    'jockey_aka_style_name' => 'J P Spencer',
                    'jockey_uid' => 13689,
                    'trainer_style_name' => 'Jeremy Noseda',
                    'trainer_mirror_name' => 'J Noseda',
                    'trainer_uid' => 10613,
                    'final_race_outcome_position' => 1,
                    'orig_race_outcome_position' => 1,
                    'final_race_outcome_code' => '1',
                    'final_race_outcome_desc' => '1st',
                    'official' => 46,
                    'new_trainer_races_count' => null,
                    'irish_reserve_yn' => 'N',
                    'final_race_outcome_joint_yn' => 'N',
                    'final_race_output_order' => 1,
                    'orig_race_output_order' => 1,
                    'rp_distance_desc' => null,
                    'dth_distance_value' => null,
                    'draw' => 2,
                    'weight_carried_lbs' => 126,
                    'extra_weight_lbs' => 0,
                    'favourite_flag' => 'Y',
                    'over_weight_lbs' => 0,
                    'out_of_handicap_lbs' => 0,
                    'odds_desc' => '8/11F',
                    'odds_value' => 25,
                    'joint_1st_fav' => 0,
                    'fav_1st' => 0,
                    'joint_2nd_fav' => 0,
                    'fav_2nd' => 0,
                    'current_official_rating' => 0,
                    'official_rating_ran_off' => 0,
                    'owner_uid' => 146465,
                    'owner_style_name' => 'Marc Keller',
                    'rp_owner_choice' => 'a',
                    'breeder_style_name' => 'Orpendale/Chelston/Wynatt',
                    'rp_close_up_comment' => 'tracked leader, ridden to challenge over 1f out, driven and stayed on to lead well inside final furlong, steadily going away at finish',
                    'rp_betting_movements' => 'op 4/5 tchd Evens',
                    'rp_horse_head_gear_code' => null,
                    'first_time_yn' => 'N',
                    'dist_to_horse_in_front_uid' => null,
                    'distance_to_winner_uid' => null,
                    'saddle_cloth_no' => 10,
                    'rp_ages_allowed_desc' => '2yo',
                    'rp_postmark' => 81,
                    'rp_topspeed' => -12,
                    'starting_price_odds_uid' => 49,
                    'horse_sex_code' => 'F',
                    'horse_date_of_birth' => '2015-02-06 00:00:00',
                    'date_gelded' => '2014-08-16 18:40:00',
                    'horse_colour_code' => 'B',
                    'rp_newspaper_output_desc' => 'b',
                    'race_datetime' => '2017-08-16 18:40:00',
                    'no_of_fences' => null,
                    'weight_allowance_lbs' => 0,
                    'disqualification_uid' => null,
                    'sire_uid' => 649250,
                    'horse_head_gear_desc' => 'eye-shields',
                    'dam_uid' => 786716,
                    'first_season_sire_id' => null,
                    'sire_avg_flat_wdp' => 8.0,
                    'sire_avg_jump_wdp' => null,
                    'horse_sire_country' => 'USA',
                    'horse_sire_style_name' => 'War Front',
                    'horse_dam_country' => 'USA',
                    'horse_dam_style_name' => 'Naples Bay',
                    'horse_dam_sire_style_name' => 'Giant\'s Causeway',
                    'horse_dam_sire_horse_uid' => 513047,
                    'dam_sire_sire_uid' => 304247,
                    'dam_sire_dam_uid' => 99024,
                    'horse_colour_desc' => 'White',
                    'dam_sire_country_origin_code' => 'USA',
                    'dam_sire_avg_flat_wdp' => 8.0,
                    'dam_sire_avg_jump_wdp' => null,
                    'race_outcome_uid' => 1,
                    'final_race_outcome_uid' => 1,
                    'owner_group_uid' => null,
                    'dtw_sum_distance_value' => null,
                    'horse_sex_desc' => 'Filly',
                    'wfa_adjustment' => 30,
                    'is_wind_surgery_first_time' => 'N',
                    'is_wind_surgery_second_time' => 'N',
                    'race_type_code' => 'X',
                    'distance_yard' => 1,
                    'notes' => 'test',
                    'beatenFavourite' => null
                ],
                [
                    'horse_uid' => 1528380,
                    'horse_style_name' => 'Amandine',
                    'horse_country_origin_code' => 'GB',
                    'horse_age' => 2,
                    'jockey_style_name' => 'Fran Berry',
                    'jockey_aka_style_name' => 'Fran Berry',
                    'jockey_uid' => 14025,
                    'official' => 13,
                    'new_trainer_races_count' => null,
                    'irish_reserve_yn' => 'N',
                    'trainer_style_name' => 'David Elsworth',
                    'trainer_mirror_name' => 'D Elsworth',
                    'trainer_uid' => 149,
                    'final_race_outcome_position' => 2,
                    'orig_race_outcome_position' => 2,
                    'final_race_outcome_code' => '2',
                    'final_race_outcome_desc' => '2nd',
                    'final_race_outcome_joint_yn' => 'N',
                    'final_race_output_order' => 2,
                    'orig_race_output_order' => 2,
                    'rp_distance_desc' => '1 3/4',
                    'dth_distance_value' => 1.75,
                    'draw' => 1,
                    'weight_carried_lbs' => 126,
                    'favourite_flag' => null,
                    'extra_weight_lbs' => 0,
                    'over_weight_lbs' => 0,
                    'out_of_handicap_lbs' => 0,
                    'odds_desc' => '7/1',
                    'odds_value' => 25,
                    'joint_1st_fav' => 0,
                    'fav_1st' => 0,
                    'joint_2nd_fav' => 0,
                    'fav_2nd' => 0,
                    'horse_head_gear_desc' => 'Baseball Cap',
                    'current_official_rating' => 0,
                    'official_rating_ran_off' => 0,
                    'owner_uid' => 88681,
                    'owner_style_name' => 'Lordship Stud',
                    'rp_owner_choice' => 'a',
                    'breeder_style_name' => 'Lordship Stud',
                    'rp_close_up_comment' => 'took keen hold early, tracked leaders, effort on inner 2f out, led entering final furlong, driven inside final furlong, headed and no extra well inside final furlong',
                    'rp_betting_movements' => 'op 6/1',
                    'rp_horse_head_gear_code' => null,
                    'first_time_yn' => 'N',
                    'dist_to_horse_in_front_uid' => 33,
                    'distance_to_winner_uid' => 398,
                    'saddle_cloth_no' => 2,
                    'rp_ages_allowed_desc' => '2yo',
                    'rp_postmark' => 76,
                    'rp_topspeed' => 60,
                    'starting_price_odds_uid' => 17,
                    'horse_sex_code' => 'M',
                    'horse_date_of_birth' => '2015-01-20 00:00:00',
                    'date_gelded' => null,
                    'horse_colour_code' => 'B',
                    'rp_newspaper_output_desc' => 'b',
                    'race_datetime' => '2017-08-16 18:40:00',
                    'no_of_fences' => null,
                    'weight_allowance_lbs' => 0,
                    'disqualification_uid' => null,
                    'sire_uid' => 602045,
                    'dam_uid' => 758495,
                    'first_season_sire_id' => null,
                    'sire_avg_flat_wdp' => 8.1,
                    'sire_avg_jump_wdp' => null,
                    'horse_sire_country' => 'USA',
                    'horse_sire_style_name' => 'Shamardal',
                    'horse_dam_country' => 'IRE',
                    'horse_dam_style_name' => 'Kissable',
                    'horse_dam_sire_style_name' => 'Danehill Dancer',
                    'horse_dam_sire_horse_uid' => 104011,
                    'dam_sire_sire_uid' => 42373,
                    'dam_sire_dam_uid' => 49465,
                    'dam_sire_country_origin_code' => 'IRE',
                    'dam_sire_avg_flat_wdp' => 8.1,
                    'dam_sire_avg_jump_wdp' => null,
                    'race_outcome_uid' => 2,
                    'final_race_outcome_uid' => 2,
                    'horse_sex_desc' => 'Mare',
                    'horse_colour_desc' => 'Brown',
                    'owner_group_uid' => null,
                    'dtw_sum_distance_value' => 1.75,
                    'wfa_adjustment' => 30,
                    'is_wind_surgery_first_time' => 'Y',
                    'is_wind_surgery_second_time' => 'N',
                    'race_type_code' => 'X',
                    'distance_yard' => 1,
                    'notes' => null,
                    'beatenFavourite' => null
                ],
                [
                    'horse_uid' => 1371856,
                    'horse_style_name' => 'Royal Parks',
                    'horse_country_origin_code' => 'GB',
                    'horse_age' => 2,
                    'official' => 46,
                    'new_trainer_races_count' => null,
                    'irish_reserve_yn' => 'N',
                    'jockey_style_name' => 'Martin Harley',
                    'jockey_aka_style_name' => 'M Harley',
                    'jockey_uid' => 86585,
                    'trainer_style_name' => 'James Tate',
                    'trainer_mirror_name' => 'J Tate',
                    'trainer_uid' => 25914,
                    'favourite_flag' => null,
                    'final_race_outcome_position' => 3,
                    'orig_race_outcome_position' => 3,
                    'final_race_outcome_code' => '3',
                    'final_race_outcome_desc' => '3rd',
                    'horse_head_gear_desc' => 'eye-shields',
                    'final_race_outcome_joint_yn' => 'N',
                    'final_race_output_order' => 3,
                    'orig_race_output_order' => 3,
                    'rp_distance_desc' => '1 1/4',
                    'horse_colour_desc' => 'Brown',
                    'dth_distance_value' => 1.25,
                    'draw' => 7,
                    'weight_carried_lbs' => 133,
                    'extra_weight_lbs' => 0,
                    'over_weight_lbs' => 0,
                    'out_of_handicap_lbs' => 0,
                    'odds_desc' => '5/1',
                    'odds_value' => 25,
                    'joint_1st_fav' => 0,
                    'fav_1st' => 0,
                    'joint_2nd_fav' => 0,
                    'fav_2nd' => 0,
                    'current_official_rating' => 0,
                    'official_rating_ran_off' => 86,
                    'owner_uid' => 17058,
                    'owner_style_name' => 'Saeed Manana',
                    'rp_owner_choice' => 'a',
                    'breeder_style_name' => 'Glebe Stud And Partners',
                    'rp_close_up_comment' => 'led, ridden 2f out, hard pressed over 1f out, headed entering final furlong, no extra and stayed on same pace final 150yds',
                    'rp_betting_movements' => 'op 7/1 tchd 9/2',
                    'rp_horse_head_gear_code' => null,
                    'first_time_yn' => 'N',
                    'dist_to_horse_in_front_uid' => 32,
                    'distance_to_winner_uid' => 53,
                    'saddle_cloth_no' => 1,
                    'rp_ages_allowed_desc' => '2yo',
                    'rp_postmark' => 80,
                    'rp_topspeed' => 63,
                    'starting_price_odds_uid' => 15,
                    'horse_sex_code' => 'F',
                    'horse_date_of_birth' => '2015-02-20 00:00:00',
                    'date_gelded' => null,
                    'horse_colour_code' => 'B',
                    'rp_newspaper_output_desc' => 'b',
                    'race_datetime' => '2017-08-16 18:40:00',
                    'no_of_fences' => null,
                    'weight_allowance_lbs' => 0,
                    'disqualification_uid' => null,
                    'sire_uid' => 739856,
                    'dam_uid' => 822749,
                    'first_season_sire_id' => null,
                    'sire_avg_flat_wdp' => 7.1,
                    'sire_avg_jump_wdp' => null,
                    'horse_sire_country' => 'GB',
                    'horse_sire_style_name' => 'Bated Breath',
                    'horse_dam_country' => 'GB',
                    'horse_dam_style_name' => 'Kensington Gardens',
                    'horse_dam_sire_style_name' => 'Oasis Dream',
                    'horse_dam_sire_horse_uid' => 565797,
                    'dam_sire_sire_uid' => 303737,
                    'dam_sire_dam_uid' => 520450,
                    'dam_sire_country_origin_code' => 'GB',
                    'dam_sire_avg_flat_wdp' => 7.1,
                    'dam_sire_avg_jump_wdp' => null,
                    'race_outcome_uid' => 3,
                    'final_race_outcome_uid' => 3,
                    'owner_group_uid' => null,
                    'dtw_sum_distance_value' => 3.0,
                    'horse_sex_desc' => 'Filly',
                    'wfa_adjustment' => 30,
                    'is_wind_surgery_first_time' => 'N',
                    'is_wind_surgery_second_time' => 'Y',
                    'race_type_code' => 'X',
                    'distance_yard' => 1,
                    'notes' => null,
                    'beatenFavourite' => null
                ],
                [
                    'horse_uid' => 1469596,
                    'horse_style_name' => 'Cavatina',
                    'horse_country_origin_code' => 'GB',
                    'horse_age' => 2,
                    'jockey_style_name' => 'Pat Cosgrave',
                    'horse_colour_desc' => 'Brown',
                    'jockey_aka_style_name' => 'P Cosgrave',
                    'jockey_uid' => 14629,
                    'official' => 46,
                    'new_trainer_races_count' => null,
                    'irish_reserve_yn' => 'N',
                    'horse_head_gear_desc' => 'eye-shields',
                    'trainer_style_name' => 'William Haggas',
                    'trainer_mirror_name' => 'W Haggas',
                    'trainer_uid' => 3415,
                    'final_race_outcome_position' => 4,
                    'orig_race_outcome_position' => 5,
                    'final_race_outcome_code' => '4',
                    'final_race_outcome_desc' => '4th',
                    'final_race_outcome_joint_yn' => 'N',
                    'final_race_output_order' => 4,
                    'orig_race_output_order' => 4,
                    'rp_distance_desc' => '1 3/4',
                    'dth_distance_value' => 1.75,
                    'draw' => 9,
                    'weight_carried_lbs' => 126,
                    'extra_weight_lbs' => 0,
                    'favourite_flag' => null,
                    'over_weight_lbs' => 0,
                    'out_of_handicap_lbs' => 0,
                    'odds_desc' => '14/1',
                    'odds_value' => 25,
                    'joint_1st_fav' => 0,
                    'fav_1st' => 0,
                    'joint_2nd_fav' => 0,
                    'fav_2nd' => 0,
                    'current_official_rating' => 0,
                    'official_rating_ran_off' => 0,
                    'owner_uid' => 16105,
                    'owner_style_name' => 'Cheveley Park Stud',
                    'rp_owner_choice' => 'a',
                    'breeder_style_name' => 'Cheveley Park Stud Ltd',
                    'rp_close_up_comment' => 'held up in touch in midfield, effort entering final 2f, headway over 1f out, stayed on inside final furlong without threatening leaders',
                    'rp_betting_movements' => 'op 12/1',
                    'rp_horse_head_gear_code' => null,
                    'first_time_yn' => 'N',
                    'dist_to_horse_in_front_uid' => 33,
                    'distance_to_winner_uid' => 100,
                    'saddle_cloth_no' => 3,
                    'rp_ages_allowed_desc' => '2yo',
                    'rp_postmark' => 68,
                    'rp_topspeed' => 51,
                    'starting_price_odds_uid' => 1,
                    'horse_sex_code' => 'F',
                    'horse_date_of_birth' => '2015-04-16 00:00:00',
                    'date_gelded' => null,
                    'horse_colour_code' => 'B',
                    'rp_newspaper_output_desc' => 'b',
                    'race_datetime' => '2017-08-16 18:40:00',
                    'no_of_fences' => null,
                    'weight_allowance_lbs' => 0,
                    'disqualification_uid' => null,
                    'sire_uid' => 783335,
                    'dam_uid' => 757718,
                    'first_season_sire_id' => null,
                    'sire_avg_flat_wdp' => 7.1,
                    'sire_avg_jump_wdp' => null,
                    'horse_sire_country' => 'IRE',
                    'horse_sire_style_name' => 'Lethal Force',
                    'horse_dam_country' => 'GB',
                    'horse_dam_style_name' => 'Piano',
                    'horse_dam_sire_style_name' => 'Azamour',
                    'horse_dam_sire_horse_uid' => 584911,
                    'dam_sire_sire_uid' => 301663,
                    'dam_sire_dam_uid' => 105146,
                    'dam_sire_country_origin_code' => 'IRE',
                    'dam_sire_avg_flat_wdp' => 7.1,
                    'dam_sire_avg_jump_wdp' => null,
                    'race_outcome_uid' => 4,
                    'final_race_outcome_uid' => 75,
                    'horse_sex_desc' => 'Filly',
                    'owner_group_uid' => null,
                    'dtw_sum_distance_value' => 4.75,
                    'wfa_adjustment' => 30,
                    'is_wind_surgery_first_time' => 'N',
                    'is_wind_surgery_second_time' => 'N',
                    'race_type_code' => 'X',
                    'distance_yard' => 1,
                    'notes' => null,
                    'beatenFavourite' => null
                ]
            ],
            //Models\Bo\Results\HorseRace:375 ->getHorseRacesToCalculatePrevAndNextRaces()
            '7f2114739216b75baf2e819873390c10' => [
                [
                    'race_instance_uid' => 680588,
                    'race_datetime' => '2018-01-26 12:10:00',
                    'horse_uid' => 1582152,
                    'course_uid' => 393,
                    'course_name' => 'LINGFIELD (A.W)',
                ],
            ],
            //Models/Bo/Results:147 ->createTmpTableForResultsPopulateExtraFields()
            '350f6751aaf741a912bd1fad544e3d98' => [
            ],
            //Models\Bo\RaceCards\Runners:529 ->getFirstSeasonSire()
            'd31eb5133a2c8ff7c49b9d17a37a0362'=>[
                [
                    'horse_uid' => 1582150,
                    'to_follow_uid' => 80
                ]
            ],
            //Models\Bo\Results\HorseRace:494 ->getHorseOwnerGroups()
            '87048e0b74033b16ce927b290e15cd60' => [
                [
                    'horse_uid' => 1353019,
                    'owner_group_uid' => 5,
                    'to_follow_uid' => null
                ],
            ],
            //Models\Bo\Results\HorseRace:579 ->getGeldingFirstTimeRunnersForResults()
            '05ac776db557a7ccb5df1aa2df083d37' => [
                [
                    'horse_uid' => 1540358
                ]
            ],

            //Models/Bo/RaceCards/Runners:426 ->createTmpTableHorseRaces()
            '22297cbc555068e433c7d569f676651c' => [
            ],
            //Models/Bo/RaceCards/Runners:432 ->createTmpTableLastSurgery()
            'af64981bb085e581470168b9913a08b4' => [
            ],
            //Models/Bo/RaceCards/Runners:434 ->countRacesAfterSurgery()
            'ea07916079682d71a5734a314ac8c54f' => [
            ],
            //Api\DataProvider\Bo\TmpTable ->dropTmpTable()
            'f268da9b3574e32b5a7f04bb65cb9fb7' => [
            ],
            //Api\DataProvider\Bo\TmpTable ->dropTmpTable()
            '9ee438da8697301551276b894669ab4c' => [
            ],
            //Models/Bo/RaceCards/Runners:444 ->getWfaPerAges()
            '7ca73a716cafc7207c6e71461a979dc9' => [
                [
                    'weight_allowance_lbs' => 10,
                    'age' => 2,
                    'distance_furlongs' => 5,
                    'race_type_code' => 'F'
                ]
            ],

        ];
    }
}
