<?php

declare(strict_types=1);

namespace Tests\Controllers\Horses\Bloodstock\Stallion\Nick;

use UnitTestsComponents\ApiRouteTest\Json as ApiRouteTestPrototype;
use \Api\DataProvider\Bo\Bloodstock\Stallion\Stallion;

/**
 * @package Tests\Controllers\Horses\Bloodstock\Stallion\Nick
 */
class Test extends ApiRouteTestPrototype
{
    /**
     * @return string
     */
    public function getRoute(): string
    {
        return '/horses/bloodstock/stallion/734508/nick';
    }

    /**
     * @inheritdoc
     */
    public function tearDown()
    {
        Stallion::clear();
    }

    /**
     * @return array
     */
    public function getPseudoPdoData(): array
    {
        return [
            //Api\DataProvider\Bo\Bloodstock\Stallion\Nick:56 ->getNick()
            '17119f86f2d54b245b029f4a0b2e7779' => [
            ],
            //Api\DataProvider\Bo\Bloodstock\Stallion\Nick:58 ->getNick()
            'e5d7e10794f0e4f63c4bde0c5c466dbf' => [
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 2,
                    'no_of_runners' => 1,
                    'win_prize_money' => 770.0,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 4,
                    'no_of_runners' => 1,
                    'win_prize_money' => 336.7,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 5,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 6,
                    'no_of_runners' => 1,
                    'win_prize_money' => 0.0,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 7,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 8,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 9,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 11,
                    'no_of_runners' => 3,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 22874,
                    'ancestor_name' => 'Genereux Genie',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 964797,
                    'style_name' => 'Warleggan',
                    'race_outcome_position' => 12,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 78138,
                    'ancestor_name' => 'Protektor',
                    'ancestor_country_origin_code' => 'GER',
                    'horse_uid' => 1692271,
                    'style_name' => 'Lion Rouge',
                    'race_outcome_position' => 2,
                    'no_of_runners' => 1,
                    'win_prize_money' => 954.0,
                ],
                [
                    'ancestor_uid' => 107700,
                    'ancestor_name' => 'Pivotal',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 1050860,
                    'style_name' => 'French Silver',
                    'race_outcome_position' => 7,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 107700,
                    'ancestor_name' => 'Pivotal',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 1050860,
                    'style_name' => 'French Silver',
                    'race_outcome_position' => 8,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 107700,
                    'ancestor_name' => 'Pivotal',
                    'ancestor_country_origin_code' => 'GB',
                    'horse_uid' => 1050860,
                    'style_name' => 'French Silver',
                    'race_outcome_position' => 9,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 109077,
                    'ancestor_name' => 'Astarabad',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1471877,
                    'style_name' => 'Astone Man',
                    'race_outcome_position' => 3,
                    'no_of_runners' => 1,
                    'win_prize_money' => 577.2,
                ],
                [
                    'ancestor_uid' => 109077,
                    'ancestor_name' => 'Astarabad',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1471877,
                    'style_name' => 'Astone Man',
                    'race_outcome_position' => 4,
                    'no_of_runners' => 2,
                    'win_prize_money' => 456.95,
                ],
                [
                    'ancestor_uid' => 303416,
                    'ancestor_name' => 'Law Society',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1037629,
                    'style_name' => 'Brametot',
                    'race_outcome_position' => 6,
                    'no_of_runners' => 1,
                    'win_prize_money' => 17550.0,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 1,
                    'no_of_runners' => 3,
                    'win_prize_money' => 21432.5695,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 2,
                    'no_of_runners' => 2,
                    'win_prize_money' => 1347.5,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 3,
                    'no_of_runners' => 1,
                    'win_prize_money' => 500.24,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 5,
                    'no_of_runners' => 3,
                    'win_prize_money' => 150.4274,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 6,
                    'no_of_runners' => 4,
                    'win_prize_money' => 0.0,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 9,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 304228,
                    'ancestor_name' => 'Highest Honor',
                    'ancestor_country_origin_code' => 'FR',
                    'horse_uid' => 991615,
                    'style_name' => 'Rock On Dandy',
                    'race_outcome_position' => 11,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 304944,
                    'ancestor_name' => 'Dynaformer',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1273384,
                    'style_name' => 'Sommervieu',
                    'race_outcome_position' => 0,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 304944,
                    'ancestor_name' => 'Dynaformer',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1273384,
                    'style_name' => 'Sommervieu',
                    'race_outcome_position' => 4,
                    'no_of_runners' => 1,
                    'win_prize_money' => 362.52,
                ],
                [
                    'ancestor_uid' => 304944,
                    'ancestor_name' => 'Dynaformer',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1273384,
                    'style_name' => 'Sommervieu',
                    'race_outcome_position' => 13,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 1,
                    'no_of_runners' => 1,
                    'win_prize_money' => 6814.1593,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 3,
                    'no_of_runners' => 1,
                    'win_prize_money' => 855.5556,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 4,
                    'no_of_runners' => 3,
                    'win_prize_money' => 1416.5948,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 6,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 7,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 15,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 466278,
                    'ancestor_name' => 'Docksider',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1552019,
                    'style_name' => 'Our Anniversary',
                    'race_outcome_position' => 18,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 4,
                    'no_of_runners' => 1,
                    'win_prize_money' => 288.6,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 5,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 6,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 7,
                    'no_of_runners' => 2,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 9,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 12,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
                [
                    'ancestor_uid' => 480438,
                    'ancestor_name' => 'Fantastic Light',
                    'ancestor_country_origin_code' => 'USA',
                    'horse_uid' => 1182941,
                    'style_name' => 'Flying Onsite',
                    'race_outcome_position' => 14,
                    'no_of_runners' => 1,
                    'win_prize_money' => null,
                ],
            ],
            //Api\Mvc\DataProvider\TemporaryTable:85 ->dropTemporaryTable()
            '52c86dce42960ce6b09e3745c847f1b6' => [
            ],
        ];
    }
}
