<?php

namespace Tests\Stubs\DataProvider\Bo\Bloodstock\Stallion;

use Api\Input\Request\HorsesRequest;
use \Api\Row\Bloodstock\Stallion\SaleStatistics as SaleStatisticsRow;

class SaleStatistics extends \Api\DataProvider\Bo\Bloodstock\Stallion\SaleStatistics
{
    /**
     * @param HorsesRequest $request
     *
     * @return mixed
     */
    public function getSaleStatistics(HorsesRequest $request)
    {
        $data = [
            '531769_GB-IRE_foals' => [
                0 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Timmy Hyde',
                    'price' => 280000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                1 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Liam McAteer',
                    'price' => 140000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                2 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Herbertstown Stud',
                    'price' => 120000,
                    'exchange_rate' => 1.54,
                    'currency_code' => 'EUR',
                    'cur_code' => 'EUR',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                3 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Vendor',
                    'price' => 55000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                4 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'M',
                    'buyer_detail' => 'Withdrawn',
                    'price' => 0,
                    'exchange_rate' => 1.54,
                    'currency_code' => 'EUR',
                    'cur_code' => 'EUR',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                5 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Tammy Twomey',
                    'price' => 330000,
                    'exchange_rate' => 1.54,
                    'currency_code' => 'EUR',
                    'cur_code' => 'EUR',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                6 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'John McCormack Bloodstock',
                    'price' => 245000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                7 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Ronald Rauscher',
                    'price' => 220000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                8 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'Darley & Townsend',
                    'price' => 165000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
                9 => SaleStatisticsRow::createFromArray([
                    'sale_year' => 2003,
                    'horse_sex_flag' => 'F',
                    'buyer_detail' => 'B B A Ireland',
                    'price' => 110000,
                    'exchange_rate' => 0.95238,
                    'currency_code' => 'GNS',
                    'cur_code' => 'GBG',
                    'total_count' => null,
                    'colts' => null,
                    'fillies' => null,
                    'median' => null,
                    'price_max' => null,
                    'price_min' => null,
                    'price_average' => null,
                    'sales_count' => null,
                    'offered_count' => null,
                    'byers_count' => null,
                    'withdraws_count' => null,
                    'prices' => null,
                ]),
            ],
        ];

        return $data["{$request->getStallionId()}_{$request->getCountryFlag()}_{$request->getHorseRestriction()}"];
    }

    /**
     * @param HorsesRequest $request
     *
     * @return bool
     */
    public function checkExistenceOfSaleStatistics(HorsesRequest $request)
    {
        return true;
    }
}
